### ISSUE TITLE
[Bug report] Save LivePhoto failed on iOS

### ISSUE THREAD

**Issue by coronoal** [fluttercandies/flutter_photo_manager#1009]
### Version

2.7.1

### Platforms

iOS

### Device Model

iPhone 12 (iOS16.6.1)

### flutter info

```sh
flutter version 3.18.3
```

### How to reproduce?

ios save dynamic graph error. Obtain the data of a local dynamic graph, and then save the dynamic graph according to the obtained data. 4:3 scale photos succeed, others fail

### Example code (optional)

```Dart
void saveByAssetEntity(AssetEntity assetEntity) async {
    // assetEntity is a local dynamic graph
    // get file subtypeFile
    var file = await assetEntity.originFile;
    var subtypeFile = await assetEntity.originFileWithSubtype;

    // save to album，equivalent to copying
    var result = await PhotoManager.editor.darwin.saveLivePhoto(
      imageFile: file!,
      videoFile: subtypeFile!,
      title: 'IMG_123',
    );
    // when the picture scale is 4:3, success
    // but 1:1 16:9, fail
  }
```

**Comment by coronoal** [comment]
Hello, is there any progress on this issue, thank you

**Comment by AlexV525** [comment]
Could you provide an example data set with a corresponding photo and video?

**Comment by coronoal** [comment]
@AlexV525 Should be any iPhone equipment, shooting moving pictures, 1:1,16:9 have problems, 4:3 no problem. I have several Apple devices here, iOS16,17 and 18. Can you find an Apple device to test it? Thank you

**Comment by coronoal** [comment]
@AlexV525 This problem has been a year, can you repair it as soon as possible, thank you very much.

**Comment by AlexV525** [comment]
Saving unpaired photos and movies as a live photo is not guarantee to 100% success.

**Comment by coronoal** [comment]
@AlexV525  Pictures and videos are obtained from the original dynamic picture of the mobile phone and then saved. What is the reason for not pairing

**Comment by coronoal** [comment]
```
void saveByAssetEntity(AssetEntity assetEntity) async {
    // assetEntity is a live photo
    // get file subtypeFile
    var file = await assetEntity.originFile;
    var subtypeFile = await assetEntity.originFileWithSubtype;

    // save live photo
    // imageFile and videoFile from the same live photo, from the above code obtained
    var result = await PhotoManager.editor.darwin.saveLivePhoto(
      imageFile: file!,
      videoFile: subtypeFile!,
      title: 'IMG_123',
    );
    // when the photo scale is 4:3, success
    // but 1:1 16:9, fail
  }
```

**Comment by coronoal** [comment]
@AlexV525 The sample code is as follows, this one should have no unpaired problem, and the photos taken at 4:3 have no problem, but the other 1:1, 16:9 have problems.

```
void saveByAssetEntity(AssetEntity assetEntity) async {
    // assetEntity is a live photo
    // get file subtypeFile
    var file = await assetEntity.originFile;
    var subtypeFile = await assetEntity.originFileWithSubtype;

    // save live photo
    // imageFile and videoFile from the same live photo, from the above code obtained
    var result = await PhotoManager.editor.darwin.saveLivePhoto(
      imageFile: file!,
      videoFile: subtypeFile!,
      title: 'IMG_123',
    );
    
    // when the photo scale is 4:3, success
    // but 1:1 16:9, fail
  }
```

**Comment by AlexV525** [comment]
@coronoal Could you try with the PR https://github.com/fluttercandies/flutter_photo_manager/pull/1186 to verify if it fixes the issue?

**Comment by coronoal** [comment]
@AlexV525 Fixed! Thank you very much!! Looking forward to the pub release

**Comment by coronoal** [comment]
@AlexV525 Thank you for the newly obtained and saved repair. The previous version of the obtained moving picture resources tried to save the moving picture again and reported an error. Can this be repaired?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PHPhotosErrorDomain (-1), 未能完成操作。（PHPhotosErrorDomain错误-1。）, No failure reason provided, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      IosPlugin.saveLivePhoto (package:photo_manager/src/internal/plugin.dart:692:24)
<asynchronous suspension>
```

**Comment by coronoal** [comment]
@AlexV525 Thank you for the newly obtained and saved repair. The previous version of the obtained moving picture resources tried to save the moving picture again and reported an error. Can this be repaired?

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PHPhotosErrorDomain (-1), 未能完成操作。（PHPhotosErrorDomain错误-1。）, No failure reason provided, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      IosPlugin.saveLivePhoto (package:photo_manager/src/internal/plugin.dart:692:24)
<asynchronous suspension>
```

**Comment by AlexV525** [comment]
> @AlexV525 Thank you for the newly obtained and saved repair. The previous version of the obtained moving picture resources tried to save the moving picture again and reported an error. Can this be repaired?

Please submit new issues with detailed info.
