### ISSUE TITLE
Why don't we implement caching on the native side i.e (kotlin for Android and swift for IOS)

### ISSUE THREAD

**Issue by Muzammil-Bit** [fluttercandies/flutter_photo_manager#1012]
### Platforms

Android, iOS

### Description

I think handling the cache on the native side with hugely improve the image loading time on the flutter side. 

### Why

- The issue arrives when we try to render 50+ images of high-resolution
- The issue is most prominent when we display heic images taken from iPhone.

**Comment by AlexV525** [comment]
Please read sources before asking such questions.

**Comment by Muzammil-Bit** [comment]
> Please read sources before asking such questions.

I am new to open source, I genuinely really like this plugin and would love to learn more and contribute, can you tell me what sources?
