### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by axroromonov** [fluttercandies/flutter_photo_manager#1014]
### Version

2.7.2

### Platforms

iOS

### Device Model

Iphone 14 pro

### flutter info

```sh
all right
```

### How to reproduce?

Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/photo_manager-2.7.2/lib/src/internal/image_provider.dart:72:28: Error: The parameter 'decode' of the method 'AssetEntityImageProvider.load' has type 'Future<Codec> Function(ImmutableBuffer, {TargetImageSize Function(int, int)? getTargetSize})', which does not match the corresponding type, 'Future<Codec> Function(Uint8List, {bool allowUpscaling, int? cacheHeight, int? cacheWidth})', in the overridden method, 'ImageProvider.load'.

How to fix it ? pls help
Error launching application on iPhone 14 Pro.

### Logs

```sh
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/photo_manager-2.7.2/lib/src/internal/image_provider.dart:72:28: Error: The parameter 'decode' of the method 'AssetEntityImageProvider.load' has type 'Future<Codec> Function(ImmutableBuffer, {TargetImageSize Function(int, int)? getTargetSize})', which does not match the corresponding type, 'Future<Codec> Function(Uint8List, {bool allowUpscaling, int? cacheHeight, int? cacheWidth})', in the overridden method, 'ImageProvider.load'.

How to fix it ? pls help
Error launching application on iPhone 14 Pro.
```

### Contact

axroromonov

**Comment by axroromonov** [comment]
3.13.8 I have flutter version like this

**Comment by CaiJingLong** [comment]
#1021
