### ISSUE TITLE
[Feature request] Assets compression / encoding

### ISSUE THREAD

**Issue by delfme** [fluttercandies/flutter_photo_manager#1016]
### Platforms

dart

### Description

Hello,
We currently compress the fetched images / videos ourselves outside photomanager. Was wondering if that feature could be added to the plugin such that it would silently (in background) compress the media with a specified compression ratio (+ optional width height) and desire result format (jpg / mp4).

Is that something you might be adding in the next future? 

### Why

High performant media compression / format encoding and resize is bit tricky and usually end up involving different plugins on the native side. We are adopting this solution at the moment, but it would be great if that burden might  be shifted onto PhotoManager. To us, it would also make sense, being that the plugin is envisioned as a Manager and not just a picker.

**Comment by CaiJingLong** [comment]
There are currently no such plans. Video transcoding and image conversion formats are very professional fields, and it is currently difficult to integrate them into this plug-in.
