### ISSUE TITLE
How can I get around a `isAuth == false`?

### ISSUE THREAD

**Issue by nidegen** [fluttercandies/flutter_photo_manager#1031]
### Platforms

Android

### Description

I call `final status = await PhotoManager.requestPermissionExtend();`, but this gives me `status.isAuth == false`, even when the app is marked to have media mermissions in the Android settings app.

What else could be wrong?

### My code

```
final status = await PhotoManager.requestPermissionExtend();
    if (!status.isAuth) {
```

**Comment by CaiJingLong** [comment]
Android OS version and plugins version is required.

**Comment by nidegen** [comment]
Of course: Same on both photo_manager 2.8.1 on Pixel3a with Android 12

**Comment by CaiJingLong** [comment]
I can't reproduce it.
I push a commit(d2af9e07163e820fae15b2d797f3837d63251e83) for example.

<img width="622" alt="image" src="https://github.com/fluttercandies/flutter_photo_manager/assets/14145407/5c3ea9e6-1d27-4870-930f-c8253e940464">

**Comment by nidegen** [comment]
My code works too in your example. Must be some AndroidManifest config error

**Comment by nidegen** [comment]
I can't make it work, changing Android settings etc. Can you have a look?
Here my example: [MRE.zip](https://github.com/fluttercandies/flutter_photo_manager/files/13365019/MRE.zip)

**Comment by CaiJingLong** [comment]
I try to test your project, change next it.

The `READ_EXTERNAL_STORAGE` will be ignored in API 33, not API 31.

By the way, this permission is defined in photo_manger, so removing it is another possible method.

```patch
--- android/app/src/main/AndroidManifest.xml    2023-11-16 11:04:57.000000000 +0800
+++ android/app/src/main/AndroidManifest-new.xml        2023-11-16 11:04:48.000000000 +0800
@@ -10,7 +10,7 @@
     <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
     <uses-permission android:name="android.permission.USE_FINGERPRINT" />
     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" tools:ignore="ScopedStorage"/>
-    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="30" tools:ignore="ScopedStorage"/>
+    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" tools:ignore="ScopedStorage"/>
     <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
     <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
     <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
```

**Comment by nidegen** [comment]
Are you saying I do not need to add any permission keys?

**Comment by CaiJingLong** [comment]
Just READ_EXTERNAL_STORAGE.

https://github.com/fluttercandies/flutter_photo_manager/blob/5f7fe257af6909433838e86812c10f3a1d5c1c5a/android/src/main/AndroidManifest.xml#L1-L5

**Comment by nidegen** [comment]
Just to be sure: My example did work for you?
