### ISSUE TITLE
photo_manager-2.8.1/lib/src/internal/image_provider.dart:7 1:5: Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercandies/flutter_photo_manager#1039]
### Platforms

dart

### Description

photo_manager-2.8.1/lib/src/internal/image_provider.dart:7
1:5: Error: Type 'DecoderCallback' not found.

### Why

photo_manager-2.8.1/lib/src/internal/image_provider.dart:7
1:5: Error: Type 'DecoderCallback' not found.

**Comment by shinesincere** [comment]
I'm also getting this error with Flutter 3.16.0 and Dart 3.2.0

**Comment by AlexV525** [comment]
Duplicate of #1021
