### ISSUE TITLE
[How to use] How am I able to generate an error if thumbnail is not loaded (iCloud) 

### ISSUE THREAD

**Issue by danialhr** [fluttercandies/flutter_photo_manager#1040]
### Platforms

iOS

### Description

My gallery gets stuck at loading skeleton once it detects a video file without a thumbnail.   I am trying to recreate it like how Instagram did. *Circled video is the one that thumbnail is not loaded. But I am unable to do so as we are unable to detect the status of the thumbnail. 

Is it possible detect if a thumbnail is not loaded? My suggestion is modify the getThumbnail method to return a special value (e.g., null) when the thumbnail is not loaded so that we can skip that file and load another? 

I would be please if there is another way I could handle this, without needing the above changes. 

![IMG_8762](https://github.com/fluttercandies/flutter_photo_manager/assets/7851981/eb5c4b45-75bf-40c5-ad5c-21003a473e8e)

**Comment by CaiJingLong** [comment]
The asset is a live photo, and asset exists but is just loading?
Is there any stable replication code? In other words, provide a complete page code, and its input parameter should be an AssetPathEntity.

**Comment by danialhr** [comment]
We did manage to create a work around managed to resolve this. Thanks for the initial response.
