### ISSUE TITLE
[Bug report] When syncing cropped images from iCloud, isLocallyAvailable(isOrigin: true) always returns false.

### ISSUE THREAD

**Issue by sy5075391** [fluttercandies/flutter_photo_manager#1047]
### Version

2.8.1

### Platforms

iOS

### Device Model

any

### flutter info

```sh
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale en-GB)
    • Flutter version 3.13.9 on channel stable at /Users/who/dev/flutter3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.dartlang.org
    • Flutter download mirror https://storage.googleapis.com
```

### How to reproduce?

When syncing cropped images from iCloud, isLocallyAvailable(isOrigin: true) always returns false.

I discovered a possible reason from the following code:
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/19810700/78c85b91-c9f1-49ae-8e6b-e77e5422a845)
The array returned by this method has more than one element, but based on the data, it appears that the value of the last element should be retrieved.
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/19810700/7d91d383-3623-4e90-811e-fb65bcccb5e5)

**Comment by AlexV525** [comment]
@sy5075391 Sorry for the late reply. Can you extract those resources and verify their corresponding images? Like which one is the raw picture and which one is edited.
