### ISSUE TITLE
[How to use] Android 14 limited photos access

### ISSUE THREAD

**Issue by StigUK** [fluttercandies/flutter_photo_manager#1053]
### Platforms

Android

### Description

We know that Android 14 added the ability for the user to give access to not all photos and videos.
I tested this on version 3.0.0-dev.4 and the requestPermissionExtend function returns the "authorized" status. Is there any way to find out that the user has not given access to all photos (as it now works on iOS). I mean, would requestPermissionExtend return PermissionState.limited in this case?

### My code

Manifest:
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/34726461/08782749-4acc-4fc7-9faf-8846f2463090)

Code:
final PermissionState status = await PhotoManager.requestPermissionExtend();
print(status);

Demo: https://github.com/StigUK/permission_demo

**Comment by CaiJingLong** [comment]
What is the return result?

**Comment by StigUK** [comment]
> What is the return result?

If I heve READ_MEDIA_VISUAL_USER_SELECTED in my manifest result is "PermissionState.authorized"

**Comment by CaiJingLong** [comment]
I'll check it in next days.

**Comment by HenrikH96** [comment]
I upgraded to version 3.0.0-dev.5, and it initially worked once. However, I now consistently receive PermissionState.authorized, even though it should be in a limited state. I conducted this test on a Pixel 7 running Android 14.

**Comment by Nikzed** [comment]
> I upgraded to version 3.0.0-dev.5, and it initially worked once. However, I now consistently receive PermissionState.authorized, even though it should be in a limited state. I conducted this test on a Pixel 7 running Android 14.

Same, why are we getting `PermissionState.authorized`, and is there any way to "reaccess" this photos? What if I want to add more to the selection range?
