### ISSUE TITLE
photo_manager doesn't pass static analysis with latest version of flutter

### ISSUE THREAD

**Issue by rbarzel** [fluttercandies/flutter_photo_manager#1054]
### Version

2.8.1

### Platforms

dart

### Device Model

all

### flutter info

```sh
flutter_photo_manager
```

### How to reproduce?

Hi, just a note in case you were unaware the Latest version of flutter has removed `DecoderCallback`, which breaks photo_manager.

https://pub.dev/packages/photo_manager/score

Thanks!

**Comment by AlexV525** [comment]
Duplicate of #1021
