### ISSUE TITLE
Execution failed for task ':photo_manager:compileDebugJavaWithJavac'. > 错误: 无效的源发行版：17

### ISSUE THREAD

**Issue by steven-gao** [fluttercandies/flutter_photo_manager#1057]
### Platforms

Android

### Description

1 use photo_manager ^3.0.0-dev.2
2  run  flutter run

**Comment by steven-gao** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.5.1 22G90 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.3 on channel stable at /Users/gaotaiwen/Desktop/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gaotaiwen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/gaotaiwen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.1)
    • VS Code at /Users/gaotaiwen/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.5.1 22G90 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.62

**Comment by CaiJingLong** [comment]
Origin issue: https://github.com/fluttercandies/flutter_photo_manager/issues/1023

See doc: https://fluttercandies.github.io/flutter_photo_manager_plugins/photo_manager/gradle/java-version/
