### ISSUE TITLE
[Bug report]  - API 34(Android 14) returns allways empty in  "PhotoManager.getAssetPathList();"

### ISSUE THREAD

**Issue by diogozup** [fluttercandies/flutter_photo_manager#1063]
### Version

version:  2.8.1  

### Platforms

dart, Android

### Device Model

Android Pixel XL API 34

### flutter info

```sh
zup@zup:~/Desktop/memes$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on Linux Mint 19.1 5.4.0-150-generic, locale en_US.UTF-8)
    • Flutter version 3.3.7 on channel stable at /home/zup/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (1 year, 2 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/zup/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/zup/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/zup/Development/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Linux Mint 19.1 5.4.0-150-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5993.117

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
zup@zup:~/Desktop/memes$
```

### How to reproduce?

after "var permissionState = await PhotoManager.requestPermissionExtend();" is authorized, it still always returns empty when "final List<AssetPathEntity> paths = await PhotoManager.getAssetPathList();".  This only happens when running the emulator Android 14 (API 34)

### Logs

```sh
returns empty array
```

**Comment by diogozup** [comment]
Thanks in advance for a fast reply.
hope everyone is doing great who is reading this ticket.

**Comment by AlexV525** [comment]
Is this reproducible using the example?

**Comment by diogozup** [comment]
yes. just test in a emulator with android 14 (api 34)
________________________________
De: Alex Li ***@***.***>
Enviado: 20 de dezembro de 2023 05:04
Para: fluttercandies/flutter_photo_manager ***@***.***>
Cc: diogozup ***@***.***>; Author ***@***.***>
Assunto: Re: [fluttercandies/flutter_photo_manager] [Bug report] - API 34(Android 14) returns allways empty in "PhotoManager.getAssetPathList();" (Issue #1063)


Is this reproducible using the example?

**Comment by AlexV525** [comment]
Emulator often shows empty assets until you've browsed them in the Gallery app, and it requires a reboot after you import aseets. Can you verify that?

**Comment by yunlongwang888** [comment]
I have encountered the same problem！

**Comment by diogozup** [comment]
Closed? not planned? what is that suposed to mean?

**Comment by AlexV525** [comment]
> Emulator often shows empty assets until you've browsed them in the Gallery app, and it requires a reboot after you import aseets. Can you verify that?

**Comment by diogozup** [comment]
> > Emulator often shows empty assets until you've browsed them in the Gallery app, and it requires a reboot after you import aseets. Can you verify that?

Should an feature have such work to function or user should simply tap a button and display all assets from a folder? features shoulnd be easy, intuitive for the end user or all of users should be expert advanced users. i hope this helps y understand that your question is not very relevant because even if it works with that steps, its useless for usage since users wont be using or even figuring out what to do

**Comment by AlexV525** [comment]
> i hope this helps y understand that your question is not very relevant because even if it works with that steps, its useless for usage since users wont be using or even figuring out what to do

Users won't use emulators in the normal world. We've seen many similar behaviors related to emulators and you happened to use the emulator to test, which is why I'm suggesting to verify if I'm correct about the emulator issue. If not, provide other reproducible steps since you've clarified it's only happening on the API 34 emulator.

**Comment by diogozup** [comment]
Its tested also in physical device. Thats not the point. the point is api 34 its bugged. i think that is made clear already
________________________________
De: Alex Li ***@***.***>
Enviado: 28 de dezembro de 2023 09:12
Para: fluttercandies/flutter_photo_manager ***@***.***>
Cc: diogozup ***@***.***>; Author ***@***.***>
Assunto: Re: [fluttercandies/flutter_photo_manager] [Bug report] - API 34(Android 14) returns allways empty in "PhotoManager.getAssetPathList();" (Issue #1063)


i hope this helps y understand that your question is not very relevant because even if it works with that steps, its useless for usage since users wont be using or even figuring out what to do

Users won't use emulators in the normal world. We've seen many similar behaviors related to emulators and you happened to use the emulator to test, which is why I'm suggesting to verify if I'm correct about the emulator issue. If not, provide other reproducible steps since you've clarified it's only happening on the API 34 emulator.

**Comment by diogozup** [comment]
Alex thanks for the effort y put into this but i can only explain stuff, i cant make u understand stuff.
Have a good day
________________________________
De: Alex Li ***@***.***>
Enviado: 28 de dezembro de 2023 09:12
Para: fluttercandies/flutter_photo_manager ***@***.***>
Cc: diogozup ***@***.***>; Author ***@***.***>
Assunto: Re: [fluttercandies/flutter_photo_manager] [Bug report] - API 34(Android 14) returns allways empty in "PhotoManager.getAssetPathList();" (Issue #1063)


i hope this helps y understand that your question is not very relevant because even if it works with that steps, its useless for usage since users wont be using or even figuring out what to do

Users won't use emulators in the normal world. We've seen many similar behaviors related to emulators and you happened to use the emulator to test, which is why I'm suggesting to verify if I'm correct about the emulator issue. If not, provide other reproducible steps since you've clarified it's only happening on the API 34 emulator.

**Comment by AlexV525** [comment]
| API 34 Emulator | ColorsOS 14 (Android 14) |
|-----|-----|
| ![image](https://github.com/fluttercandies/flutter_photo_manager/assets/15884415/a2565866-019e-428e-9db5-8ec4b71baeae) |  ![image](https://github.com/fluttercandies/flutter_photo_manager/assets/15884415/1762d446-7cf1-4f10-9d8e-14a1e636ae9a) |

**Comment by diogozup** [comment]
var ps = PhotoManager.requestPermissionExtend();
                      print(ps); // autorized

                      List<AssetPathEntity> assetPaths = await PhotoManager.getAssetPathList(type: RequestType.image);
print("value: " + assetPaths.lenght.toString()) // value: 0

**Comment by AlexV525** [comment]
I cannot reproduce this using the example on Android API 34 Emulator and real device, as I've already stated: https://github.com/fluttercandies/flutter_photo_manager/issues/1063#issuecomment-1871017991

**Comment by AlexV525** [comment]
Sure. Please use the example to record.

**Comment by diogozup** [comment]
i created a wetransfer link with video: https://we.tl/t-yI5V4ySO7U

**Comment by diogozup** [comment]
dont know if that is the right way to do this procedure. if not, please advise how to proceed. 
Thansk!

**Comment by diogozup** [comment]
Gets the same behaviour. Want me to record?

**Comment by AlexV525** [comment]
> Gets the same behaviour. Want me to record?

Yep. Please make sure your device includes images.
