### ISSUE TITLE
[How to use] Update a modified video in the Library

### ISSUE THREAD

**Issue by kaciula** [fluttercandies/flutter_photo_manager#1065]
### Platforms

iOS

### Description

I want to be able to modify a video from an album and to update it in the album and Library.

### My code

I am getting the originFile, modify it and save it in place. But the changes do not appear in the video from the album. So I am guessing the originFile isn't actually the original file but it's only a copy.

**Comment by AlexV525** [comment]
Please provide details of your issue. It's unclear for us about what environment we need to reproduce.

**Comment by kaciula** [comment]
@AlexV525 

`// Get origin video file

(await AssetEntity.fromId(fileId))!.originFile

// Do some modifications to the origin video file such as trim start and end of video using video tools and save as originFile

// The iPhone gallery does not show the updated video. How can I replace the original video file with the modified one in the Gallery?
`

**Comment by AlexV525** [comment]
What I meant is provide a detailed platform/package/flutter information, also whether the video is captured as any special type such as HDR, and whether it's uploaded to iCloud and whether it's locally available. And any other necessary information.

**Comment by AlexV525** [comment]
Bonus point: record a screenrecording using the example of the plugin to reproduce.

**Comment by AlexV525** [comment]
BTW, after modifications, you'll need to refetch the entity to grab it's latest references in order to obtain the correct file.

**Comment by kaciula** [comment]
@AlexV525 I am refetching the entity but getMediaUrl still shows the original video file. And the iPhone Photos app still shows the original video file. But the originFile contains the modified video file.

**Comment by AlexV525** [comment]
> I am getting the originFile, modify it and save it in place. But the changes do not appear in the video from the album. So I am guessing the originFile isn't actually the original file but it's only a copy.

Reviewing the request again, the plugin is not scoping to modify assets in the gallery, and it does make a copy into the sandbox of your app due to security limitations.
