### ISSUE TITLE
[Bug report] Huawei Permission 

### ISSUE THREAD

**Issue by HenrikH96** [fluttercandies/flutter_photo_manager#1067]
### Version

3.0.0-dev.5

### Platforms

dart, Android

### Device Model

Huawei p30 

### flutter info

```sh
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
    • Flutter version 3.16.5 on channel stable at C:\Users\Henrik\fvm\versions\3.16.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

### How to reproduce?

After requesting permission with ```PermissionState permisson = await PhotoManager.requestPermissionExtend();``` , the permission enum always returns Permission.denied, even though I granted access.

### Contact

hh@jourries.com

**Comment by HenrikH96** [comment]
Upon further investigation, I discovered that Huawei phones, including the one I have, require storage permission. Although ```Photomanager.requestPermission```  grants it, the return value consistently remains PermissionState.denied

**Comment by AlexV525** [comment]
What is the issue exactly? We don't know your device info yet.

**Comment by HenrikH96** [comment]
@AlexV525 
I tested it on a Huawei P30 with EMUI 12. When using `Photomanager.requestPermission`, the permission prompt is displayed, but it never receives authorization. To work around this issue, I checked for storage permission using `permission_handler`, which successfully granted storage permission. Consequently, I proceeded even though the `Photomanager` permission state remained as `PermissionState.denied`.

All other functionalities appear to work correctly, and I haven't encountered any additional issues. The only concern is that the `PermissionState` is not reflecting the actual permission status in this particular case.

**Comment by AlexV525** [comment]
Can you provide a minimal reproducible example? Or share your usage code about what permissions you've requested using the permission_handler?

**Comment by HenrikH96** [comment]
Certainly. Here's my workaround. After implementing this, I handle permission states accordingly. 
The `performAction` boolean is used later to determine whether to navigate to AppSettings or not.
```
Future<PermissionState> checkPermission({bool performAction = true}) async {
    PermissionState permisson = await PhotoManager.requestPermissionExtend();
    if (permisson == PermissionState.denied) {
      //Huawei extra
      PermissionStatus storageStatus = await Permission.storage.request();
      if (storageStatus.isGranted) {
        permisson = PermissionState.authorized;
      }
    }
    
    [...]
 }
```

**Comment by AlexV525** [comment]
Did you declare the storage permission in your manifest? What Android API level is your Huawei device? Can it be reproduced on other devices that have the same API level?

**Comment by jeevareddy** [comment]
@AlexV525,
I believe it is simply reproducible with Android 10 (API 29).

**Comment by jeevareddy** [comment]
Adding this permission resolves the permission.denied issue with Android 10
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29"/>

**Comment by HenrikH96** [comment]
@jeevareddy 
Thank's that seems to fix the Issue I had with Huawei
