### ISSUE TITLE
[How to use] Preload thumbnails

### ISSUE THREAD

**Issue by dodatw** [fluttercandies/flutter_photo_manager#1078]
### Platforms

iOS

### Description

Hi, we'd like to improve the scrolling experience of our app's photo picker, just like the native one. 
We've added gaplessPlayback = true, it improve, but not enough.

On Native, it almost show thumbnail immediately and no show placeholder. On Photo_Manager, we need wait 300ms~1 sec.
If I use ScrollBar and drag bar fast, the thumbnail will generate slow and slow. It look like a task queue issue.

https://pub.dev/packages/photo_manager#preload-thumbnails
We found a chapter about `PhotoCachingManager`, but not detail now to use it, is it can improve my case?
How it work between `PhotoCachingManager` and `thumbnailDataWithSize` ? 
Because it seem do different if I cache after scrolling ?

**Comment by AlexV525** [comment]
You can easily add another cache layer between the plugin and your displays, obtain the bytes, and save them as a cache file in your app's cache.
