### ISSUE TITLE
[How to use] Is it possible to load videos that are not in the Photo Library but are on the file system?

### ISSUE THREAD

**Issue by kaciula** [fluttercandies/flutter_photo_manager#1079]
### Platforms

iOS

### Description

Is it possible to load videos that are not in the Photo Library but are on the file system? The user may have videos/photos on the file system (on My iPhone folder) that are not saved in the Photo Library.

**Comment by AlexV525** [comment]
Nope. This is not the scope of the plugin. You'll need to build entities on top of the `AssetEntity/AssetPathEntity`.
