### ISSUE TITLE
[Feature request] android provide image uri

### ISSUE THREAD

**Issue by lwj1994** [fluttercandies/flutter_photo_manager#1083]
### Platforms

Android

### Description

```dart
  Future<String?> getMediaUrl() async {
    if (type == AssetType.video || type == AssetType.audio || isLivePhoto) {
      return plugin.getMediaUrl(this);
    }
    return null;
  }
```

provide image uri

### Why

when pick image in webview，it only receive image uri

**Comment by AlexV525** [comment]
Would `content://media/external/image/media/102` work with WebView? That doesn't sound correct.

**Comment by lwj1994** [comment]
> Would `content://media/external/image/media/102` work with WebView? That doesn't sound correct.

after  allow `_isAndroidImage` get uri， it works .
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/10978048/5ac676b1-7e7e-4150-a3d0-33c7da31fad0)  
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/10978048/5a75406c-500a-457e-b8b4-b48ee8c00bb8)

can i pr this commit?

**Comment by lwj1994** [comment]
After my test，in flutter_webview，only uri is effective
```dart
androidController.setOnShowFileSelector((FileSelectorParams params) async {
      switch (params.mode) {
        case FileSelectorMode.open:
        case FileSelectorMode.openMultiple:
          final assetEntity = await Picker.pickAImage(
              AppMainPage.scaffoldKey.currentContext!);
          if (assetEntity == null) return [];
          return [
            assetEntity.androidUri.isNotEmpty
                ? assetEntity.androidUri
                : assetEntity.filePath
          ];
```

**Comment by lwj1994** [comment]
usring uri seems reasonable that file path cannot be accessed after 30
