### ISSUE TITLE
[How to use] Android API 34 ACCESS_MEDIA_LOCATION is denied if user selected limited access to photos and videos

### ISSUE THREAD

**Issue by StigUK** [fluttercandies/flutter_photo_manager#1089]
### Platforms

Android

### Description

I am requesting access to media files on Android 14 (api 34) using PhotoManager (version 3.0.0-dev.5).
Provided that the user chooses not full, but **limited access** to the gallery of permissions, ACCESS_MEDIA_LOCATION is always returned as **denied**. This means I can't get coordinates from the metadata of a photo or video.

If the user gives **full access**, then the ACCESS_MEDIA_LOCATION status is returned as **granted**.

I don’t know for sure whether this is a library bug, or whether it’s a feature of API 34, which is why I didn’t file this as a bug report.

### My code

import 'package:photo_manager/photo_manager.dart';
import 'package:permission_handler/permission_handler.dart';

Future<void> test() async {
         final PermissionState permissionState = await PhotoManager.requestPermissionExtend();
         final PermissionStatus accessMediaLocationStatus = await Permission.accessMediaLocation.status;
       ///If permissionState is limited => accessMediaLocationStatus  is denied
       ///If permissionState is authorized => accessMediaLocationStatus is granted
}

**Comment by ashilkn** [comment]
I was facing `ACCESS_MEDIA_LOCATION` denied/not-requested issue on photo_manager v2.8.1. It's not exactly your issue, but this helped me resolve mine.

```
 final permissionState = await PhotoManager.requestPermissionExtend(
        requestOption: const PermissionRequestOption(
          androidPermission: AndroidPermission(
            type: RequestType.common,
            mediaLocation: true,
          ),
        ),
      );
```

`mediaLocation` is set to false by default, changing it fixed my issue. See if this works for you as well?

**Comment by mozammal-Hossain-dev** [comment]
@StigUK , you can try @ashilkn's solution and also give the below permission for the Android:

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>



These procedures solved the issue for Android API 34.

**Comment by AlexV525** [comment]
as https://github.com/fluttercandies/flutter_photo_manager/issues/1089#issuecomment-2027999973 explained

**Comment by TheAnh188** [comment]
![Screenshot 2024-12-01 234730](https://github.com/user-attachments/assets/2acf3f24-5427-4440-873f-ab77a2fde7ba)
![Screenshot 2024-12-01 234741](https://github.com/user-attachments/assets/db01210d-6280-4931-b9fa-45cd0acd3159)
I couldn't set permission is authorized. Does anyone face this problem ?
