### ISSUE TITLE
[Feature request] Access path from asset

### ISSUE THREAD

**Issue by martyfuhry** [fluttercandies/flutter_photo_manager#1095]
### Platforms

dart, Android, iOS

### Description

I would like to access the path of the asset by calling `asset.path` to get the full path.

### Why

Currently, the only way to do this is by loading the entire file:

```dart
final file = await asset.originFile;
final path = file.path;
```

I don't need to load the entire file, I only want to know the path.

**Comment by AlexV525** [comment]
File is not entirely loaded at this point.
