### ISSUE TITLE
[Feature request] Allow to choose more photos after limited access Android 14

### ISSUE THREAD

**Issue by Nikzed** [fluttercandies/flutter_photo_manager#1096]
### Platforms

dart, Android

### Description

I need to allow users to change their photos selection if they decide to add more photos after `Select photos and videos`.
Or force them to allow access to all photos if it's possible.
<img width="227" alt="image" src="https://github.com/fluttercandies/flutter_photo_manager/assets/38156331/790cc133-ca45-4a5f-9c83-8a8cc9da4e62">

Right now I get `PermissionState.authorized` status after calling `PhotoManager.requestPermissionExtend`

**Comment by CaiJingLong** [comment]
1. Forced access to all pictures is not possible due to system version restrictions.
2. If "limited access" has been set, you need to call the `PhotoManager.presentLimited()` method to repick asset by user.
