### ISSUE TITLE
[Bug report] The latlngAsync() method is not working in the 3.0.0 version.

### ISSUE THREAD

**Issue by gpf0205** [fluttercandies/flutter_photo_manager#1113]
### Version

3.0.0

### Platforms

Android

### Device Model

vivo(android 11)

### flutter info

```sh
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
```

### How to reproduce?

On the same Android device and with the same image, the latlngAsync() method can be executed normally to obtain the location information in the image under the Flutter 3.13.9+photo_manager: 2.7.0 environment. However, in the Flutter 3.19.3+photo_manager: 3.0.0 environment, the latlngAsync() method cannot obtain the location information in the image.

**Comment by AlexV525** [comment]
Did you request the media location permission when calling the `requestPermissionExtend`?
