### ISSUE TITLE
[Bug report] portrait photos from 2018-2020 appear as libraries

### ISSUE THREAD

**Issue by benmccann** [fluttercandies/flutter_photo_manager#1115]
### Version

3.0.0-dev.5

### Platforms

Android

### Device Model

Pixel 7 (Android 14)

### flutter info

```sh
I installed a Flutter app from the Play store, so don't know the answer to this one
```

### How to reproduce?

I encountered this issue when using [Immich](https://immich.app/). When I installed that app it told me that I had 85 image libraries that could be backed up, but Google Photos said I had only 8. They suggested that it was caused by this library.

I was able to determine that was likely because there are some folders under DCIM/Camera that are causing this. The dates on the folders correspond to 2018-2020. I guess that maybe that's how portrait mode used to work?

![Screenshot_20240414-125938](https://github.com/fluttercandies/flutter_photo_manager/assets/322311/897c98ad-2cb4-471a-9e26-77982edf36eb)

![Screenshot from 2024-04-14 16-09-28](https://github.com/fluttercandies/flutter_photo_manager/assets/322311/b016dfb2-3832-4ece-8257-19d4e5cd512c)

### Example code (optional)

```Dart
In case it helps, the code for the Immich project is located here: https://github.com/immich-app/immich/tree/main/mobile
```

**Comment by benmccann** [comment]
Is there something we should be doing as consumers of `flutter_photo_manager` to filter them out then just as android / google photos does?

**Comment by AlexV525** [comment]
> Is there something we should be doing as consumers of `flutter_photo_manager` to filter them out then just as android / google photos does?

To do this, you might need to customize a mechanism like `SortPathDelegate` to manipulate your libraries. The plugin only reads from the database and makes abstractions without extra modifications. The custom implementation for Google Photos is not within our supporting scope.
