### ISSUE TITLE
[Bug report] size of the originFile is wrong

### ISSUE THREAD

**Issue by coronoal** [fluttercandies/flutter_photo_manager#1123]
### Version

3.1.0

### Platforms

iOS

### Device Model

iPhone 12 (iOS17.4.1)

### flutter info

```sh
Flutter 3.19.6
```

### How to reproduce?

iOS device.
get the originFile of the photo, then to display it or save it locally, the size of the picture is wrong.
1:1, 4:3, 16:9 will all become 4:3

but 3.0.0 correct

### Example code (optional)

```Dart
void saveByAssetEntity(AssetEntity assetEntity) async {
    // get originFile
    var file = await assetEntity.originFile;

    // save it locally or display
    var result = await PhotoManager.editor.darwin.saveImageWithPath(
      imageFile: file!.path,
      title: 'IMG_123',
    );

    // 1:1, 4:3, 16:9 will all become 4:3
  }
```

**Comment by AlexV525** [comment]
Might be fixed by #1140. Please verify
