### ISSUE TITLE
[Bug report] No new photos available with v3.1.0

### ISSUE THREAD

**Issue by matthiasn** [fluttercandies/flutter_photo_manager#1125]
### Version

3.1.0

### Platforms

iOS

### Device Model

iPhone 14 Pro 

### flutter info

```sh
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.19.6 on channel stable at /Users/mn/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mn/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mn/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mn/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • Fred (2) (mobile) • 00008120-001A70290CC0C01E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### How to reproduce?

After updating to v3.1.0, only photos from prior to the update are available for selection when using `AssetPicker.pickAssets`. No photos made afterwards are visible at all. New screenshots made in the meantime are visible, however.

Reverting to v3.0.0 fixes the issue, after downgrading, everything works as expected again.

**Comment by AlexV525** [comment]
Follow the migration guide might be helpful.

**Comment by matthiasn** [comment]
@AlexV525 thanks 🙏  I'm actually not using `photo_manager` directly at all, only (flutter_wechat_assets_picker)[https://github.com/fluttercandies/flutter_wechat_assets_picker] but I must have at some point added the dependency separately and then updated. After removing `photo_manager` from `pub spec.yaml`, `3.0.0` is picked correctly. 

Closing this issue as it's working again. I guess the migration is then something to consider in `flutter_wechat_assets_picker` at some point.

**Comment by matthiasn** [comment]
Actually no, maybe I closed this too soon. `flutter pub upgrade` will update to `3.1.0` and then break the photo picker. But it's mostly an issue with [flutter_wechat_assets_picker](https://github.com/fluttercandies/flutter_wechat_assets_picker) not pinning the version, so I'll raise the issue there, for anyone who runs into the same issue.
