### ISSUE TITLE
[Discussions] wechat_assets_picker图片选择在鸿蒙系统显示

### ISSUE THREAD

**Issue by luhongalex** [fluttercandies/flutter_photo_manager#1129]
### Content

目前photo_manager已适配完成（pub最新版本），本地运行wechat_assets_picker可以正常选择图片，但是在点击图片预览时显示黑屏无图片展示，源码中看是使用的extended_image相关组件

https://github.com/fluttercandies/extended_image/assets/39117934/dd32b866-ae16-417d-bd17-475a660ffb82
日志中没有异常
请问有什么解决方法吗？

**Comment by luhongalex** [comment]
![isLocallyAvailable](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/a4a85b54-268b-403a-91ad-f612d2697f3e)
![log1](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/e0a0f989-e19c-4b1c-b4b4-a89ee568eca9)

目前看代码逻辑 执行到_checkLocallyAvailable方法是调用photoManager的isLocallyAvailable方法无回调

**Comment by luhongalex** [comment]
详细代码
![code](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/ccd44a1d-da9c-4c26-920d-1c2fc328873f)
![log](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/0928a944-12fd-4a60-8650-8093cf8c710a)

**Comment by zmtzawqlp** [comment]
Future<bool> isLocallyAvailable(String id, {bool isOrigin = false}) async {
    if (Platform.isAndroid || PlatformUtils.isOhos) {
      return true;
    }

你本地可以先改成这样一下

**Comment by zmtzawqlp** [comment]
video，这种依赖外接纹理的。都还有问题。

**Comment by luhongalex** [comment]
https://gitee.com/openharmony-sig/flutter_packages/tree/master/packages/video_player
gitee上video_player已经适配完成了
目前日志打印 pm中的getMediaUrl未返回
![log](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/def5f659-8c4c-4530-baf7-918da47e9d8e)

![code](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/a9a9b381-4b7a-471c-85f8-0a868c1de338)

**Comment by luhongalex** [comment]
![videoController](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/09115463-7365-436d-b0ee-5dc0a76e7c97)
ohos的controller目前仅支持fileFd的方式

**Comment by luhongalex** [comment]
id:  file://media/Photo/3/VID_1715753395_000/VID_20240515_140823.mp4
目前controller初始化不支持contentUri以及file这种方式，只有fildFd这种
![videoController](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/f36ea074-5ba1-4af2-8f7a-901a0bd2f0e2)

**Comment by zmtzawqlp** [comment]
那就是要 file 的id，我看看呢

**Comment by luhongalex** [comment]
![fileFd](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/bea0a04f-f1ab-460d-9fa6-b56e017b0bbd)
id已经通过这种方式获取到了
但是 执行到controller.initialize()时不继续往下执行了

**Comment by zmtzawqlp** [comment]
> ![fileFd](https://private-user-images.githubusercontent.com/39117934/331027965-bea0a04f-f1ab-460d-9fa6-b56e017b0bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjkyMzAsIm5iZiI6MTcxNTgyODkzMCwicGF0aCI6Ii8zOTExNzkzNC8zMzEwMjc5NjUtYmVhMGEwNGYtZjFhYi00NjBkLTlmYTYtYjU2ZTAxN2IwYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZjQwNDMzNjUyY2EyNmNjNzExYmEyODY1YTRkNTk1ODIyZmM3MDYyYWRjMWZmNTliY2JkOGViMDc5NGQwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQ2Y5bxUgpE8tvlgMsoWkSwNkMjud9Z_2Sd2dP8mYlY) id已经通过这种方式获取到了 但是 执行到controller.initialize()时不继续往下执行了

那要问问社区的了

**Comment by luhongalex** [comment]
好的。
上面图片预览的问题，可以先修改更新个小版本吗？

**Comment by zmtzawqlp** [comment]
> 好的。 上面图片预览的问题，可以先修改更新个小版本吗？

正在修改，还要看看 wechat_assets_picker， getFileFd 方法应该是只有 鸿蒙才有的

**Comment by luhongalex** [comment]
好的

**Comment by zmtzawqlp** [comment]
可以加 qq群 981630644，这样反馈更快速些

**Comment by luhongalex** [comment]
已申请加入

**Comment by zmtzawqlp** [comment]
我试了一下。可以播放，用fd

**Comment by luhongalex** [comment]
您那边怎么使用，可以截图发下部分代码吗？

**Comment by zmtzawqlp** [comment]
我只是在 pm 里面改的。。wechat_assets_picker 要改的地方蛮多的。。

**Comment by luhongalex** [comment]
您那边预计什么时候可以更新？

**Comment by luhongalex** [comment]
还有另外一个小问题  视频的时长显示不对
![image](https://github.com/fluttercandies/flutter_photo_manager/assets/39117934/44fcfd0b-13e1-45de-9a47-eb0842024e59)

**Comment by zmtzawqlp** [comment]
应该是鸿蒙那个时间，跟其他平台不一致吧，我看看

**Comment by zmtzawqlp** [comment]
> 您那边预计什么时候可以更新？

https://github.com/fluttercandies/flutter_photo_manager/pull/1131

**Comment by luhongalex** [comment]
好的

**Comment by zmtzawqlp** [comment]
> 还有另外一个小问题 视频的时长显示不对 ![image](https://private-user-images.githubusercontent.com/39117934/331115023-44fcfd0b-13e1-45de-9a47-eb0842024e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDgyMDcsIm5iZiI6MTcxNTg0NzkwNywicGF0aCI6Ii8zOTExNzkzNC8zMzExMTUwMjMtNDRmY2ZkMGItMTNlMS00NWRlLTlhNDctZWIwODQyMDI0ZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDM5NDFkMjkyMzk5ODgyMTQzNzE2MWUxZWFmZGQ2ZjI3ZGYzMGRmMmRmMjg5NGE0NjhjZjA5N2ZhMzE3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7aFEIK4R-2_QfcsbuS14By9Z0VAU7CThni6OO9phneA)

好的，忘记除以1000

**Comment by luhongalex** [comment]
好的

**Comment by zmtzawqlp** [comment]
适配了wechat_assets_picker 一起发，你着急。可以先引用这个分支

> #1131 pm适配完成之后 wechat_assets_picker涉及到的部分会更新并发布新版本吗？

**Comment by luhongalex** [comment]
好的

**Comment by zmtzawqlp** [comment]
> 好的

https://gitee.com/openharmony-sig/flutter_packages/issues/I9PZBG?from=project-issue  

最终api 应该还会变。。我在提pr 让 video player 支持 file://格式

**Comment by luhongalex** [comment]
好的，我们也提了issuereporter 支持file或者contentUri，目前还没有回复

**Comment by zmtzawqlp** [comment]
> 好的，我们也提了issuereporter 支持file或者contentUri，目前还没有回复

靠鸿蒙那边。感觉很慢。我现在是在插件里面 通过 file 去拿到 fd 的

**Comment by luhongalex** [comment]
好的

**Comment by AlexV525** [comment]
对应平台已不再开放权限。
