### ISSUE TITLE
[BUG] iOS Preview shows original image instead of edited picture

### ISSUE THREAD

**Issue by anderson-oki** [fluttercandies/flutter_photo_manager#1136]
**Describe the bug**

The issue that occurred on fluttercandies/flutter_wechat_assets_picker#74 started happening again on version `9.x`. iOS large image preview shows the original image after has been edited. Also when retrieving the image for upload or anything else, the original image is retrieved instead of the one that has been edited.

1. Take a screenshot on iOS
2. Edit the image using the gallery editor and Save
3. Open the we chat asset editor and select the saved edited image

**Expected behavior**
The edited image instead of the original should be selected for upload

**Version information**

- Device: iPhone 15 Pro, iPhone 14 Pro
- OS: iOS 17.5.1
- Package Version: 9.0.3
- Flutter Version: 3.19.6

**Additional context**
It was working fine on ^8.9.0-dev.1

**Comment by sumichell** [comment]
I'm having a similar problem.

This problem occurs when images are retrieved using `AssetEntity.originFile`.
It does not occur if I use `AssetEntity.file` to get the image, but the EXIF information is lost.
At least during April this bug did not occur.
It still occurs after changing to ^8.9.0-dev.1 in my environment.
If you know how to fix this bug, please let me know.
