### ISSUE TITLE
[Feature request] Why not expose the file path of Android images?

### ISSUE THREAD

**Issue by 6a209** [fluttercandies/flutter_photo_manager#1138]
### Platforms

Android

### Description

here is kotlin class  
```

data class AssetEntity(
    val id: Long,
    var path: String,

```

it's has the "path" 

but the dart class  AssetEntity  don't has  the "path".    

when i use the "path" on dart  i need to call 
```
 File? file = await entity.file;  
 final paht =  file.path;
```

it's will query again the database then get the "path" to generate the file then return to path to dart. 

Why not directly expose the path field?

**Comment by AlexV525** [comment]
The path might be invalid if only the scoped storage is allowed. Exposing path also does not help with cross-platform abstractions.
