### ISSUE TITLE
[BUG] image width and height reversed.

### ISSUE THREAD

**Issue by SwiftyWang** [fluttercandies/flutter_photo_manager#1139]
**Describe the bug**

Get the image from CameraPicker.pickFromCamera(context); the orientatedWidth and orientatedHeight are reversed.

**How to reproduce**

1. add the following line to HomePage.dart L31 in example code. 
`print('swifty:${result.orientation} ${result.orientatedWidth} ${result.orientatedHeight}');`
2. press `Taking photos` to take a vertical photo.
3. from the log it shows swifty:0 3840 2160 which means a horizontal photo.

**Expected behavior**

the orientatedWidth should be 2160. orientatedHeight should be 3840
**Screenshots (If contains)**

**Version information**

- Device: Sumsung, Xiaomi
- OS: Android 11,Android 13
- Package Version: master branch.
- Flutter Version: 3.16.9, 3.22.1

**Additional context**

**Comment by AlexV525** [comment]
Offline discussed with related developers that the Samsung phone always produces invalid orientation in the EXIF. Solving particular brand devices is out of the scope of the plugin.

**Comment by SwiftyWang** [comment]
> Offline discussed with related developers that the Samsung phone always produces invalid orientation in the EXIF. Solving particular brand devices is out of the scope of the plugin.

Also reproduced in Xiaomi 10 pro~
