### ISSUE TITLE
[Bug] When trying to fetch 100 images, it returns latest 99 images. only happening in specific devices.

### ISSUE THREAD

**Issue by nileshmsd12345** [fluttercandies/flutter_photo_manager#1141]
### Version

3.0.0

### Platforms

Android

### Device Model

One plus Nord2 5g android version 11

### flutter info

```sh
Flutter (Channel stable, 3.19.6, on macOS 14.3.1 23D60 darwin-arm64, locale en-IN)
    • Flutter version 3.19.6 on channel stable at /Users/nileshsahu/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
```

### How to reproduce?

Implement a custom gallery using the photo_manager plugin.
Use the getAssetPathList method to get the list of galleries.
Fetch images using the getAssetListPaged method with a page size of 100.
Observe that only the latest images are fetched on certain devices.

### Example code (optional)

```Dart
final List<AssetPathEntity> galleries =
          await PhotoManager.getAssetPathList(
        onlyAll: true,
        type: RequestType.image,
      );
      final List<AssetEntity> newAssets = await galleries[0].getAssetListPaged(
        page: 0,
        size: 100,
      );
```

**Comment by AlexV525** [comment]
Isn't that indicate the device only has 99 images in the gallery?

**Comment by nileshmsd12345** [comment]
> Isn't that indicate the device only has 99 images in the gallery?

No, that's not the case. when i set the page size to 50, it fetches all the images, at least more than 100. and this is very device specific issue.

**Comment by AlexV525** [comment]
Can you set a break point and take a screenshot with those variables that includes your requested page size and the returned size?
