### ISSUE TITLE
photo throw an error when build project:A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### ISSUE THREAD

**Issue by yaochangliang159** [fluttercandies/flutter_photo_manager#1144]
### Version

photo_manager3.0.0

### Platforms

dart, Android

### Device Model

redmi note 12 turbo

### flutter info

```sh
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.5 23F79 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.19.4 on channel stable at /Users/dhkj/flutter3.x/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (3 months ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dhkj/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/dhkj/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (6 available)
    • 23049RAD8C (mobile) • ceda2243                                 •
      android-arm64  • Android 14 (API 34)
    • 测试机iPhone (mobile)  • 00008110-001670D21ABA201E                • ios
      • iOS 17.5.1 21F90
    • 姚常亮的iPhone (mobile) • 78f2c5b4b0325fd3d9406ec2c807501687f3d606 • ios
      • iOS 15.8.2 19H384
    • 徐延棋的iphone (mobile) • 00008110-000574C93ADA801E                • ios
      • iOS 17.4.1 21E236
    • macOS (desktop)     • macos                                    •
      darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)        • chrome                                   •
      web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for iPhone of Kui. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### How to reproduce?

when i run flutter build apk  in my project,it throw an error ,the error  log is under this page

### Logs

```sh
e: /Users/yaochangliang/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionDelegate.kt: (18, 16): Redeclaration: PermissionDelegate
e: /Users/yaochangliang/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.0.0/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate29.kt: (11, 7): Redeclaration: PermissionDelegate29
e: /Users/yaochangliang/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.1.1/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/PermissionDelegate.kt: (17, 16): Redeclaration: PermissionDelegate
e: /Users/yaochangliang/.pub-cache/hosted/pub.flutter-io.cn/photo_manager-3.1.1/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/impl/PermissionDelegate29.kt: (13, 7): Redeclaration: PermissionDelegate29

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':photo_manager:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Error: Gradle task assembleDebug failed with exit code 1
```

### Example code (optional)

```Dart
no code
```

### Contact

805650956@qq.com

**Comment by yaochangliang159** [comment]
my build.gradle:

buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven {
            allowInsecureProtocol = true
            url 'https://maven.aliyun.com/nexus/content/groups/public'
        }
//        google()
//        // mavenCentral()
//        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven {
            allowInsecureProtocol = true
            url 'https://maven.aliyun.com/nexus/content/groups/public'
        }
//        google()
//        // mavenCentral()
//        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by AlexV525** [comment]
flutter clean

**Comment by yaochangliang159** [comment]
my build gradle:


buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
//        maven { url 'https://maven.aliyun.com/repository/google' }
//        maven { url 'https://maven.aliyun.com/repository/jcenter' }
//        maven { url 'https://maven.aliyun.com/repository/public' }
        jcenter()
        google()
        mavenCentral()

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
//        maven { url 'https://maven.aliyun.com/repository/google' }
//        maven { url 'https://maven.aliyun.com/repository/jcenter' }
//        maven { url 'https://maven.aliyun.com/repository/public' }
        jcenter()
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
