### ISSUE TITLE
[Bug report] containsLivePhotos be deprecated, how to disable live photo in future?

### ISSUE THREAD

**Issue by dodatw** [fluttercandies/flutter_photo_manager#1150]
### Version

3.2.0

### Platforms

dart

### Device Model

All

### flutter info

```sh
flutter 3.13.3
```

### How to reproduce?

I saw containsLivePhotos be deprecated.
How can I disable live photo in right way ?
```
    @Deprecated(
      'The option will be always enabled by default. '
      'This will be removed in v4.0.0',
    )
    this.containsLivePhotos = true,
```

**Comment by AlexV525** [comment]
Live Photos are image + video so when you are obtaining it like images it behaves the same as other images. In this case it makes no difference with others.

**Comment by dodatw** [comment]
For my use case, I need it for video picker.

Some case I need "video with livePhoto", some case I need "video without livePhoto".
How can I do that after containsLivePhotos be removed

Thanks.

**Comment by AlexV525** [comment]
Use a custom filter to grab video assets and Live Photos subtype resources. Live Photos are images in concept.

**Comment by dodatw** [comment]
Oh, I found different from 2.8 to 3.2

in Photo_Manager 2.8,
If I set RequestType.video and containsLivePhotos = true,
I get "Video + Live Photos".

in Photo_Manager 3.2,
If I set RequestType.video, no matter containsLivePhotos is true or false,
I only get Video.

In new version , Live photo is photo.

If I set RequestType.common, (video and image), I get "video + live photo + photo", that is not I want.

How to set correct filterOption to get "Video + LivePhoto" result ?
FilterOptionGroup seem no way to set option.

I need "video + LivePhoto" result like before.

**Comment by AlexV525** [comment]
https://pub.dev/documentation/photo_manager/latest/photo_manager/CustomFilter-class.html

**Comment by dodatw** [comment]
Wow, CustomFilter is very powerful,
is that mean, if I need "Video + LivePhotos"
I need to set type to `RequestType.common` and filter pure photo ?

Is there any example for the sql comman ?

**Comment by AlexV525** [comment]
Yeah that's it. Additionally placing the filter only on iOS should complete your demand.
