### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by bladeofgod** [fluttercandies/flutter_photo_manager#1153]
### Platforms

iOS

### Description

I want to get exception from native at flutter side.
Would we provide it? t thanks :)

**Comment by AlexV525** [comment]
What exception?

**Comment by bladeofgod** [comment]
> What exception?

Error Domain=PHPhotosErrorDomain Code=3302

**Comment by AlexV525** [comment]
What method throws the exception?

**Comment by bladeofgod** [comment]
> What method throws the exception?

await PhotoManager.editor.saveVideo();
