### ISSUE TITLE
[Feature request] To get AssetEntity with local asset path

### ISSUE THREAD

**Issue by ManmohanTalwar** [fluttercandies/flutter_photo_manager#1170]
### Platforms

Android, iOS

### Description

If we could have a way to fetch the assetEntity based on the asset path.

### Why

I am using [flutter_sharing_intent](https://pub.dev/packages/flutter_sharing_intent) package, which allows user to share any gallery/other-installed-apps media to my app. I get a `SharedFile` object, which only provides the file path.

I have tried the solution @AlexV525 you suggested in #795 and it is working perfectly fine, but it just creates an duplicate file in the device, as some users can select larger files or nonetheless it will always create duplicate files, which is an issue.

It will be very useful if it can be supported by the plugin, rather then having to creates duplicates.

**Comment by AlexV525** [comment]
The reason has been well-explained in https://github.com/fluttercandies/flutter_photo_manager/issues/795#issuecomment-1182983821. Closing as duplicated.

A reasonable approach is to maintain the relation between `SharedFile` and `AssetEntity` mappings locally so you won't create duplicate entities, but this is still out of the scope of the plugin.
