### ISSUE TITLE
[Bug report] saveLivePhoto error

### ISSUE THREAD

**Issue by coronoal** [fluttercandies/flutter_photo_manager#1181]
### Version

3.3.0

### Platforms

iOS

### Device Model

iPhone 12 (iOS16.6.1)

### flutter info

```sh
Flutter (Channel stable, 3.22.3
```

### How to reproduce?

```
AssetEntity? resultEntity =
            await PhotoManager.editor.darwin.saveLivePhoto(
          imageFile: imageFile,
          videoFile: videoFile,
          filename: fileName,
        );
```

saveLivePhoto error. But the last version is normal.

### Logs

```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'CastMap<Object?, Object?, dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'
#0      IosPlugin.saveLivePhoto (package:photo_manager/src/internal/plugin.dart:696:50)
```

**Comment by passerby-yyds** [comment]
![image](https://github.com/user-attachments/assets/0bda5967-df69-486a-bff9-6564a514fbad)
![image](https://github.com/user-attachments/assets/338ed18a-7592-4199-85e6-1a7cc9a77b86)

**Comment by emmett-deen** [comment]
@coronoal you mentioned `saveLivePhoto error. But the last version is normal.` what was the last version you were using that this worked?

**Comment by emmett-deen** [comment]
> @coronoal you mentioned `saveLivePhoto error. But the last version is normal.` what was the last version you were using that this worked?

After some of my own testing, it looks to still work with v3.2.3
