### ISSUE TITLE
[How to use] create fail, error: Error Domain=PHPhotosErrorDomain Code=3302 "(null)"

### ISSUE THREAD

**Issue by Flajt** [fluttercandies/flutter_photo_manager#1190]
### Platforms

iOS

### Description

Not sure if that is a `How to use` or `Bug report` I went with this one, apologies if that was the wrong one.

What does: `create fail, error: Error Domain=PHPhotosErrorDomain Code=3302 "(null)"` mean and how can I resolve it?
I only found an inconclusive Stackoverflow post.

As notice: I'm trying to save an .mkv file, and if I remember correctly it worked once. 
The video file has been updated with FFmpeg, to include metadata, thats it.

### My code

```dart
Future<void> addToGalleryACleanUp(
      String initalPath, String finalPath, bool video) async {
    final outPutFile = File(finalPath);
    final initalFile = File(initalPath);
    final title = outPutFile.path.split("/").last;
    print(title);
    if (Platform.isAndroid || Platform.isIOS) {
      //This is to prevent file deletion while running flutter test (since all file paths are fake)
      if (video) {
        await PhotoManager.editor.saveVideo(outPutFile); // <- This one
      } else {
        await PhotoManager.editor.saveImageWithPath(outPutFile.path);
      }
      if (initalPath != finalPath) {
        await initalFile.delete();
      }
    }
  }
```

I would like to know what the issue is and how can I remedy it.

### Try do it

Adding a title with file type, trying to figure out what the error is, upgrade to v `3.4.0`.

Note: The "full access Photo permission" has been granted & the file is stored under the `ApplicationDocumentsDirectory` and shows up there.

**Comment by Flajt** [comment]
Ran the same code with an `.mp4`file. Worked.... my guess would now be: No support for .mkv files in the gallery.
(I could swear I managed to get it to work once before)

**Comment by Fansvaer** [comment]
I had the same problem. This is because iOS Gallery does not support saving mkv files

**Comment by Flajt** [comment]
@Fansvaer thanks. I feared that much. Rather suboptimal in my case but whatever. I'll guess I have to change the file format...

Do you know by any chance if there is a list with supported file types out there?

**Comment by Flajt** [comment]
Ok, thanks anyway. I'll guess well have to try and see what works and what not.

mp4 seems to work out. I'll try webm later today

**Comment by Flajt** [comment]
@Fansvaer I think I found an overview:

```
Your photos and videos are stored in iCloud in their original format at full resolution. 
Formats include HEIF, JPEG, RAW, PNG, GIF, TIFF, HEVC and MP4, as well as special formats you capture with your iPhone or iPad, such as slo-mo, time-lapse, 4K videos and Live Photos. 
The photos and videos you capture with these devices are in [HEIF and HEVC](https://support.apple.com/en-gb/116944) format. 
Depending on your internet speed, the time it takes for you to see your photos and videos on all of your devices and iCloud.com may vary
```

So: 
**Images**: PNG, JPEG,RAW, HEIF, TIFF

**Video**: GIF, MP4 , HEVC

source: [https://discussions.apple.com](https://discussions.apple.com/thread/253066035?sortBy=rank)

Still have to test for webm.

**Comment by AlexV525** [comment]
I think supported file types are typically the `AVFileType`.

https://developer.apple.com/documentation/avfoundation/avfiletype

**Comment by Flajt** [comment]
Seems more viable, since HEVC is not supported apparently.

**Comment by AlexV525** [comment]
Closing based on the above doc reference and discussions.
