### ISSUE TITLE
[BUG] PhotoManager.editor.saveVideo 返回null

### ISSUE THREAD

**Issue by zxk-design** [fluttercandies/flutter_photo_manager#1197]
**Describe the bug**
使用 wechat_camera_picker-4.3.1 录制视频 点击确定按钮时 
查看源码发现 会调用entity = await PhotoManager.editor.saveVideo(
              previewFile,
              title: path.basename(filePath),
            );
            部分手机返回null 

**How to reproduce**
wechat_camera_picker-4.3.1 的官方demo 录制视频部分手机会出现

录制视频-点击确定

**Expected behavior**
调用entity = await PhotoManager.editor.saveVideo(
              previewFile,
              title: path.basename(filePath),
            );会返回entity ！= null

**Screenshots (If contains)**
在控制台上点击确定按钮后 出现的日志 供参考
<img width="740" alt="image" src="https://github.com/user-attachments/assets/fd4d77e0-2c2a-490d-a5cf-1204f73ee1c5">
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/cb7d8f38-7c18-4f4e-af88-95fcaadc1842">

**Comment by AlexV525** [comment]
你应该是使用了 camerax 的构建，目前 camera picker 使用的不是对应的包。保存非媒体的后缀是无效的
