### ISSUE TITLE
[BUG] 使用该库从相册选择图片，报错，一直打不开，具体报错日志已贴到描述中

### ISSUE THREAD

**Issue by yuanhoujun** [fluttercandies/flutter_photo_manager#1214]
**Describe the bug**

并非所有手机都能复现，目前测试在MIX3手机上面一直出现。

使用该库从相册选择图片，报错，一直打不开

**Expected behavior**

可以正常打开相册选择图片

**Screenshots (If contains)**

**Version information**

- Device: MIX3
- OS: Android 10
- Package Version: 9.3.3
- Flutter Version: 3.24.3
**Additional context**

从提示来看，是从数据库中查询到数据，实际并不存在该图片，可确定是否在某些情况下，存在数据库查询图片存在，而实际并不存在导致，是否可以过滤掉不存在的图片，仅显示已经存在的图片。

**Comment by AlexV525** [comment]
Revert to 3.5.0 should temporary fix this.

**Comment by AlexV525** [comment]
Could someone verify if #1216 fixes this?

**Comment by yuanhoujun** [comment]
> Could someone verify if #1216 fixes this?

I fixed the version of photo_manager to 3.5.0 and everything worked fine, I think your solution is correct

**Comment by AlexV525** [comment]
> I think your solution is correct

It would be great if you can test with the PR :)
