### ISSUE TITLE
[BUG] Assets list is not updated when set to limited access on android though settings, after pressing continue with limited access and selecting some files.

### ISSUE THREAD

**Issue by arthurpuha** [fluttercandies/flutter_photo_manager#1215]
Assets list is not updated when set to limited access on android though settings, after pressing continue with limited access and selecting some files.

**How to reproduce**
1.Set permission to limited access in phone settings on android. 
2. Open gallery picker. 
3. Proceed with limited access on the info screen.
4.  On screen with empty list press top button.
5. Select some photos for limited access. 
6. Previous page with empty list is not updated with selected photos.

**Expected behavior**
When we selected some assets for limited access those are displayed in the list.

**Version information**

- Device: Android
- OS: 14
- Package Version: [9.2.2]
- Flutter Version: [3.19.6]

**Comment by AlexV525** [comment]
I can see the same behavior by following your screen recording. Thanks!

The debug log tells that the limited permission is granted without asking.

```console
I/PhotoManager( 5377): Returned permissions: android.permission.READ_MEDIA_VISUAL_USER_SELECTED
I/PhotoManager( 5377): Returned permissions: android.permission.READ_MEDIA_VIDEO
I/PhotoManager( 5377): Returned permissions: android.permission.READ_MEDIA_IMAGES
D/PhotoManager( 5377): dealResult: 
D/PhotoManager( 5377):   permissions: [Ljava.lang.String;@8adcaca
D/PhotoManager( 5377):   grantResults: [I@805143b
D/PhotoManager( 5377):   deniedPermissionsList: [android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_IMAGES]
D/PhotoManager( 5377):   grantedPermissionsList: [android.permission.READ_MEDIA_VISUAL_USER_SELECTED]
D/PhotoManager( 5377): [PermissionDelegate34] havePermissions: [android.permission.READ_MEDIA_VIDEO], result: false
D/PhotoManager( 5377): [PermissionDelegate34] havePermissions: [android.permission.READ_MEDIA_IMAGES], result: false
```

From the first look this might be a bug with Android 14 permissions.

**Comment by AlexV525** [comment]
Debugged around the permission delegate, in this case, `READ_MEDIA_VISUAL_USER_SELECTED` did return as *granted* from the application context, so there is a little bug with the permission in the Android. However, I've managed to find a workaround for the picker to get rid of permissions in this case.
