### ISSUE TITLE
[How to use] How can the user only select photos without explicitly authorize the app?

### ISSUE THREAD

**Issue by dayuy** [fluttercandies/flutter_photo_manager#1222]
### Platforms

iOS 16

### Description

According to [Determine Your App's Access Needs](https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app#3695529), `PHPickerViewCOntroller` , the user interface is private by default,  meaning the user doesn't need to explicitly authorize the app to select photos. How can I implement this in `photo_manager`?

### My code

```
dependencies:
  photo_manager: ^3.6.1
```

**Comment by fluttercandies-dev** [comment]
**AI Summary:** The user wants to use `photo_manager` to allow users to select photos without explicit authorization, similar to the behavior of `PHPickerViewController` on iOS. They are seeking guidance on how to achieve this functionality within the `photo_manager` package.

**Comment by AlexV525** [comment]
Can you use `PhotoManager.presentLimited` standalone?

**Comment by dayuy** [comment]
> Can you use `PhotoManager.presentLimited` standalone?

Thanks for your reply, It doesn't seem to be working,  The effect I'm aiming for is shown in the image below, appearing only in the iPhone photo permissions settings under `ONE-TIME PHOTO SELECTION`. 
I'll look into it further.


![image](https://github.com/user-attachments/assets/0539375a-3c81-4b08-a3ef-e8f55c544356)

**Comment by AlexV525** [comment]
Looks like you should use `image_picker` instead.

**Comment by dayuy** [comment]
> Looks like you should use `image_picker` instead.

yep, there is  an  [issue](https://github.com/flutter/flutter/issues/146400) being tracked.
