### ISSUE TITLE
Facing an Exception: Could not create Impeller texture. 

### ISSUE THREAD

**Issue by RKSigma** [fluttercandies/flutter_photo_manager#1251]
### Version

3.6.3

### Platforms

dart

### Device Model

ALL

### flutter info

```sh
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image frame:
Exception: Could not create Impeller texture.

When the exception was thrown, this was the stack: 
====================================================================================================
```

### How to reproduce?

Encountering an error while scrolling through some images.

Exception: Could not create Impeller texture.

![Screenshot 2024-12-25 at 9 18 53 AM](https://github.com/user-attachments/assets/b4b36303-85cd-4644-89cf-7c2997cab10e)

**Comment by fluttercandies-dev** [comment]
**AI Summary:** The user is encountering an "Exception: Could not create Impeller texture" error while scrolling through images in version 3.6.3 of the `photo_manager` package.
