### ISSUE TITLE
[Feature] move, copy, delete asset. Create album or folder.

### ISSUE THREAD

**Issue by CaiJingLong** [fluttercandies/flutter_photo_manager#231]
All of platform:
- [x] copy asset from an album to another.

----
For iOS:
- [x] create album or folder in recent or folder(iOS).
- [x] delete asset in album(iOS).
- [x] delete album(iOS).
- [x] delete folder(iOS).
- [x] favorite asset.

----
For android:
- [x] move asset from an album to another.
- [x] Iterate and delete all rows that do not exist in the local file, because it is a full scan, it may be slow.
- [ ] Specify the scan directory, file, if it is a type recognized by MediaStore, it will be added to MediaStore

----
Scanning the existing media without size and duration and updating the columns will not take effect. Because the width, height, and duration columns are read-only.

I'm just exploring the feasibility of the api, there is no guarantee that it can be completed. If the existing SDK API does not support this, it will remove todo.

**Comment by CaiJingLong** [comment]
Related #166 .

**Comment by rignaneseleo** [comment]
To trigger the galleries or create album you can check this out: https://pub.dev/packages/gallerytrigger

**Comment by CaiJingLong** [comment]
@rignaneseleo 
Thank you for your suggestion. I checked the plugin you wrote. 

I and your specific approach will be different. Not only trigger the system broadcast. 

https://github.com/CaiJingLong/flutter_photo_manager/blob/8ab010347ba1772c2191411e223d0dae83398270/android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt#L575-L640

Like my saveVideo or saveImage code, I will insert many fields as possible to MediaStore so that I can get more valid fields when using photo_manager to get assets.

**Comment by rignaneseleo** [comment]
`saveVideo` function doesn't work on Android 11. It returns always `null`. 
Please fix it.

**Comment by AlexV525** [comment]
Closing since this is completed as @CaiJingLong mentioned offline.
