### ISSUE TITLE
[Feature] ContentObserver for listening to MediaStore updates

### ISSUE THREAD

**Issue by vishnukvmd** [fluttercandies/flutter_photo_manager#380]
**Is your feature request related to a problem? Please describe.**
I'm building an application that backs up photos to a server. Currently the user has to open the app to detect new/updated photos on device. It would be nice to have a listener that is fired when the media store changes even when the app is not alive.

**Describe the solution you'd like**
I understand that this is not possible on iOS, but on Android we could perhaps have an interface over `ContentObserver`?

**Comment by AlexV525** [comment]
IMO It might better to have a separate plugin or built-in to the app itself to support.

**Comment by AlexV525** [comment]
Closing as above.
