### ISSUE TITLE
[Feature] Support filtering live photos

### ISSUE THREAD

**Issue by dodatw** [fluttercandies/flutter_photo_manager#386]
I want to select all video and Live photo on the iOS.
I can set requestType to requestType.common. but I will get all image.
I want to filter static image, only keep Live Photo. 

is it doable ?

**Comment by AlexV525** [comment]
Any documents from Apple that support to filter live photo directly?

**Comment by ua741** [comment]
> Any documents from Apple that support to filter live photo directly?

We can filter live photos by adding a filter on [mediaSubTypes](https://developer.apple.com/documentation/photokit/phasset/1624775-mediasubtypes?language=objc).  
See: https://stackoverflow.com/a/49495326 
> let liveImagesPredicate = NSPredicate(format: "(mediaSubtype & %d) != 0", PHAssetMediaSubtype.photoLive.rawValue)

StackOverflow References: 
[How to get videoUrl in case of live Photos](https://stackoverflow.com/a/45568364)
[Save Live Photo](https://stackoverflow.com/a/32911958)  (PhotoManager.editor.saveLivePhoto?)


------
Thank you for creating this extremely useful package, which is super easy to use :). 

We have been trying to add support for live photos in our project. For now we have been able to make it work by [adding subTypes](https://github.com/ente-io/flutter_photo_manager/commit/8e2989e4ad3336ffea20cd92762c1642de08840f) in PMAsset and created a simple plugin (swift based) to get the videoUrl. Due to lack of objective-C knowledge and time-constraint, we decided to go via this route instead of contributing to upstream directly. 

```swift
---
if(call.method == "getLivePhotoUrl") {
            if let args = call.arguments as? Dictionary<String, String?>,let assetID = args["id"]! {
                let assetsFound = PHAsset.fetchAssets(withLocalIdentifiers: [assetID], options: PHFetchOptions())
                if(assetsFound.count == 0) {
                    result(nil)
                } else {
                    fetchLivePhotoUrl(asset: assetsFound[0]) { [weak self] (url, err) in
                        guard let _ = self else { result(nil); return }
                        if (url != nil) {
                            result(url?.path)
                        } else {
                            result(nil)
                        }
                    }
                }
            } 
 ---           
func fetchLivePhotoUrl(asset: PHAsset, completionHandler: @escaping (URL?, Error?) -> Void) {
        let option = PHLivePhotoRequestOptions()
        option.deliveryMode = .highQualityFormat
        option.isNetworkAccessAllowed = true
        PHImageManager.default().requestLivePhoto(for: asset, targetSize: CGSize(width: CGFloat(asset.pixelWidth), height: CGFloat(asset.pixelHeight)),
                                                  contentMode: .default,
                                                  options: option) { [weak self] (livePhoto, info) in
            guard let self = self else { completionHandler(nil, nil); return }
            self.handleLivePhoto(asset: livePhoto, info: info, onCompletion: completionHandler)
        }
    }

    private func handleLivePhoto(asset: PHLivePhoto?,
                                 info: [AnyHashable: Any]?,
                                 onCompletion: @escaping (URL?, Error?) -> Void) {
        guard let asset = asset else { onCompletion(nil,nil); return}
        let resources = PHAssetResource.assetResources(for: asset)
        for resource in resources {
            if resource.type == .video || resource.type == .pairedVideo {
                let url = FileManager.default.temporaryDirectory.appendingPathComponent(resource.originalFilename)
                try? FileManager.default.removeItem(atPath: url.path)
                PHAssetResourceManager.default().writeData(for: resource, toFile: url, options: nil) { [weak self] (error) in
                    guard let _ = self else { onCompletion(nil, nil); return }
                    if (error != nil) {
                        onCompletion(nil, error)
                    } else {
                        onCompletion(url, nil)
                    }
                    return
                }
            }
        }
    }
```

**Comment by AlexV525** [comment]
Thanks for pointed out the documentation and the code snippet, we'll try to implement it, hopefully in a short term.

(I'm not an expert in Objective-C as well, but still can write some code by searching and repeatedly debugging. 😃 )

**Comment by AlexV525** [comment]
> I want to filter static image, only keep Live Photo.

To be clear, filtering Live Photo only might not be supported, since Android does not include such concept.

**Comment by AlexV525** [comment]
So the subtype and the media URL are both supported in recent PR #667 , but I found a little bit tricky when filtering with subtype. We can't use a single `NSPredicate` when we fetch assets, it's necessary to decide whether we should use `AND` or `OR` compound precidate.
