### ISSUE TITLE
[Feature] Adding a bool parameter to getAssetPathList  get albums/folders *excluding the hidden albums*

### ISSUE THREAD

**Issue by yasinarik** [fluttercandies/flutter_photo_manager#506]
Hi, basically, would you mind adding a feature so that when `getAssetPathList`is used, let us get albums/folders **excluding the hidden albums**?

The reason is that the users tend to be concerned about their privacy when I also get the "hidden" folder. (This is for iOS btw. I don't remember if Android has that feature too.)

I show both an album selector and the photos inside it. I can place an **if check** that checks the album names and if it equals "Hidden", I can just skip it and don't show that. 

However, people use their phones in different languages. So, there are different namings for the hidden album. For example, it is called **"Gizli"** in Turkish. **"Ausgeblendet"** in German/Deutsch. That means I have to filter them out for each and every language which is not practical and error-prone.

Is there a native solution for that?

Thanks a lot for your outstanding efforts!

**Comment by AlexV525** [comment]
Any documents from Apple that indicates the implementation to exclude "Hidden" albums?

**Comment by AlexV525** [comment]
I'm not seeing any *hidden albums* or *hidden assets* displayed by default with this plugin.

Closing since it seems invalid.

**Comment by zhulmin** [comment]
> Please let us know if there are any documents from Apple that indicates the implementation to exclude "Hidden" albums, then we'll try to implement it.
   
https://developer.apple.com/documentation/photokit/phasset/1624773-ishidden
