### ISSUE TITLE
[Feature] Execute stuff on separate thread - or different way to make it faster/not block UI

### ISSUE THREAD

**Issue by TheLastGimbus** [fluttercandies/flutter_photo_manager#587]
Hiii!

When calling any functions from this library, it usually takes *some* time - if I would like to get index of *all* media on device, it can take up to 5 seconds! This often blocks the main UI thread and makes app unresponsive

If there would be a way to move stuff done on native side to some separate thread or something, it would be much better!

**Comment by AlexV525** [comment]
Is this related to all platforms or a specific platform?

**Comment by TheLastGimbus** [comment]
I only have Android phone: Android 10 (LineageOS 17)

**Comment by TheLastGimbus** [comment]
Thank you :heart:  !!!
