### ISSUE TITLE
[BUG] getAssetListPaged doesnt work well

### ISSUE THREAD

**Issue by ajosecueto** [fluttercandies/flutter_photo_manager#588]
**Describe the bug**
getAssetListPaged doesnt work well when paginated album's assets, always return an empty list. Android 11 - Sumsung S21+

In Docs you can see:
  /// Doesn't support AssetPathEntity with only(Video/Image) flag.
  /// Throws UnsupportedError

but never throws an error...

```dart
  final filterOption = FilterOptionGroup()
      ..containsEmptyAlbum = false
      ..addOrderOption(
        const OrderOption(type: OrderOptionType.createDate),
      );
    paths = await PhotoManager.getAssetPathList(
        type: RequestType.common, filterOption: filterOption);

    newAssets = await selectedGallery!.getAssetListPaged(page, 50);
```

where page = 1 and all albums contains photos and videos...

Change getAssetListPaged to getAssetListRange works

```dart
      newAssets = await selectedGallery!.getAssetListRange(start: (page - 1) * 50, end: page * 50);
```

**To Reproduce**
1. List albums with type and filters
2. Select an album
3. Paginate album's assets

**Expected behavior**
Correct pagination system or API

**Flutter version**
2.2.3

**Smartphone (please complete the following information):**
 - Device: Samsung s21+
 - OS: Android 11

**Log**

No logs... Only an empty list.

**Comment by CaiJingLong** [comment]
Only Samsung phones have this problem? 
Have you tried other devices?

**Comment by ajosecueto** [comment]
Samsung note 20 (Android 11), Motorola one action (Android 10) and xiaomi mi 10 pro (Android 10).

**Comment by AlexV525** [comment]
`wechat_assets_picker` is using `getAssetListPaged` too and seems not running into this problem. Can you verify if it's reproducible?

**Comment by Cotspheer** [comment]
Can reproduce this on an emulator. Having the same issue.

- Flutter 3.0.0
- photo_manager: 2.1.1
- Device: Pixel 4 API 30 (android-x64 emulator) Android 11 Google Play

Call to `getAssetListRange(start: (page - 1) * take, end: page * take)` returns results as call to `getAssetListPaged(page: page, size: take)` (page is 1 and size is greater than 0) returns just an empty list. So not only a Samsung related issue I presume.

Did this with a clean build. Flutter doctor result:

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1526], locale de-DE)
    • Flutter version 3.0.0 at D:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Nighty\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

This issue does not occur on a test device using Huawei P20 Lite with Android 9. I think this happens only on Android 11 devices. Using the workaround from @ajosecueto for now (thanks for this).

**Comment by CaiJingLong** [comment]
> Reference in new issue
Can you provide an example github repository to reproduce the problem?
