### ISSUE TITLE
Number of images & video [Feature] 

### ISSUE THREAD

**Issue by marcodecarolisidt** [fluttercandies/flutter_photo_manager#594]
**Is your feature request related to a problem? Please describe.**
I know there is the assetCount property, but I need to know how many are images and how many are videos.
Is it possible to get it without fetching all the assets with getAssetPathList ?

With many assets, the getAssetPathList method is very slow

**Describe the solution you'd like**
Get an imageAssetCount & videoAssetsCount

**Comment by AlexV525** [comment]
Is there any documents that directly obtain images/videos count without extra requests?

**Comment by AlexV525** [comment]
Well, after some thinking, I think asynchronous getters will do.

**Comment by AlexV525** [comment]
Sorry, I missed the part that we already have `PhotoManager.getAssetCount`. You can access asset count with a specific request type and filtering options.
