### ISSUE TITLE
[BUG] Duplicate images on iOS are sorted differently from ios "Photos" app

### ISSUE THREAD

**Issue by iosephmagno** [fluttercandies/flutter_photo_manager#603]
**Describe the bug**
Sometime users duplicate images in their albums (eg. to apply different effects to the same pic). Noticed that all duplicated images are not loaded by photomanager.

**To Reproduce**
1. Load Recents album via photomanager
2. Duplicate an image via native photos app
3. Load album again via photomanager and see that duplicated image is neglected

Tested on iOS, it might affect android as well.

**Expected behavior**
Albums in photomanager should be an exact copy of what they are in native photos app.

**Flutter version**

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS:  iOS17.7.1

**Log**

If applicable, add logs to help explain your problem.

```bash

```

**Comment by AlexV525** [comment]
Could you tell me how to get a iOS 17 device? I'm really curious about it.

**Comment by iosephmagno** [comment]
Typo :) It’s 14.7.1

**Comment by AlexV525** [comment]
Versions, code snippets, screenshots/screenrecordings, and whether you've granted full permissions or not.

**Comment by iosephmagno** [comment]
How to reproduce issue on iphone XS, iOS 14.7.1, full permissions enabled, video/photos available below:
1. Open wechat assets picker
2. Load recents album
3. Switch to iOS photos and duplicate a photo (not the last one)
4. Switch back to wechat assets picker
5. Load recents album 
6. Duplicate photo in point 3 is ignored in the picker’s grid.

Video: https://www.dropbox.com/s/irws5adivc8exzv/Wechatsassetspicker.MP4?dl=0

Photos:
![828AC7C5-6B1A-4216-AFE2-49B17BBBE353](https://user-images.githubusercontent.com/83366073/134761940-ddc1695c-7495-467c-b027-39dbcfc7dbd5.png)

![8E6CB3CB-2E54-466A-83B8-89AAEC117868](https://user-images.githubusercontent.com/83366073/134761947-5afe2b71-ad81-4f97-82e0-f860d76333b5.png)

![766C28A3-D987-4061-A014-34038DAAB39D](https://user-images.githubusercontent.com/83366073/134761968-88c7751b-bc36-46ea-b281-fe4bff40498a.png)

![F2B7B305-66E4-4EE2-91A5-E348CF60734D](https://user-images.githubusercontent.com/83366073/134761979-869e6d54-e722-41ec-b96a-3867aa8a2fe4.png)

![BBDBBCC2-8269-4BCD-BC86-C6C0737C7E11](https://user-images.githubusercontent.com/83366073/134761985-7ea2a78f-aa80-48a9-a05e-428a394b618f.png)

**Comment by iosephmagno** [comment]
Noticed by chance that duplicate photo is not ignored, it is instead placed in the wrong place (see pic below, red “X” mark vs “check mark”). Check mark is the right chronological position (as in iOS photos app). This means there is a problem with duplicate photos’ timestamp. Not sure whether it depends on iOS or photomanager.


![D8ABA064-20C9-4493-92C9-5E14809EEB13](https://user-images.githubusercontent.com/83366073/134782880-fd54aca0-45e2-4c63-8d6a-81458c53d837.jpeg)

**Comment by AlexV525** [comment]
Can you verify if the #606 solve your problem?

**Comment by AlexV525** [comment]
See the description in #620 for the detailed behavior about the "Photos" app.

**Comment by iosephmagno** [comment]
A duplicate pic is placed soon after origin pic instead of being displayed as the most recent pic in the gallery. See pic below.

![4B23F430-FCB6-4FCF-904E-6A825DE07B02](https://user-images.githubusercontent.com/83366073/138249054-05bd81d7-ba0b-4a67-96b0-4c1caf935b82.jpeg)

**Comment by AlexV525** [comment]
Sure. I just want to confirm if the "Photos" app will keep these positions after it's been kill/restart, since last time photos that have been airdropped are re-positioned after the "Photos" app restart.

**Comment by AlexV525** [comment]
So we use the `creationDate` key as the default sort condition on iOS, which means duplicate photos might have the same creation date from the system, but gallery handles them differently.

**Comment by iosephmagno** [comment]
Maybe that was a temporarily bug from ios. Iphone’s photos stores new pics at most recent position (airdropped files included) and doesn’t change sorting after kill/restart.

**Comment by iosephmagno** [comment]
@AlexV525 any updates on this?

**Comment by AlexV525** [comment]
> @AlexV525 any updates on this?

Sorry that I'm personally busying in preparing for the DevFest next month, and these issues are all scheduled for further investigations.

**Comment by iosephmagno** [comment]
Thx for letting me know it. I will ping you again later on

**Comment by iosephmagno** [comment]
Hi Alex, any news on this?

**Comment by AlexV525** [comment]
cc @moyusword

**Comment by iosephmagno** [comment]
@AlexV525 @moyusword same issue occurs with airdropped files. If we send files over aidrop they don’t get placed as most recent in the Recents album’s grid. Also, airdropped videos aren’t listed at all in Recents album, they only appear in Video album. 

Tested on both ios 14 and 15. Bug is reproducible on wechat assets picker.

**Comment by AlexV525** [comment]
If you're indicating airdropped files too, I'm pretty sure it's the same issue that #620 is trying to fix, which is typically an iOS bug when new files are dropped and not following the creation date sort.

Closing as it seems to be resolved already, or cannot be solved until iOS fix this.

**Comment by iosephmagno** [comment]
I have read #620. Here are the differences I notice:
1) 620 says photos are positioned well when app is open yet and repositioned wrongly after it closes. We don’t experience this with Duplicate photos (they are positioned wrongly in both cases).
2) Airdropped videos are not placed in Recents album, either when app is open or after it is closed.

If you guys converge all ios sorting issues in #620, please check these differences.

**Comment by AlexV525** [comment]
I'll leave this open until we get more responses from iOS developers.

**Comment by AlexV525** [comment]
Also please file a separate issue for videos.

**Comment by AlexV525** [comment]
Please verify if #659 solves this problem.

**Comment by iosephmagno** [comment]
We will check soon and let you know here. Thx!

**Comment by iosephmagno** [comment]
Hi @AlexV525, we tested #659 and it doesn't fix this issue on iOS. Duplicate photos are still placed soon after original ones, and not as most recent ones in Recent's album grid

**Comment by AlexV525** [comment]
Can you make a screenrecord with the whole process?

**Comment by iosephmagno** [comment]
Checking this again. A team mate tested with an old iphone

**Comment by iosephmagno** [comment]
Is this fix also available in 1.3.10?

**Comment by AlexV525** [comment]
> Is this fix also available in 1.3.10?

Of course not...It's available through direct dependency or the 2.0.0-dev.1 version.

**Comment by iosephmagno** [comment]
Bug is fixed in 2.0.0 👍
