### ISSUE TITLE
[Release] 2.0.0

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_photo_manager#610]
### TODOs

- [x] API deprecations.
- [x] Breaking changes.
- [x] Code analysis improvements.
- [x] Document improvements.
- [x] Example improvements.
- [x] Migration guide.
- [x] Write an article: https://medium.flutter.cn/hard-to-manage-media-with-flutter-try-photo-manager-the-all-in-one-solution-5188599e4cf

### PRs

- #611
- #616
- #618
- #613
- #624
- #625
- #626
- #637
- #656
- #657
- #658
- #659
- #660
- #662
- #663
- #664
- #667
- #668
- #669
- #670
- #671
- #672
- #673
- #675
- #681
- #682
- #683
- #684
- #686
- #687
- #698
- #701
- #705
- #708
- #709
- #712
- #714
- #716
- #717
- #718
- #719
- #720

### Issues

- #386
- #584 
- #587 
- #592 
- #603
- #619
- #622
- #635 
- #636
- #639
- #647
- #649
- #650
- #654
- #655
- #665
- #678
- #704

**Comment by bounty1342** [comment]
Hey, is there something blocking to go stable on this version ?
Seem like there is a lot of improvement already 👍

**Comment by AlexV525** [comment]
> Hey, is there something blocking to go stable on this version?

I personally want to release three packages (this, and two pickers) to stable at once, since I'm trying to getting more deeper around every corner of these packages.

**Comment by AlexV525** [comment]
All requirements have been done, scheduled to release the version next Monday (7th March) if we didn't receive/find fixes anymore.
