### ISSUE TITLE
[BUG] PhotoManager.editor.saveImage is not preserving the title on iOS

### ISSUE THREAD

**Issue by vishnukvmd** [fluttercandies/flutter_photo_manager#619]
**Description**
Calling `PhotoManager.editor.saveImage(data, title: "title")` returns an asset, with an empty title.

**To Reproduce**
```dart
final asset = PhotoManager.editor.saveImage(data, title: "title");
print(asset.title); // will be an empty string
```

**Expected behavior**
The `title` that is passed to `saveImage` should be preserved in the `AssetEntity` that is returned.

**Flutter version**: Flutter version 2.5.2
**flutter_photo_manager version**: v1.3.6

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15.0.1

**Comment by AlexV525** [comment]
Is this an iOS 15 related issue? Has it happened on previous versions of iOS or the plugin?

**Comment by AlexV525** [comment]
Is this still happening?

**Comment by vishnukvmd** [comment]
Hey @AlexV525 , very sorry for the delayed response. I missed your previous question.

> Could you try with the version before we solved the previous title issue?

I checked out to https://github.com/fluttercandies/flutter_photo_manager/commit/9a0db1a6910612ed2526bf51c7987eadbf42e46f (v1.3.5), and verified that the issue exists there too. The prettification was introduced in v1.3.6.

> Is this still happening?

Yes it is.

**Comment by AlexV525** [comment]
Can you verify if bdba618afceb560def0116d78eea1cd2cfd9b74f still repro this issue?

**Comment by vishnukvmd** [comment]
This commit seems to have broken some things, mainly the ability to call `asset.id`. So I'm unable load and edit existing images, which is required for me to reproduce this scenario. 😢

**Comment by AlexV525** [comment]
> This commit seems to have broken some things, mainly the ability to call `asset.id`. So I'm unable load and edit existing images, which is required for me to reproduce this scenario. 😢

I think what we need here is a flag to control whether to preserve the title, as it's false by default when saving.

**Comment by AlexV525** [comment]
Further tips, 2.0 is about to release once all preparstions are done. If you have behavior breaking, make sure you verify them on that branch.

**Comment by vishnukvmd** [comment]
> > This commit seems to have broken some things, mainly the ability to call `asset.id`. So I'm unable load and edit existing images, which is required for me to reproduce this scenario. 😢
> 
> I think what we need here is a flag to control whether to preserve the title, as it's false by default when saving.

The `title` is an optional argument to `saveImage` right now. We could override only if the argument is set?

**Comment by AlexV525** [comment]
> The `title` is an optional argument to `saveImage` right now. We could override only if the argument is set?

It's no longer optional in 2.0.

**Comment by vishnukvmd** [comment]
> > The `title` is an optional argument to `saveImage` right now. We could override only if the argument is set?
> 
> It's no longer optional in 2.0.

Then we could override the title if the argument is non-null?

Or make sure that the passed argument is non-null and override always?

**Comment by AlexV525** [comment]
> Then we could override the title if the argument is non-null?
> 
> Or make sure that the passed argument is non-null and override always?
> 
> I prefer the second approach.

Sure, I'm trying to solve this with `title: data['title'] as String? ?? title`.
