### ISSUE TITLE
[Android] Android8, how to create new assetPath (or album directory)

### ISSUE THREAD

**Issue by takapiroid88** [fluttercandies/flutter_photo_manager#634]
in case Android11,
to create new album or direcry at /Picture working.
```
PhotoManager.editor.saveImageWithPath(path, relativePath: relativePath)
```

but Android8, 
not working above.

also,
PhotoManager.getAssetPathList could find root path album like this directory tree.(Android8)

system
|- Android
|- DCIM
|- Pictures
|- TARGET_ALBUM

but, PhotoManager cannot make album this layer.
same layer as TARGET_ALBUM, Pictures... , i want to create.

Is there a solution?

at lease, in Android8, make album or directory in Pictures.

**Comment by AlexV525** [comment]
You should create the folder first, using other plugins like `path_provider` to obtain the root path, then try to save images.
