### ISSUE TITLE
[BUG] saveVideo method doesn't save video in Android

### ISSUE THREAD

**Issue by nayanbabariya95** [fluttercandies/flutter_photo_manager#635]
**Describe the bug**
`await PhotoManager.editor.saveVideo(File(file.path))` is not working in Android
here my `file.path` comes from video that is captured by `camera` plugin
Working in iOS

*Description*
Above method returns object of `AssetEntity?` but in Android it returns `null` 

**Expected behavior**
Above method should work on also Android

**Flutter version**
2.2.3

**Smartphone**
 - Device: Asus Zenfone Max Pro M1
 - OS: Android 11

**Comment by AlexV525** [comment]
`title` is a required argument in the code at present. Closing as it'll be solved in the next major release.

**Comment by LeJulious** [comment]
You probably un-required `title` at some point since I just encountered the same exact issue as this user. Adding a title fixed my problem. Please either require `title` or add "title is required on Android" in the docstring of editor.saveVideo()

**Comment by AlexV525** [comment]
> You probably un-required `title` at some point since I just encountered the same exact issue as this user. Adding a title fixed my problem. Please either require `title` or add "title is required on Android" in the docstring of editor.saveVideo()

The file path is required when saving the video and the file extension will be using for the type recognition. Do you still running into the issue using v3.3.0?
