### ISSUE TITLE
[Feature Request] Add possibility to display video's first frame when retrieving their thumbnail

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#639]
**Describe the bug**
When retrieving assets and trying to display them using ```entity.thumbDataWithOption()```, if the ```AssetEntity``` named ```entity``` is a ```video```, the first frame is not displayed. 

**To Reproduce**

1. Run the sample code on a phone that has videos in its gallery.
2. See that the first frame is not displayed.

**Code sample :** 

```
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:photo_manager/photo_manager.dart';

void main() {
  runApp(const TestApp());
}

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  State<TestApp> createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  final List<AssetEntity> assetsList = [];

  bool granted = false;

  void loadAssets() async {
    granted = await PhotoManager.requestPermission();
    if (granted) {
      FilterOptionGroup option = FilterOptionGroup()
        ..addOrderOption(const OrderOption(
          type: OrderOptionType.createDate,
          asc: false,
        ));

      final albums = await PhotoManager.getAssetPathList(
          onlyAll: true, filterOption: option, type: RequestType.video);

      if (albums.isNotEmpty) {
        var album = albums.first;
        // Now that we got the album, fetch all the assets it contains
        List<AssetEntity> currentList = await album.getAssetListRange(start: 0, end: 200);
        // Update the state and notify UI
        assetsList.clear();
        assetsList.addAll(currentList);
      }
      setState(() {

      });
    }
  }

  @override
  void initState() {
    loadAssets();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: granted
              ? _gridView()
              : Center(
                child: Container(
                    color: Colors.blue,
                    width: 200,
                    height: 200,
                    child: TextButton(
                      onPressed: () async {
                        granted = await PhotoManager.requestPermission();
                        setState(() {});
                      },
                      child: const Text("Ask permission", style: TextStyle(color: Colors.white),),
                    )),
              )),
    );
  }

  Widget _gridView() {
    return GridView.builder(
      itemCount: assetsList.length,
        gridDelegate:
            const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
        itemBuilder: (context, index) {
          return GalleryThumbnail(asset: assetsList[index]);
        });
  }
}

class GalleryThumbnail extends StatelessWidget {
  final AssetEntity asset;

  const GalleryThumbnail({Key? key, required this.asset}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Uint8List?>(
      future: Platform.isIOS
          ? asset.thumbDataWithOption(
              ThumbOption.ios(
                  width: 500,
                  height: 500,
                  deliveryMode: DeliveryMode.opportunistic,
                  resizeMode: ResizeMode.fast,
                  resizeContentMode: ResizeContentMode.fit,
                  quality: 100
                  // resizeContentMode: ResizeContentMode.fill,
                  ),
            )
          : asset.thumbDataWithSize(250, 250),
      builder: (_, snapshot) {
        final bytes = snapshot.data;
        if (snapshot.hasError) {
          return Container();
        }
        // If we have no data
        if (bytes == null) return Container();
        // If there's data, display it as an image
        return Image.memory(bytes, fit: BoxFit.cover);
      },
    );
  }
}
```

**Expected behavior**
I would expect to see the first frame of the video when retrieving a ```thumbnail``` with option for the ```AssetEntity```.
If this is not a global behavior, maybe add a ```bool``` parameter which would allow the user to choose which frame to take.

**Flutter version**

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

**Smartphone (please complete the following information):**
 - Device: iPhone XS max, iPhone 7 plus, Android OPPO (10), iPhone 12 pro max
 - OS: ios 15, 14.7, android 10

**Comment by AlexV525** [comment]
Is this reproducible in our demo? AFAIK this should not be misfunctioned.

**Comment by Tom3652** [comment]
I don't really know why did you put "need use case" when i provided one with the sample code above :/

I have tried the demo and it's the same but this minimal reproductible code uses only APIs from the package and it doesn't display the first frame of videos.

Have you tried to run the sample code and see on your phone that your videos are not displaying correctly ? Screenshots will be less useful than seeing it on your real phone with the sample code above. 

I can however confirm that it shows asset such as the native gallery on IOS, it seems to be taking the middle frame of the video. I have tested on other applications such as Snapchat, Instagram, etc... It shows a middle frame as well like in the native gallery.
On Android, it also gives the middle frame for videos thumbnail (with your API), but Android's native gallery is showing the first frame of the video in their thumbnails. 

So i agree it should not be a "bug" since it gives the output such as the native gallery on IOS, but more a feature request. It would be nice to be able to display the first frame of videos when using the ```thumbDataWithOptions``` method.

Logs won't be helpful at all since it's only a visual issue.

**Comment by AlexV525** [comment]
IIRC the thumbnail of a video should be the first frame of itself. I'll check whether it's true and what else can it be.

**Comment by Tom3652** [comment]
hello @AlexV525, did you find some time to check this ?

**Comment by AlexV525** [comment]
> hello @AlexV525, did you find some time to check this ?

Sorry for the delay since I'm quite busy in preparing for the DevFest next month. I'll take look in the next month after these things are done.

**Comment by Tom3652** [comment]
No problem, good luck then 🥇

**Comment by AlexV525** [comment]
@Tom3652 Can you verify if the linked PR implemented this request on Android?

**Comment by AlexV525** [comment]
In my tests, most videos will have the first frame in their thumbnails, about 90%, on Android.

**Comment by AlexV525** [comment]
Oh, so `1` might be the correct answer instead of `0` in the request option.

**Comment by Tom3652** [comment]
Thanks for the PR !

Sorry i can't try it right now, but i saw what you have done and yes i was using ```Glide``` in another Android project and i was using 1 as ```frame``` parameter 👍 

On iOS there is no way to change it ? 
I saw in many apps (Snapchat, Instagram, Photos) that the preview is not the first frame for videos, so this is probably a native restriction...

**Comment by AlexV525** [comment]
> On iOS there is no way to change it?

Actually, I'm at home so I'll try with iOS tomorrow, just tweaking with Android before bed.

**Comment by Tom3652** [comment]
No problem haha thank you anyway. 
I will test it a bit later and tell you for Android, i am not home that's why i can't for now.

**Comment by AlexV525** [comment]
After a few investigations, it appears that `PHAsset` didn't include such things as `frame` when requesting for thumbnail, only `AVAsset` did. So I guess this can be only implemented on Android. I've abstracted the `frame` field for `ThumbOption`, which allows users to define.

**Comment by Tom3652** [comment]
Thank you for the update !
No problem for iOS as no apps seem to have it either.
