### ISSUE TITLE
[Feature] Get space/size of file as entity property

### ISSUE THREAD

**Issue by burcus** [fluttercandies/flutter_photo_manager#640]
**Is your feature request related to a problem? Please describe.**
When need to getting size of the file firstly we need to get entity file. And sometimes it returns null and also delay  occurs caused by await.

**Describe the solution you'd like**
Maybe we can access directly the space property of mentioned entity's file. (e.g entity.space or entity.storage)

**Comment by AlexV525** [comment]
Size/disk space is not a general abstraction on all platforms, especially when it involves sandbox, scoped storage, etc.

We can obtain the total size of an asset only when an actual I/O method is called.
