### ISSUE TITLE
call PhotoManager. requestPermissionExtend [BUG]

### ISSUE THREAD

**Issue by luokunman** [fluttercandies/flutter_photo_manager#643]
**Describe the bug**
PhotoManager a ios problem, the retrieval process: First installation application call PhotoManager. requestPermissionExtend, call photo permissions, select "choose photo", pop-up photo process in the system, do not cancel or complete, directly down, the second choice. Permission will not be applied again

**To Reproduce**
1. Go to call PhotoManager. requestPermissionExtend()
2. do not cancel or complete
3. pop-up photo process in the system
4. the second choice. Permission will not be applied again

**Expected behavior**
 the second choice. Permission will be applied again or Provide state

**Flutter version**

**Log**

```bash

1 print(123123);
2 PermissionState _ps = await PhotoManager.requestPermissionExtend();
3 print(_ps);
// The first line can be printed, can't get past the third line of code.
```

**Comment by AlexV525** [comment]
This is a known iOS bug when an app is first installed, call request access, select limited and pick nothing. Still waiting for the feedback from Apple.

**Comment by dodatw** [comment]
> This is a known iOS bug when an app is first installed, call request access, select limited and pick nothing. Still waiting for the feedback from Apple.

Is there any form talking about this issue? I face same issue now.

**Comment by AlexV525** [comment]
> Is there any form talking about this issue? I face same issue now.

The feedback should be private at this moment: https://feedbackassistant.apple.com/feedback/9759773

**Comment by AlexV525** [comment]
Closing as we are not likely to see it solved from Apple.
