### ISSUE TITLE
[BUG] RequestType never equal in AssetPathEntity

### ISSUE THREAD

**Issue by SixSheeppp** [fluttercandies/flutter_photo_manager#647]
`RequestType ` never equal in AssetPathEntity.

I found `AssetPathEntity` has overrided the == and equals method.
But it never be true in this line.
>https://github.com/fluttercandies/flutter_photo_manager/blob/b6885e31e64ea59032e20e029c840dfbd21e6533/lib/src/entity.dart#L158

I think `RequestType` should override the == and equals method.

Here is example
![image](https://user-images.githubusercontent.com/18064048/142575715-3efd468e-8003-487d-b117-3c7eda50bea7.png)

**Comment by AlexV525** [comment]
On which platform?

**Comment by SixSheeppp** [comment]
I test on Android yet.
But i dont think this is relatied to platform. `RequestType ` is defined in flutter and has the same value.
