### ISSUE TITLE
[BUG] requestPermissionExtend() does not work correctly with instabug_flutter

### ISSUE THREAD

**Issue by Artem2908** [fluttercandies/flutter_photo_manager#648]
**Describe the bug**
When using the flutter_photo_manager and instabug_flutter in project, requestPermissionExtend returns PermissionState.denied, but permission to access the media is granted. The getAssetPathList method does not return assets on android devices. If you remove instabug_flutter from pubspec.yaml, then photo_manager will return assets. At the same time, checking for media access via permission_handler returns the correct value (granted)

**Expected behavior**
PhotoManager.requestPermissionExtend() should return PermissionStatus.authorized.
PhotoManager.getAssetPathList(hasAll: false, type: type, filterOption: filterOptionGroup) should return the list of assets

**Screenshots**
A simple code sample:
<img src="https://user-images.githubusercontent.com/37964624/143292782-767ee9cf-7ee6-40aa-a612-d9efb78c966b.png" 
width="500">

Console log:
<img src="https://user-images.githubusercontent.com/37964624/143292931-279becee-c750-4b0c-a9ab-d37dcc4ea34e.png" width="500">

**Flutter version**
Channel stable, 2.5.3, on macOS 11.5.2 

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A9 2018, Samsung Galaxy s21]
 - OS: [Android 10, Android 11]

**Comment by AlexV525** [comment]
Why >=29 is `Permission.accessMediaLocation`?

**Comment by AlexV525** [comment]
Closing, as it seems to be invalid and no further information is provided.

**Comment by Artem2908** [comment]
@AlexV525 Sorry for the wait. Here is an example of a _main.dart_ file on which you can reproduce this bug on **Android**:

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:photo_manager/photo_manager.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(title: 'Demo', home: HomeScreen());
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  bool isLoading = false;
  String permissionStatus = '';
  List<AssetEntity> importedAssets = [];

  Future<void> importPhotos() async {
    final List<AssetEntity> assets = [];
    late final String mediaAccessStatus;

    final status = await PhotoManager.requestPermissionExtend();

    if (status == PermissionState.authorized ||
        status == PermissionState.limited) {
      mediaAccessStatus = 'Access granted';

      setState(() => isLoading = true);

      final List<AssetPathEntity> paths = await getAssetsPaths();
      await Future.wait(paths.map((mediaPath) async {
        if (mediaPath.assetCount > 0) {
          final mediaAssetsList = await mediaPath.assetList;
          assets.addAll(mediaAssetsList);
        }
      }).toList());
    } else {
      mediaAccessStatus = 'No access to photos';
    }
    setState(() {
      permissionStatus = mediaAccessStatus;
      importedAssets = assets;
      isLoading = false;
    });
  }

  Future<List<AssetPathEntity>> getAssetsPaths() async {
    if (Platform.isAndroid) {
      return await PhotoManager.getAssetPathList(hasAll: false);
    } else if (Platform.isIOS) {
      return await PhotoManager.getAssetPathList(hasAll: true, onlyAll: true);
    }
    return [];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Import test')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: <Widget>[
            TextButton(
              onPressed: importPhotos,
              child: const Text('Import photos'),
            ),
            if (isLoading)
              const CircularProgressIndicator()
            else
              Text('Imported assets count: ${importedAssets.length}'),
            Text(permissionStatus),
          ],
        ),
      ),
    );
  }
}

And the dependencies I use in _pubspec.yaml_:
photo_manager: ^1.3.0
instabug_flutter: ^10.9.1

First, build the app on Android device with  photos and without "instabug_flutter: ^10.9.1" dependence in pubspec.yaml. Tap on "Import" button and give permission to access the media. At the bottom, the assets counter should update and the media access should show as "granted".
Then add the "instabug_flutter: ^10.9.1" dependency to pubspec.yaml and rebuild the app. Tap on the "Import" button. The assets counter will show 0, and at the bottom it will say "No access to photos"
