### ISSUE TITLE
[BUG] Android getThumb works in Main thread

### ISSUE THREAD

**Issue by SixSheeppp** [fluttercandies/flutter_photo_manager#649]
Although `getThumb` has `runOnBackground` in `PhotoManagerPlugin`,
`Glide` call `onResourceReady` still work in Main thread.

After that , `resource.compress(format, quality, bos)` may  affect ui performance.

![image](https://user-images.githubusercontent.com/18064048/143396963-76993c7e-bc60-460b-b04b-ca93b1ae9930.png)

The Thread excutor is in main thread.
![image](https://user-images.githubusercontent.com/18064048/143398246-eff9684e-fd12-458f-a616-6636773c75b9.png)

BTW : `getThumbOfUri` may have the same issue, but i don't test yet :(

**Comment by bdlukaa** [comment]
I'm also experiencing this issue. I load a bunch of thumbs and it's taking a while to load, impacting mostly low-end devices

**Comment by AlexV525** [comment]
@SixSheeppp I'm not familiar with Glide overall, would `Executor.directExecutor()` help in this case?

**Comment by SixSheeppp** [comment]
> @SixSheeppp I'm not familiar with Glide overall, would `Executor.directExecutor()` help in this case?

`Executor.directExecutor()` work in this case. 
The PR which has been merged do the same thing. Thanks for the solutation ：）

**Comment by SixSheeppp** [comment]
> @SixSheeppp I'm not familiar with Glide overall, would `Executor.directExecutor()` help in this case?

`Executor.directExecutor()` work in this case. 
The PR which has been merged do the same thing. Thanks for the solutation ：）
