### ISSUE TITLE
[BUG] Failed to load live photos

### ISSUE THREAD

**Issue by jiabin87428** [fluttercandies/flutter_photo_manager#654]
**Describe the bug**
iOS真机13.6，从相册选择图片,预览照片时，如为实况照片，无法预览，显示“加载失败”

1、使用iOS13.6系统的苹果手机
2、AssetPicker.pickAssets(context, maxAssets: 10);
3、尝试在选择界面预览照片

**Expected behavior**
期望照片都可以正常预览

**Screenshots (If contains)**

**Version information**

- Device: iPhone 6s Plus
- OS: iOS13.6
- Package Version: 6.1.2
- Flutter Version: v2.5.2

**Comment by jarvan11** [comment]
> 

Android小米手机也有这个问题，产生的问题是代码通过图片路径删除了图片文件，没有通知媒体数据库更新，然后AssetPicker.pickAssets(context, maxAssets: 10);是通过数据库拿图片的，被删除的图片在数据库还有记录，但实际上该图片已经被删除了

**Comment by AlexV525** [comment]
Didn't repro this on the latest plugin. Please file new issues if it's still reproducible, and provide more cases.
