### ISSUE TITLE
[iOS] Sort difference between the default sort order and the system

### ISSUE THREAD

**Issue by zachchou** [fluttercandies/flutter_photo_manager#655]
最近项目的排序不是按照的照片本身的添加时间来排序，而且照片本身ext里面的创建时间来排序，导致从其他手机传过来之前的图片在最近项目这个path里面就会出现丢失的情况

**Comment by zachchou** [comment]
可以从其他iPhone设备隔空投送一张早些时候的照片到测试设备上，然后在测试设备用flutter_wechat_assets_picker选取照片在最近项目这张照片不是添加在最后，而是在这张照片本身的时间对应的位置，但是在手机相册最近项目是排在最后，这个可以改成按添加时间排序吗
![Snipaste_2021-12-15_17-18-18](https://user-images.githubusercontent.com/7876029/146159595-6a9a1cfb-d1e1-43e1-a782-9d7e8e581f72.png)

**Comment by zachchou** [comment]
可以从其他iPhone设备隔空投送一张早些时候的照片到测试设备上，然后在测试设备用flutter_wechat_assets_picker选取照片在最近项目这张照片不是添加在最后，而是在这张照片本身的时间对应的位置，但是在手机相册最近项目是排在最后，这个可以改成按添加时间排序吗
![Snipaste_2021-12-15_17-18-38](https://user-images.githubusercontent.com/7876029/146159711-2a4ba0e7-fccb-4502-ba76-9745289c83d2.png)
![Snipaste_2021-12-15_17-18-18](https://user-images.githubusercontent.com/7876029/146159726-bd9774ca-5582-44df-bdda-eb9ad4a7f0eb.png)

**Comment by AlexV525** [comment]
这个问题与 #620 相关，并且在 PR 中作出了完整的解释。

> 最近项目的排序不是按照的照片本身的添加时间来排序，而且照片本身ext里面的创建时间来排序

何以得此结论？

**Comment by zachchou** [comment]
> 这个问题与 #620 相关，并且在 PR 中作出了完整的解释。
> 
> > 最近项目的排序不是按照的照片本身的添加时间来排序，而且照片本身ext里面的创建时间来排序
> 
> 何以得此结论？

我刚刚隔空投送测试了，不能说图片丢失，就是排序不是按照添加时间来排序的，而是按照图片exif里面的时间来排序的，这个有办法修改成按照添加时间来排序吗

**Comment by AlexV525** [comment]
> 而是按照图片exif里面的时间来排序的

iOS 是根据 `NSSortDescriptor` 进行排序的，为什么说是 EXIF 内的时间？

**Comment by zachchou** [comment]
> 

        NSString *key = nil;
        if (typeValue == 0) {
            key = @"creationDate";
        } else if (typeValue == 1) {
            key = @"modificationDate";
        }
        
        if (key) {
            NSSortDescriptor *descriptor = [NSSortDescriptor sortDescriptorWithKey:key ascending:asc];
            if (descriptor) {
                [result addObject:descriptor];
            }
        }

就是这个creationDate是获取照片添加进手机相册的时间还是获取的是本身这个照片在创建的时间，我这边测试的话这个应该是本身这个照片创建的时间，所以导致在最后排序的时候出来的结果，如果有个别照片是从其他设备上传过来的 就会出现不是在最后而是在这张照片本身创建的时间对应的位置

**Comment by AlexV525** [comment]
#620 中已经有详细的解释了，其实所有图片都是按照创建时间来排列的，当你完全关闭相册应用 1 次或数次，又或是重启手机 1 次或数次后，图片就会回到以创建时间为排序的位置。你在相册中看到它被投送后显示在前面，是因为相册 App 在它的周期内保持了原本的相册顺序，额外处理了投送的内容，属于自己的特性或 BUG。但是：
- Plugin 是做不到的，因为你不能保证它像系统相册一样持续在后台；
- 排序规则没有错，在 #620 之前也尝试过 `burstIdentifier` 等一系列排序方案，最后只有 `creationDate` 是对的。

**Comment by zachchou** [comment]
> #620 中已经有详细的解释了，其实所有图片都是按照创建时间来排列的，当你完全关闭相册应用 1 次或数次，又或是重启手机 1 次或数次后，图片就会回到以创建时间为排序的位置。你在相册中看到它被投送后显示在前面，是因为相册 App 在它的周期内保持了原本的相册顺序，额外处理了投送的内容，属于自己的特性或 BUG。但是：
> 
> * Plugin 是做不到的，因为你不能保证它像系统相册一样持续在后台；
> * 排序规则没有错，在 [Improve sort orders on iOS #620](https://github.com/fluttercandies/flutter_photo_manager/pull/620) 之前也尝试过 `burstIdentifier` 等一系列排序方案，最后只有 `creationDate` 是对的。

排序规则是没有错，我的意思是有没有办法能做到和系统相册 微信飞书在最近项目里的排序是一样的都是新添加的在最后

**Comment by AlexV525** [comment]
cc @moyusword

**Comment by zachchou** [comment]
[PHAsset fetchAssetsInAssetCollection:collection options: nil]

**Comment by zachchou** [comment]
感谢大佬，我找到解决方案了，[PHAsset fetchAssetsInAssetCollection:collection options: nil]，用这个方法拿到的顺序和系统相册是一样的，不进行任何排序的设置，然后显示的时候直接滚动到底部完美解决
