### ISSUE TITLE
[BUG]  The Android 30 permission is denied When Android add WRITE_EXTERNAL_STORAGE maxSdkVersion is 29

### ISSUE THREAD

**Issue by dyy1993** [fluttercandies/flutter_photo_manager#665]
**Describe the bug**

The Android 11 permission is denied When Android add WRITE_EXTERNAL_STORAGE maxSdkVersion is 29. (User authorized)

**To Reproduce**
1. add   `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
               android:maxSdkVersion="29" />` in AndroidManifest.xml.
2. PermissionState is denied on 30 Android SDK (User authorized).

**Flutter version**
flutter 2.5.3

**Smartphone (please complete the following information):**
 - OS: [Android 11]

**Comment by dyy1993** [comment]
Google does not recommend using android.permission.WRITE_EXTERNAL_STORAGE in Android 11. [link](https://developer.android.google.cn/training/data-storage/use-cases?hl=zh-cn#show-all-files-media)

**Comment by AlexV525** [comment]
It didn't tell *NOT RECOMMEND* on the doc, but another behavior was provided instead.

When permission is only used on SDKs below 29, then it should be at the denied state on 29+, isn't it correct?

**Comment by dyy1993** [comment]
> It didn't tell _NOT RECOMMEND_ on the doc, but another behavior was provided instead.
> 
> When permission is only used on SDKs below 29, then it should be at the denied state on 29+, isn't it correct?

When setting <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" /> in other plugins, this plugin checkPermissions is false in 29+.
Please review this pr #666.

**Comment by dyy1993** [comment]
For example, other plugin add this.
![WX20211224-184601](https://user-images.githubusercontent.com/10572649/147346311-3f98789d-3a7a-489a-88a6-82ccaea79d97.png)
photo manage not working.
