### ISSUE TITLE
[BUG] Not Retrieving Edited Images on iOS

### ISSUE THREAD

**Issue by Huge-Puppy** [fluttercandies/flutter_photo_manager#680]
**Describe the bug**
New problem identical to #281 . Getting images that have been edited on iOS do not retrieve the edited image. Original image is retrieved instead. 

**To Reproduce**
1. On iOS, take a screenshot and save a cropped version.
2. Load it in your app through PhotoManager.

**Expected behavior**
PhotoManager should retrieve the edited image instead of the original.

**Flutter version**
2.8.0-3.3.pre • channel beta

**Smartphone (please complete the following information):**
 - Device: iPhone 6s Plus
 - OS: iOS 15.1

**Comment by AlexV525** [comment]
This was fixed by #663. Closing.
