### ISSUE TITLE
 Future<File?> get file => _getFile(); slowing iOS

### ISSUE THREAD

**Issue by statsss** [fluttercandies/flutter_photo_manager#688]
photo_manager: ^2.0.0-dev.2

 Future<File?> get file => _getFile(); 

on iOS 15.1 very slow, more than 3 seconds

I need to get the file path for further processing, but we know the selection for a very long time, is there something more optimal?

**Comment by AlexV525** [comment]
See https://github.com/fluttercandies/flutter_photo_manager/discussions/661#discussioncomment-1863526.
