### ISSUE TITLE
Future<File?> get file => _getFile() - never completed

### ISSUE THREAD

**Issue by statsss** [fluttercandies/flutter_photo_manager#691]
photo_manager: ^2.0.0-dev.3
 iOS 15.1

AssetEntity imageData (curren instas);
final Uint8List? bytes = await imageData.thumbDataWithOption(
          ThumbOption(height: height, width: width, quality: 1));
its ok
after call

 imageData.file.then((value) {
     //never completed,  no errors
      print(' ${value?.path}');
    });

what could be the problem?
thanks

**Comment by statsss** [comment]
I suspect any repeated request to the entity fails

**Comment by AlexV525** [comment]
See https://github.com/fluttercandies/flutter_photo_manager#long-retrieving-duration-with-file-on-ios.
