### ISSUE TITLE
[Custom]

### ISSUE THREAD

**Issue by aliaktas-tr** [fluttercandies/flutter_photo_manager#692]
How can I display all device images on page without folders?

**Comment by AlexV525** [comment]
Please run through the example before ask.

**Comment by aliaktas-tr** [comment]
Actually I did but  I couldn't figure out. Im new at coding.With getAssetListPaged I get images but need size,couldn't get all.  I need get all images and display. I can be glad if you can help me @AlexV525 .Thank you

**Comment by aliaktas-tr** [comment]
![Screenshot_20220121_182101_com example test_project](https://user-images.githubusercontent.com/51866588/150552988-111198f3-1b93-4b9b-a708-fcab9f499c16.jpg)

I'm using images in bottom sheet. Just dont want with display with folders.I want to correctly display all images
