### ISSUE TITLE
[Question] Loading videos with ```getMediaUrl``` result sometimes in black video but with audio playing.

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#694]
## Expect

Load the video through ```getMediaUrl()```.   
Sometimes i am getting a black video with the audio playing alone when using ```entity.getMediaUrl```.  
In the logs, there is also this error : 

```
Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)"
[PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x28149acd0> accessor:<<PAApplication 0x283917980 identifierType:auditToken identifier:{pid:1986, version:5600}>> identifier:FC035C4E-E0B5-4326-9CF4-7841CA51EC91 kind:intervalEnd timestampAdjustment:0 tccService:kTCCServicePhotos, error=Error Domain=PAErrorDomain Code=10 "Possibly incomplete access interval automatically ended by daemon"
```

I have checked this error on the net and it's related to the Photo API [as mentioned here](https://stackoverflow.com/questions/57803075/get-an-error-when-trying-to-get-all-the-photos-from-phassetcollection-fetchasset)

Not sure that this is related but when i have this log, i also have the black video with only audio playing.

Do you know what can be causing this or how to fix this ?   
Thanks !

**Comment by AlexV525** [comment]
Check `video_player` first.

**Comment by Tom3652** [comment]
Thanks for the reply.

Actually you are right again, i have tried with the ```image_picker``` and i also have a black rendered video while audio is playing. 
It's probably related to [#62785](https://github.com/flutter/flutter/issues/62785) in the flutter repo. 

I have learned the lesson with ```video_player``` now :)
