### ISSUE TITLE
[BUG] com.apple.root.default-qos

### ISSUE THREAD

**Issue by LeeJunYoung-2823** [fluttercandies/flutter_photo_manager#695]
**Describe the bug**
There is a phenomenon that the phone is abnormally terminated when loading the gallery in ios.
It works fine on Android, but only gives the error on iOS.
Maybe it has something to do with the cache?

**To Reproduce**
I tested it and it doesn't play, but there are users who say that this happens when loading a gallery or loading a photo.
When I asked the user, all photo access rights were allowed.

**Expected behavior**

```dart
  Future<void> refreshGalleryList() async {
    var imageList =
        await PhotoManager.getAssetPathList(type: RequestType.image);

    imageList.sort((s1, s2) => s2.assetCount.compareTo(s1.assetCount));
    list.clear();
    list.addAll(imageList);
    notifyListeners();
  }
```

It seems that the method is throwing an error

**Screenshots**
![캡처](https://user-images.githubusercontent.com/59245557/151274096-7ef2e245-07f9-4557-a3f0-fbccb1ebbd0a.PNG)
<img width="698" alt="스크린샷 2022-01-27 오전 10 34 54" src="https://user-images.githubusercontent.com/59245557/151275590-1f2f22cb-e93b-4de8-926f-8dc12309e81c.png">

**Flutter version**
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
    • Flutter version 2.2.1 at /Users/bae-kyungpark/Developer/flutter
    • Framework revision 02c026b03c (8 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bae-kyungpark/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 830E378C-752E-4710-941D-E7D8CEF7DF45 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 91.0.4472.77

photo_manager: ^1.3.10

**Smartphone (please complete the following information):**
 IOS 15.2.1 or IOS 14
 iphone 12, 13, xs ....

**Log**

Crashed: com.apple.root.default-qos
0  CoreFoundation                 0x6adc0 mdict_rehashd + 160
1  CoreFoundation                 0x2c7f4 -[__NSDictionaryM setObject:forKeyedSubscript:] + 836
2  photo_manager                  0x5d90 -[PMCacheContainer putAssetEntity:] + 23 (PMCacheContainer.m:23)
3  photo_manager                  0x971c -[PMManager getAssetEntityListWithGalleryId:type:page:pageCount:filterOption:] + 235 (PMManager.m:235)
4  photo_manager                  0x13044 __26-[PMPlugin onAuth:result:]_block_invoke + 264 (PMPlugin.m:264)
5  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
7  libdispatch.dylib              0x7798 _dispatch_queue_override_invoke + 792
8  libdispatch.dylib              0x15de0 _dispatch_root_queue_drain + 396
9  libdispatch.dylib              0x16608 _dispatch_worker_thread2 + 164
10 libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
11 libsystem_pthread.dylib        0xe94 start_wqthread + 8

```bash

```

**Comment by AlexV525** [comment]
Can you verify whether the latest commit can reproduce this issue?

**Comment by CaiJingLong** [comment]
Hi, your example code is just have get `List<AssetPathEntity>`, I think you need provide other code(such as: get assetList of AssetPathEntity) to reproduce your issue.

**Comment by LeeJunYoung-2823** [comment]
> Hi, your example code is just have get `List<AssetPathEntity>`, I think you need provide other code(such as: get assetList of AssetPathEntity) to reproduce your issue.

![image](https://user-images.githubusercontent.com/59245557/151517030-7dd49412-d839-4402-951f-01ab43c87ba6.png)

I have code to get gallery thumbnails.

**Comment by LeeJunYoung-2823** [comment]
> 최신 커밋이 이 문제를 재현할 수 있는지 확인할 수 있습니까?

**Comment by AlexV525** [comment]
Regarding the usage of your code, you should avoid to use the `FutureBuilder` since it'll be called to update once `markNeedsBuild` happened, instead you can cache them as a `Map` to avoid duplicate requests.

**Comment by LeeJunYoung-2823** [comment]
> Regarding the usage of your code, you should avoid to use the `FutureBuilder` since it'll be called to update once `markNeedsBuild` happened, instead you can cache them as a `Map` to avoid duplicate requests.

As you said, I've modified the FutureBuilder in a way that doesn't use it and deployed it to users.
If the same problem occurs again, reopen this problem. thank you.
