### ISSUE TITLE
[Question] Unit testing for Photo Manager

### ISSUE THREAD

**Issue by iTEEECH** [fluttercandies/flutter_photo_manager#702]
## Expect
Hi Everyone, I would like to know how I can to mock the dependency un order to test the methods please. Because I can't mock Photo_manager because it doesn't have any constructor. 

So do you have any solution or is it possible to add an empty constructor ?

Thanks.

**Comment by AlexV525** [comment]
Are looking for something like this? https://github.com/jpush/jpush-flutter-plugin/blob/8db7887c201f7359598c1a546cbb5f23146f76a6/lib/jpush_flutter.dart#L17

What's your purpose for the mock and what kind of code you intend to write?

**Comment by iTEEECH** [comment]
No I didn't know that, I'll have a look. Thanks. 

I was planning to mock with Mocktail by returning a list of objects from this method PhotoManager.getAssetPathList();
