### ISSUE TITLE
[BUG] Requesting multiple AssetPathEntites at the same time is very slow on iOS

### ISSUE THREAD

**Issue by timcreatedit** [fluttercandies/flutter_photo_manager#711]
**Describe the bug**
For our app, we need to display a calendar that marks each day that has a video in the devices gallery.

Therefore, we request an AssetPathEntity for each widget like this:
```dart
final albums = await PhotoManager.getAssetPathList(
      type: RequestType.video,
      hasAll: true,
      filterOption: FilterOptionGroup(
        containsLivePhotos: false,
        orders: const [
          OrderOption(type: OrderOptionType.createDate, asc: false)
        ],
        createTimeCond: DateTimeCond(
          min: date.startOfDay(),
          max: date.endOfDay(),
        ),
        videoOption: FilterOption(
          durationConstraint: DurationConstraint(
            min: minDuration,
          ),
        ),
      ),
    );
    return albums.firstWhereOrNull((album) => album.isAll);
```

Using FutureBuilders for the widgets works like a charm on Android, on iOS however, this process is extremely slow.
Requests for about 20 days simultaneously takes about 40 seconds, then all the Futures complete at the same time. Requesting each day sequentially still takes about 2-3 seconds per day.

On Android, all requests complete virtually instantly, even when requesting AssetPathEntities for a lot of days at the same time.

**Expected behavior**
Similar speeds on iOS and Android.

**Flutter version**
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
    • Flutter version 2.10.1 at /Users/tim/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

**Smartphone (please complete the following information):**
- Device: iPhone 13, iPhone 8 (physical devices)
- iOS 15.3.1
- Version ^1.3.10 (also reproducible in 2.0.0--dev.11)

**Comment by AlexV525** [comment]
Any screen recordings?

**Comment by AlexV525** [comment]
Also, no matter how fast the plugin on Android, your implementation seems to be strange...

**Comment by AlexV525** [comment]
A more reasonable implementation would be:
- Define a `Map<DateTime, int>` for assets count
- Load the `isAll` path only once
- Load assets with paginations of the calendar, then increase the count of each day.

Meanwhile, I'll try to figure out if any latency we can improve.

**Comment by AlexV525** [comment]
```
Performing hot reload...
Syncing files to device Alex’s iPhone...
Reloaded 1 of 899 libraries in 378ms.
collection name = Panoramas, count = 0
collection name = Videos, count = 3
collection name = Favorites, count = 0
collection name = Time-lapse, count = 0
collection name = Hidden, count = 1
collection name = Recently Deleted, count = 3
collection name = Recents, count = 3
collection name = Bursts, count = 0
collection name = Slo-mo, count = 1
collection name = Recently Added, count = 3
collection name = Selfies, count = 3
collection name = Screenshots, count = 3
collection name = Portrait, count = 3
collection name = Live Photos, count = 3
collection name = Animated, count = 0
collection name = Long Exposure, count = 0
collection name = Unable to Upload, count = 0
collection name = RAW, count = 0
collection name = 抖音, count = 2
collection name = 微博, count = 1
collection name = QQ, count = 1
[PhotoManager 📣] 2022-02-22T11:44:13.860127 - Obtain path list duration: 0:00:00.121575
```

**Comment by timcreatedit** [comment]
>  A more reasonable implementation would be:
> 
> Define a Map<DateTime, int> for assets count
> Load the isAll path only once
> Load assets with paginations of the calendar, then increase the count of each day.

On Android, this is is actually less sensible, since at that stage we only care whether there are any assets at all that match the given filter criteria, so we want to use the assetCount getter, which is synchronous once you obtained the AssetPathEntity.

**Comment by AlexV525** [comment]
Can you run the latest example and filter logs by `PhotoManager 📣`?

**Comment by AlexV525** [comment]
Another option is to explicitly mark `containsModified` to false to see if it makes any differences.

**Comment by AlexV525** [comment]
Closing, as we don't have a valid further response about the fix.
