### ISSUE TITLE
PhotoManager getAssetList maybe cause ClassCastException

### ISSUE THREAD

**Issue by ZanderZhan** [fluttercandies/flutter_photo_manager#721]
**Describe the bug**
firebase throw a ClassCastException on PhotoManager getAssetList.  Query method should wrap with try catch statement.
```
Fatal Exception: java.lang.ClassCastException
java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
```

**To Reproduce**
1. 非必现，firebase 上收集到的。

**Expected behavior**
在获取图片的时候，有机率会出现这个错误。怀疑可能是并发导致的查询出错。

**Screenshots**
no screenshots.

**Flutter version**
flutter 2.8.1

**Smartphone (please complete the following information):**
 - Device: Redmi S2、vivo 1816 等
 - OS: Android 
 - Browser
 - Version Android 8、9、10

**Log**

If applicable, add logs to help explain your problem.

```bash

```

**Comment by AlexV525** [comment]
Please fill up all required info before we can take further investigations.

**Comment by ZanderZhan** [comment]
> Please fill up all required info before we can take further investigations.

重新编辑了

**Comment by AlexV525** [comment]
Still missing detailed info for investigations, e.g. full logs, stack traces, etc.

**Comment by ZanderZhan** [comment]
> Still missing detailed info for investigations, e.g. full logs, stack traces, etc.

混淆的文件路径，贴上来也没有意义

**Comment by ZanderZhan** [comment]
> Still missing detailed info for investigations, e.g. full logs, stack traces, etc.

可以删除这个 issue 了。
