### ISSUE TITLE
[BUG] [iOS] getMediaUrl some times returns error "Could not cache the video file."

### ISSUE THREAD

**Issue by hazzo** [fluttercandies/flutter_photo_manager#724]
**Describe the bug**
The method `getMediaUrl` in last version is not working after updating to 2.0. Most of the times I receive an error that file could not be cached, so I added a `NLog` in the plugin to get the full iOS error, which is the following: 

```bash
open on /private/var/mobile/Containers/Data/Application/SOME-UID/tmp/.video/1646541163.430584_IMG_1798.MP4: File exists
error = Error Domain=NSCocoaErrorDomain Code=516 "“IMG_1798.MP4” couldn’t be copied to “.video” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/var/mobile/Media/DCIM/111APPLE/IMG_1798.MP4, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/private/var/mobile/Containers/Data/Application/SOME-UID/tmp/.video/1646541163.430584_IMG_1798.MP4, NSFilePath=/var/mobile/Media/DCIM/111APPLE/IMG_1798.MP4, NSUnderlyingError=0x283ae52f0 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
```
**To Reproduce**
1. Get AssetEntity of video.
2. Call method `getMediaUrl`

**Expected behavior**
Should get file url even if file is already cached.

**Flutter version**
Flutter version 2.8.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 15.3.1

**Comment by hazzo** [comment]
I'm gonna close this because there was a bug in my code in which I was calling twice the method `getMediaUrl` and the plugin was trying to cache the file twice. Even though this is a bug in my side, shouldn't the plugin instead of throwing exception return the path because the video is already cached?

**Comment by AlexV525** [comment]
From your description, this will introduce a race-condition in creating files. A first check whether the file exists, then start to produce the media. B start checking while A is processing, which means the file is not yet produced. And after B is done, A is usually done already. It can be improved, but not in a high priority, and can be avoid by the correct usage, or a cancelable mechanism.
