### ISSUE TITLE
[BUG] Images saved by the plugin have wrong orientation

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/flutter_photo_manager#726]
**Describe the bug**
拍摄照片分辨率错误

**How to reproduce**
在oppo手机上，拍摄照片后返回的的宽高不正确，一张1080x1920的图片返回1920x1080，我怀疑在oppo上获取手机角度出现问题。

**Screenshots (If contains)**
![221646987119_ pic](https://user-images.githubusercontent.com/18067025/157830879-c2b52fbb-f645-4273-a673-0d52d66fd018.jpg)
![211646987118_ pic](https://user-images.githubusercontent.com/18067025/157830908-930852f6-6214-40da-a7b4-02910df5f5aa.jpg)

**Version information**

- Device: [e.g. OPPO K9s]
- OS: [e.g. ColorOS V11.2(Android 11)]
- Package Version: [e.g. 2.6.5]
- Flutter Version: [e.g. v2.8.1]

**Comment by AlexV525** [comment]
尝试：

```yaml
dependency_overrides:
  photo_manager:
    git:
      url: https://github.com/fluttercandies/flutter_photo_manager
      ref: '8004fbb'
