### ISSUE TITLE
[BUG]GPS from exif is missing

### ISSUE THREAD

**Issue by KevinChang-NC** [fluttercandies/flutter_photo_manager#737]
**Describe the bug**
when 1.3.10 update to 2.0.4,the gps from exif is missing in Android.

**To Reproduce**
Get originFile and read exif,then return
key: GPS GPSLatitudeRef, value:
key: GPS GPSLatitude, value: [0/0, 0/0, 0/0]
key: GPS GPSLongitudeRef, value:
key: GPS GPSLongitude, value: [0/0, 0/0, 0/0]

**Expected behavior**
should get correct lat and long

**Flutter version**
Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hant-TW)

**Smartphone (please complete the following information):**
 - Device: pixel 4XL
 - OS: Android 11

**Comment by AlexV525** [comment]
Did your apps grant with `ACCESS_MEDIA_LOCATION`?

**Comment by KevinChang-NC** [comment]
Thanks a lot,it's my mistake to skip the limitations.

**Comment by HenrikH96** [comment]
Hey there, 
I have granted ```	<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION " /> ```
but my exif data for GPS still says [0/0, 0/0, 0/0] 
I use the exif: ^3.3.0 Package in my app to extract the data. 
I request permission with ```    PermissionState permisson = await PhotoManager.requestPermissionExtend();``` 
anything i am doing wrong ?
