### ISSUE TITLE
[BUG] Unable to access specified image title after saving it to the gallery

### ISSUE THREAD

**Issue by PhoenixPhighter** [fluttercandies/flutter_photo_manager#739]
**Describe the bug**
I have a project where in one Dart file, I am saving a network image to the iOS gallery with a specified title (in my case, a hashcode). In another Dart file, I need to access that title that I specified, but widget.asset.title and widget.asset.titleAsync are not returning the title I set. Let's say when I am saving the network image, I set the title to be "55775351". In another screen, which displays asset entities from the iOS gallery, when I return the title, I get something like "IMG_3430" instead of the title I specified.

**To Reproduce**

1. Save a network image with a specific title.
final AssetEntity? entity = await PhotoManager.editor.saveImage(rawData, title: hashString + ".png");

2. Print the ID of this AssetEntity and you will see that it is not the specified title, even though in the camera roll you can see the title you specified.
String s = await entity.titleAsync;
print(s);

**Expected behavior**
Returning the Asset title should give the string you specified when you saved it. If you look in the iOS device gallery (since iOS now lets you swipe up and see metadata), you can see that the title you specified is being saved. But, if you try to retrieve that title, it outputs something different.

**Screenshots**
https://imgur.com/a/LAoryLe 
In the screenshot from my iOS camera gallery, you can see that the title is 55775351, but when I fetch the title for this asset, it returns "IMG_3430" (this title follows sequentially from previous photos, so internally iOS is somehow rewriting it I guess - still, the title that I set displays, so should I not be able to access it?)

**Flutter version**
Flutter Version 2.10.3

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: 15.3
 - Browser: Doesn't matter here, but Firefox

I should note, I read a similar issue where someone was having a similar problem, where they set a path but the newly created AssetEntity had an empty title - basically, the title they set was not being written in. This issue was marked as CLOSED but I could not find any solution in that thread. If you can, instead of just linking that issue since I already read it, could you please explain how to fix this? Thank you.

**Comment by CaiJingLong** [comment]
The title will be use in next code:

https://github.com/fluttercandies/flutter_photo_manager/blob/a8c193ed320bed5e833fcb7a93998e1652f9fec8/ios/Classes/core/PMManager.m#L1006

[The apple document](https://developer.apple.com/documentation/photokit/phassetresourcecreationoptions/1622683-originalfilename?language=objc)

Description in the official document: this field is the original name of the resource.

**Comment by PhoenixPhighter** [comment]
Thanks for the quick response.

I am having a little trouble understanding though. Does this mean it is impossible to access the title I set because Apple is overwriting it? If so, why can I see the title I set in the iOS camera gallery?

Basically, I am just wondering if someone can give me a clear-cut way to access the title I set since I am able to view it in the camera gallery.

Thank you for your help!

**Comment by CaiJingLong** [comment]
I know why this happened.

https://github.com/fluttercandies/flutter_photo_manager/blob/a8c193ed320bed5e833fcb7a93998e1652f9fec8/ios/Classes/core/PHAsset%2BPM_COMMON.m#L71-L96</details>

I get the title of iOS asset with kvo, the method is fast.
The `originalFilename` can only be obtained through `PHAssetResource`, which is very slow. 

If you need to obtain `originalFilename` in batch, the performance may not be satisfactory.

**Comment by PhoenixPhighter** [comment]
Clarification - originalFilename is what I set, right? So if I want to access the hashcode I have embedded in the title field, I will need to use PHAssetResource?

**Comment by CaiJingLong** [comment]
Now that it's not provided, we should modify the `titleAsync` property to provide the `originalFileName`.

**Comment by PhoenixPhighter** [comment]
Perfect, this seems like it should work - I'll look into this tomorrow and let you know. Thank you so much for all this help!

**Comment by AlexV525** [comment]
There are a couple of cases that get involved after the PR lands:
- With a photo that you just saved, the getter should return the exact title as you used to save it.
- With a photo that's edited, e.g. cropped, applied with filters, the method will try to find the edited resource, and return its `originalFilename`, and it could be different from your title.
- With a Live Photo, the getter will return according to the subtype you requested (`titleAsync` or `titleAsyncWithSubtype`). It can return the `originalFilename` of the resource, or the `originalFilename` of the paired resource.

**Comment by AlexV525** [comment]
If an accurate title is not frankly necessary in your case, `title` is still preferred.
