### ISSUE TITLE
[BUG] Xcode 13.3 flutter 2.10.3 build failed

### ISSUE THREAD

**Issue by xiaomaiTD** [fluttercandies/flutter_photo_manager#742]
<img width="1065" alt="434FCB10-7812-45A2-858C-24AF92BA5D92" src="https://user-images.githubusercontent.com/18552341/160090363-f8481102-4aa5-421d-90b6-5a51f8487779.png">

![B37897D9-0B61-4C69-AD90-04A3EEECBE38](https://user-images.githubusercontent.com/18552341/160089409-f60cb91d-a579-4a0a-8b71-844b61eb1ae0.png)

**Flutter version**
2.10.3 (macOS 12.2.1)
**Dart version**
2.16.1

**Comment by AlexV525** [comment]
Is this reproducible with the example?

**Comment by CaiJingLong** [comment]
It may be because of Xcode project configuration that `PMLogUtils.h` is not referenced.
I think we can be modified if necessary the reference method of `.h` file with quote.

**Comment by CaiJingLong** [comment]
@xiaomaiTD 
You can try to use a9a73d9.
