### ISSUE TITLE
[BUG] save image and get an exception on android 11 or above

### ISSUE THREAD

**Issue by EricShe** [fluttercandies/flutter_photo_manager#747]
**Describe the bug**
Hi community 
i try to download and save an image to album, and the library return and Error to me . 

code: 
Future<AssetEntity?> _saveToAlbum(String filePath) async {
    try {
      MyLogger.debug('save image to album');
      final title = 'img_${DateTime.now().toUtc().millisecondsSinceEpoch}';
      AssetEntity? ae =  await PhotoManager.editor.saveImageWithPath(path, title: title);
      return ae;
    } on Exception catch (e){
      MyLogger.debug("save to album Exception");
      MyLogger.error(e);
      return null;
    }
}

exception : 
⛔ PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)

My build config setting is target to android 11 and up ( Api level 30 )

   defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mypackage"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

**To Reproduce**
1. setup a project with target api 31 and up
2. call method await PhotoManager.editor.saveImageWithPath(path, title: title) | PhotoManager.editor.saveImage(rawData, title: title);
3. you will see the exception

**Expected behavior**
save image success .

**Flutter version**

**Smartphone (please complete the following information):**
 - Device:  android Q emulator / redmi 9a 
 - OS: Android 10 
 - Browser n/a
 - Version n/a

**Log**

⛔ PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)

**Comment by AlexV525** [comment]
The exception has already told you that you're missing the `requestLegacyExternalStorage`,

**Comment by EricShe** [comment]
PS: not only write read also facing to the save issue 

when i call final result = await PhotoManager.requestPermissionExtend();


E/flutter (11971): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)
E/flutter (11971): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (11971): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (11971): <asynchronous suspension>
E/flutter (11971): #2      PhotoManagerPlugin.requestPermissionExtend (package:photo_manager/src/internal/plugin.dart:68:24)
E/flutter (11971): <asynchronous suspension>

**Comment by EricShe** [comment]
i have add theis flag to androidmanifest , i have check that androi 11 will be ignore this flag 

       <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:requestLegacyExternalStorage="true"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">

**Comment by AlexV525** [comment]
You're adding this to the wrong position. See the example for how to update the manifest.

**Comment by EricShe** [comment]
Grate! you help me to solve a big issue, i am study this for few days. thanks bros!
