### ISSUE TITLE
PhotoManager.getAssetPathList takes too much time with iCloud

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/flutter_photo_manager#750]
PhotoManager.getAssetPathList performance seems fixed with local file fetch but not in iCloud, anyone facing this issue?

I got 2T volume iCloud and has around 60000up photos in many folder/album

I tried PhotoManager.getAssetPathList(type: RequestType.image, onlyAll: true), costed my about 4secs, i can deal with that, but what i use PhotoManager.getAssetPathList(type: RequestType.image) to get all album, it costed me about 2mins to return the result

_Originally posted by @dvlj in https://github.com/fluttercandies/flutter_photo_manager/issues/178#issuecomment-1097483990_

**Comment by dvlj** [comment]
@AlexV525 Thanks for the issue opening, i was just wondering at the moment wether anyone facing this issue.

**Comment by AlexV525** [comment]
@dvlj In this case, we might require to access you iCloud account in order to debug the root cause. But before that, can you share any logs that presented a long retreiving duration?

**Comment by dvlj** [comment]
@AlexV525 Actually this is from my customer, although i don't have the environment to test for, but it's really happening, i will see what i can do. Thanks in advanced!

**Comment by CaiJingLong** [comment]
I guess the problem come from request iCloud asset.

So, we need provider option to allow network assets? @AlexV525

**Comment by AlexV525** [comment]
For now, I can only find that `obtainAssetCount` might affect the retrieving duration during the path obtained:
https://github.com/fluttercandies/flutter_photo_manager/blob/8e89d53cae7926f4fa9e5501d489bb2785b2ade1/ios/Classes/core/PHAssetCollection%2BPM_COMMON.m#L12-L17

**Comment by Kal-Elx** [comment]
> @AlexV525 Thanks for the issue opening, i was just wondering at the moment wether anyone facing this issue.

I've had multiple customers reporting this too so it would be amazing if there was a solution.

**Comment by jron42** [comment]
Still no solutions on any of this?

I believe I am having this issue as well..  I had a user with 70,000+ photos on iCloud and another with 36,000+ and both have very slow asset listings. This seems to be aggravated when using filter options..

is there a way to exclude iCloud images? Is there a way to make PhotoManager.getAssetPathList() examine only a SINGLE album instead of processing ALL of them?

**Comment by AlexV525** [comment]
We intend to introduce a breaking change that does not count the `assetCount` for an `AssetPathEntity` when constructing it. Instead, make it an asynchronized getter `assetCountAsync` or something. Ideally, this should significantly reduce the duration cost when obtaining the path list.

**Comment by delfme** [comment]
Hi @AlexV525, why is assetCountAsync so expensive? I always assumed that both iOS and Android keep track of asset counts per album, so there wouldn’t be a need to count them manually. However, I’ve noticed that assetCountAsync can take several seconds for albums with thousands of media files. Is it iterating through them one by one? Could you clarify how it works?
