### ISSUE TITLE
get width and height for imageView [Feature]

### ISSUE THREAD

**Issue by MohsenHaydari** [fluttercandies/flutter_photo_manager#751]
how I can get the image width and height for view?
I worked on uploading and downloading images when the user picks an image I get the wrong width and height from the server and your plugin,
For example, the height and width are displaced, and I have to use another method to get the width and height that affects the performance of the program

```
final _data = await entity.thumbnailDataWithOption(
        _thumbOption(ThumbnailSize(size!.width, size.height)));
var decodedImage = await decodeImageFromList(_data!);

```
```entity.size``` or ```orientatedSize ``` give me a displaced result with ```decodeImageFromList``` method in flutter In some images
I know this is not a problem with your plugin, but you can add this feature to your plugin

**Comment by AlexV525** [comment]
Not sure what you're talking about.

**Comment by AlexV525** [comment]
Closing as the issue is missing requirements and no response.
