### ISSUE TITLE
Feature: Add support for RAW/DNG images and flags

### ISSUE THREAD

**Issue by dev4jam** [fluttercandies/flutter_photo_manager#753]
It is possible to shoot RAW/DNG images on iOS and Android for a long time. 

Could you add support for this feature as well? 

Desired behavior: 

1. Flag in AssetEntity.
2. Method to get RAW data if it differs from AssetEntity originBytes method.

**Comment by AlexV525** [comment]
> Flag in AssetEntity.

I didn't see any necessity with a RAW field.

> Method to get RAW data if it differs from AssetEntity originBytes method

Have you encountered any issues when obtaining the raw data of RAW images when using `originBytes`?

**Comment by AlexV525** [comment]
Closing as the issue is missing requirements and no response.
