### ISSUE TITLE
[BUG] Android: `getTitleAsync` not implemented

### ISSUE THREAD

**Issue by johannessachse** [fluttercandies/flutter_photo_manager#754]
The method `getTitleAsync` is not implemented on Android. Therefore I get the error message `Null check operator used on a null value`.

File: photo_manager-2.0.7/lib/src/internal/plugin.dart (l. 335-353)
```
  Future<String> getTitleAsync(
    AssetEntity entity, {
    int subtype = 0,
  }) async {
    assert(Platform.isAndroid || Platform.isIOS || Platform.isMacOS);
    if (Platform.isAndroid) {
      return entity.title!;
    }
    [...]
  }
```

**Comment by AlexV525** [comment]
> The method `getTitleAsync` is not implemented on Android.

I didn't see any unimplemented info here, instead, it's an NPE issue.

**Comment by AlexV525** [comment]
Please provide the full `AssetEntity` you're calling with `getTitleAsync`.

**Comment by johannessachse** [comment]
The `AssetEntity` was correct. But I used the `AssetEntityImageProvider` with a recreated `AssetEntity` (without a `title`) afterwards. Therefore i got this error message.

Thank you for your support.
