### ISSUE TITLE
in ios image is repeating rtandomly 

### ISSUE THREAD

**Issue by vartikaantino** [fluttercandies/flutter_photo_manager#756]
Future<List<AssetEntity>> fetchAssets({required int presentPage}) async {
    lastPage.value = currentPage.value;
    foldersAvailable.value = await PhotoManager.getAssetPathList(onlyAll: true);

    var assetList = <AssetEntity>[];
    assetList =
        await foldersAvailable[0].getAssetListPaged(currentPage.value, 100);

    

    return assetList;
  }

 assets.value = await foldersAvailable.value[selectedFolder.value]
        .getAssetListPaged(currentPage.value, 100);

**Comment by vartikaantino** [comment]
I am using this piece of code but repeated image is coming without any stack trace

**Comment by AlexV525** [comment]
The screenshot doesn't provide any useful infomations. Please verify if it's reproducible using the example of this plugin.

**Comment by AlexV525** [comment]
Closing as the issue is missing requirements and no response.
