### ISSUE TITLE
upadate new image

### ISSUE THREAD

**Issue by TheBeginer2002** [fluttercandies/flutter_photo_manager#757]
did the function _loadMoreAsset use to update the image? When I call this function it doesn't update new images when I put the app to sleep. Any solution
![Screenshot 2022-05-05 120359](https://user-images.githubusercontent.com/70203679/167057930-b6b51a98-1388-439c-b08f-8e278a3bdeaf.png)

**Comment by AlexV525** [comment]
Closing as the issue is missing requirements and no response.
