### ISSUE TITLE
[BUG] 缩略图加载失败

### ISSUE THREAD

**Issue by zhangshuqi** [fluttercandies/flutter_photo_manager#763]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15172679/168253216-cf37854e-a63f-4c9a-81f2-d72d113d2c7e.png)

**Version information**

- Device: XIAOMI MIX 2S
- OS: ANDROID 11
- Package Version: 7.3.0
- Flutter Version: 2.10.0

**Additional context**

**Comment by AlexV525** [comment]
cc @CaiJingLong

**Comment by AlexV525** [comment]
Offline discussed with @MeandNi, who's voting for further investigations.

**Comment by MeandNi** [comment]
@zhangshuqi 没复现这个 bug，这边在文件管理器删除图片之后，进 demo 选择之后被删除的图片就不在了。

存在的 GlideException 应该是 com.android.fileexplorer 抛出的。

**Comment by zhangshuqi** [comment]
> @zhangshuqi 没复现这个 bug，这边在文件管理器删除图片之后，进 demo 选择之后被删除的图片就不在了。
> 
> 存在的 GlideException 应该是 com.android.fileexplorer 抛出的。

小米手机系统的问题

**Comment by AlexV525** [comment]
> 小米手机系统的问题

请提供录屏。

**Comment by zhangshuqi** [comment]
> > 手机小米系统的问题
> 
> 请提供录屏。

我重新复现了一下该bug 我用文字记录一下复现流程
1.使用相机拍摄照片
2.前往文件管理器删除该图片,图片选择器中报错加载失败

https://user-images.githubusercontent.com/15172679/179443488-318a4ba4-96cb-45c6-85f3-76118d77df48.mp4

**Comment by zhangshuqi** [comment]
> > 手机小米系统的问题
> 
> 请提供录屏。

我重新复查了一下  步骤如下
1. 使用摄像头拍摄照片
2. 前往文件管理器删除该图片，图片选择器中报错加载失败

视频

https://user-images.githubusercontent.com/15172679/179443555-cdf02cc4-3d0b-400a-97c2-dc95dc399570.mp4

**Comment by zhangshuqi** [comment]
抱歉 我在修改代码时,发现我的复现是错误的, 我重新描述如何复现
1.使用ImageGallerySaver将页面截图Uint8List对象  插入到相册
2.在手机文件管理器中将图片删除 
3.重新打开图片选择器则可以复现.

备注: 如果从手机图库删除则不会出现此问题.

**Comment by AlexV525** [comment]
> 1.使用ImageGallerySaver将页面截图Uint8List对象 插入到相册 2.在手机文件管理器中将图片删除 3.重新打开图片选择器则可以复现.

使用单个文件提供调用代码。

**Comment by zhangshuqi** [comment]
您好,您指的是  我需要提供调用assets_picker 的代码吗?

**Comment by Lilee902** [comment]
I had a similar problem. You can select but not preview.my device is redmi k30 5G, os android 12.
我遇到了一个相似的问题。可以选择但不能预览。我的手机是红米k30 5g, 系统是安卓12.

https://user-images.githubusercontent.com/20561112/180943986-93c39e19-9199-4c08-9388-96570f0d2703.mp4

**Comment by Lilee902** [comment]
i add AssetPickerConfig args previewThumbnailSize fix it.
because i find AssetEntityImageProvider need previewThumbnailSize, but when i debug, size is null.

```
  const AssetEntityImageProvider(
    this.entity, {
    this.isOriginal = true,
    this.thumbnailSize = PMConstants.vDefaultGridThumbnailSize,
    this.thumbnailFormat = ThumbnailFormat.jpeg,
  }) : assert(
          isOriginal || thumbnailSize != null,
          "thumbSize must not be null when it's not original",
        );
```

**Comment by AlexV525** [comment]
> 您好,您指的是 我需要提供调用assets_picker 的代码吗?

调用 saver 后调用选择器的最小复现代码。

**Comment by clycheng2015** [comment]
遇到了类似的问题，也是小米的较早机型！

**Comment by AlexV525** [comment]
自 98ef9fd (2.2.0) 起，生成 entity 前已开始检查实际文件是否存在。
