### ISSUE TITLE
[BUG] I am not able to get png images from AQUOS sense 4 SHARP Android 10 device.

### ISSUE THREAD

**Issue by Hoai-Phong** [fluttercandies/flutter_photo_manager#774]
**I am not able to get png images from AQUOS sense 4 SHARP Android 10 device.**
I've tried everything and still can't get the png image on this device.
I need help . 

**Screenshots**
![image](https://user-images.githubusercontent.com/83800555/172085420-a0c68f42-0329-4916-adb1-0fac4e18e77a.png)
![image](https://user-images.githubusercontent.com/83800555/172085750-b139ba2c-a4b5-48e3-8628-27bba89518ab.png)

![image](https://user-images.githubusercontent.com/83800555/172085485-773bc44e-17ac-4abb-880d-2368ccfb0678.png)
![image](https://user-images.githubusercontent.com/83800555/172085515-07e45e78-18f7-48d1-b81b-890939fb4a57.png)

**Flutter version**
 Flutter Version : 2.10.5
 Photo_manager: ^2.1.1

**Device **
Device :  AQUOS sense 4 SHARP Android 10

**Comment by AlexV525** [comment]
Try
https://github.com/fluttercandies/flutter_photo_manager/blob/d51761629915072c0957342eb4bc44d6b43c8081/lib/src/filter/filter_options.dart#L86

**Comment by Hoai-Phong** [comment]
@AlexV525 Thank you, i tried the problem solved.

**Comment by ChanShiraz** [comment]
Hi!
I also having trouble getting the PNG images, can someone
<img width="734" alt="Screenshot 2024-02-09 at 4 30 27 PM" src="https://github.com/fluttercandies/flutter_photo_manager/assets/87255860/14b16c83-d7ea-418b-ac8f-dd9795b21b46">
<img width="774" alt="Screenshot 2024-02-09 at 4 30 59 PM" src="https://github.com/fluttercandies/flutter_photo_manager/assets/87255860/4b89c061-d176-4c6d-bba6-84fb186dcb98">

 please help me
