### ISSUE TITLE
[BUG]assetExistsWithId Unhandled Exception: type

### ISSUE THREAD

**Issue by Lay523** [fluttercandies/flutter_photo_manager#776]
**Describe the bug**
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'Future<bool>' in type cast
#0      PhotoManagerPlugin.assetExistsWithId (package:photo_manager/src/internal/plugin.dart:311:7)
#1      AssetEntity.exists (package:photo_manager/src/types/entity.dart:634:37)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter version**

**Smartphone (please complete the following information):**

**Log**

If applicable, add logs to help explain your problem.

```bash
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'Future<bool>' in type cast
#0      PhotoManagerPlugin.assetExistsWithId (package:photo_manager/src/internal/plugin.dart:311:7)
#1      AssetEntity.exists (package:photo_manager/src/types/entity.dart:634:37)
```

**Comment by AlexV525** [comment]
Please provide valid version informations.

**Comment by Lay523** [comment]
> 请提供有效的版本信息。

photo_manager: ^2.1.2
