### ISSUE TITLE
[BUG] Can't read audio path from my gallery (FLUTTER)

### ISSUE THREAD

**Issue by amalnaami** [fluttercandies/flutter_photo_manager#779]
**Describe the bug**
I try to open audio from my gallery and paly it

**To Reproduce**
1. Try to catch audios from gallery
fetchAudio() async {
    Future.delayed(const Duration(seconds: 1));
    lastPage = currentPageAudio;
    List<AssetPathEntity> albumsAudio =
        await PhotoManager.getAssetPathList(type: RequestType.audio);
    if (albumsAudio.isEmpty) return;
    media = await albumsAudio[0].getAssetListPaged(page: 0, size: 60);
    media.length;
  }
2. Play one of them using audioPlayer
 newFile =  await media[index].file;
 print( '===== ==== ${newFile!.path}');
  _audioPlayer.play(newFile!.path);
3. It doesn't play it and give me this error
 Unexpected error!
D/AudioPlayers(18848): java.io.FileNotFoundException: /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory)

Unhandled Exception: PlatformException(Unexpected error!, /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory), java.io.FileNotFoundException: /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory)

**Expected behavior**
Play selected audio

**Log**
I/flutter (18848): ===== ==== /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3
D/AudioPlayers(18848): Unexpected error!
D/AudioPlayers(18848): java.io.FileNotFoundException: /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory)
D/AudioPlayers(18848): 	at libcore.io.IoBridge.open(IoBridge.java:496)
D/AudioPlayers(18848): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
D/AudioPlayers(18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1238)
D/AudioPlayers(18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1216)
D/AudioPlayers(18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1181)
D/AudioPlayers(18848): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
D/AudioPlayers(18848): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
D/AudioPlayers(18848): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
D/AudioPlayers(18848): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
D/AudioPlayers(18848): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
D/AudioPlayers(18848): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
D/AudioPlayers(18848): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
D/AudioPlayers(18848): 	at android.os.Handler.handleCallback(Handler.java:883)
D/AudioPlayers(18848): 	at android.os.Handler.dispatchMessage(Handler.java:100)
D/AudioPlayers(18848): 	at android.os.Looper.loop(Looper.java:224)
D/AudioPlayers(18848): 	at android.app.ActivityThread.main(ActivityThread.java:7561)
D/AudioPlayers(18848): 	at java.lang.reflect.Method.invoke(Native Method)
D/AudioPlayers(18848): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
D/AudioPlayers(18848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
D/AudioPlayers(18848): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
D/AudioPlayers(18848): 	at libcore.io.Linux.open(Native Method)
D/AudioPlayers(18848): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
D/AudioPlayers(18848): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
D/AudioPlayers(18848): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
D/AudioPlayers(18848): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7458)
D/AudioPlayers(18848): 	at libcore.io.IoBridge.open(IoBridge.java:482)
D/AudioPlayers(18848): 	... 18 more
E/flutter (18848): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Unexpected error!, /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory), java.io.FileNotFoundException: /storage/emulated/0/Download/Albumaty.Com_Amr_Diab_Ahia.mp3: open failed: ENOENT (No such file or directory)
E/flutter (18848): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/flutter (18848): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
E/flutter (18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1238)
E/flutter (18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1216)
E/flutter (18848): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1181)
E/flutter (18848): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
E/flutter (18848): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/flutter (18848): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
E/flutter (18848): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (18848): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (18848): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter (18848): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
E/flutter (18848): 	at android.os.Handler.handleCallback(Handler.java:883)
E/flutter (18848): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter (18848): 	at android.os.Looper.loop(Looper.java:224)
E/flutter (18848): 	at android.app.ActivityThread.main(ActivityThread.java:7561)
E/flutter (18848): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18848): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (18848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
E/flutter (18848): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/flutter (18848): 	at libcore.io.Linux.open(Native Method)
E/flutter (18848): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/flutter (18848): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/flutter (18848): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/flutter (18848): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7458)
E/flutter (18848): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/flutter (18848): 	... 18 more
E/flutter (18848): , null)
E/flutter (18848): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (18848): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (18848): <asynchronous suspension>
E/flutter (18848): #2      AudioPlayer.invokeMethod (package:audioplayers/src/audioplayer.dart:151:20)
E/flutter (18848): <asynchronous suspension>
E/flutter (18848): #3      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:173:20)

**Flutter version**
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 2.10.4 at C:\flutterSDKs\flutter_2.10.4                                     
    • Upstream repository https://github.com/flutter/flutter.git                                  
    • Framework revision c860cba910 (3 months ago), 2022-03-25 00:23:12 -0500                     
    • Engine revision 57d3bac3dd                                                                  
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Amal Naami\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Java\jdk-15.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7371

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Amal Naami\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • M2003J15SC (mobile) • 1ebd95170407 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)   • windows      • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)          • edge         • web-javascript • Microsoft Edge 102.0.1245.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by AlexV525** [comment]
It's better to use `getMediaUrl()` to play with.

**Comment by amalnaami** [comment]
@AlexV525 
If use it to open audio it get me path like this "/mdia/xral/audi/mdia/27464"
how I can convert it to mp3 ?

**Comment by AlexV525** [comment]
The media URL is not `path`, so play it directly with URI controller.
