### ISSUE TITLE
[BUG] loadFile fails for almost all images

### ISSUE THREAD

**Issue by DieGlueckswurst** [fluttercandies/flutter_photo_manager#780]
**Describe the bug**
I implemented the package and it was working fine so far. I can display the images how I want it but now I want to save them inside the app. This is where it fails. For **almost all** images (talking here about  > 90%) I `.loadFile` is returning null.

My app is really complex and you would need access to my PhotoLibrary so I can not really give you an example but this is the code where I try to save the image:
```
if (returnObject is AssetEntity) {
         print(returnObject.createDateTime);  // -> works everytime

        dynamic bytes = await returnObject.originBytes; // -> almost always null
        File? image = await returnObject.originFile;  // -> almost always null
        File? loadImage = await returnObject.loadFile();  // -> almost always null
        File? fileImage = await returnObject.file;  // -> almost always null
}
```

What am I missing here? The package is pretty much useless if you can not save the actual images. I must be forgetting something but I have no idea what...

I also downloaded the `example-project` and checked if I can open the images there, but same result: It shows the thumbnail but can not get the data:

> Bad state: The data of the entity is null: AssetEntity(id: 6E76423A-C3BF-46CF-BFEB-9F7018C9DE81/L0/001 , type: AssetType.image)

**Smartphone (please complete the following information):**
 - Device: iPod touch - 7th generation - iOS 15.2

**Comment by AlexV525** [comment]
> Bad state: The data of the entity is null: AssetEntity(id: 6E76423A-C3BF-46CF-BFEB-9F7018C9DE81/L0/001 , type: AssetType.image)

Your entity ID seems a little bit weird. Can you determine which type of assets failed to obtain the data? Such as iCloud, Smart Album, ID type, taken by camera, imported from other devices?
