### ISSUE TITLE
[BUG] No assets were found on HOS 2.0

### ISSUE THREAD

**Issue by azhansy** [fluttercandies/flutter_photo_manager#781]
当前demo， 测试机中，mate9当前Cursor语句拿不到视频文件。
没有报错信息，就是拿不到。
mate9:
- sdk:28
- android 9
- ---------------
flutter ：
![image](https://user-images.githubusercontent.com/13672892/174803189-376764da-9f4d-4e53-8099-fd73988fcc69.png)

**Comment by AlexV525** [comment]
提供机型详细信息、Cursor log、相册截图。

**Comment by azhansy** [comment]
-  机型信息
![photo-size-5-6167690453328178978-y](https://user-images.githubusercontent.com/13672892/174937335-cee8500a-11c3-4140-b0db-6b1cca3b8821.jpg)

- Cursor log:
![image](https://user-images.githubusercontent.com/13672892/174937291-92822ac9-9ce8-498a-85c4-a032585c062d.png)

-  相册截图
![destop](https://user-images.githubusercontent.com/13672892/174937504-249dfb29-5a53-465a-91db-81f92b45b77c.jpg)

**Comment by AlexV525** [comment]
神奇…………

**Comment by AlexV525** [comment]
Package 版本？

**Comment by azhansy** [comment]
项目引用的是：photo_manager: ^2.1.1
也跑了当前github的最新代码example，图片正常出来，视频不行。
-----
我把插件里的Cursor改为以下代码，
能拿出来视频，但是demo中recent的数量有问题，视频时长取出来一直为0。
时长的问题最后我用MediaMetadataRetriever 重新获取。
但是这个方案并不好，给你们参考一下，希望有帮助！
`
val mImageUri: Uri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI
        val proj = arrayOf(
            _ID,
            MediaStore.Video.Thumbnails.DATA,
            MediaStore.Video.Media.DURATION,
            MediaStore.Video.Media.SIZE,
            MediaStore.Video.Media.DISPLAY_NAME,
            MediaStore.Video.Media.DATE_MODIFIED
        )
      
        val cursor = context.contentResolver.query(
            mImageUri,
            proj,
            MediaStore.Video.Media.MIME_TYPE + "=?", arrayOf("video/mp4"),
            MediaStore.Video.Media.DATE_MODIFIED + " desc"
        ) ?: return emptyList()
        cursor.use {

            while (it.moveToNext()) {
                val id = it.getString(it.getColumnIndex(MediaStore.Video.Media._ID))
                val name = it.getString(it.getColumnIndex(MediaStore.Video.Media.DATA))
//                val count = it.getInt(it.getColumnIndex(MediaStore.Video.Media.DURATION))
                val retriever = MediaMetadataRetriever()
                retriever.setDataSource(name)
                val timeString =
                    retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)
                val count =timeString?.toInt() ?:0

                val entity = GalleryEntity(id, name, count, 0)
                if (option.containsPathModified) {
                    injectModifiedDate(context, entity)
                }
                Log.d("dashu", "entity, list=${entity.toString()}，it.getColumnIndex(MediaStore.Video.Media.DURATION=${it.getColumnIndex(MediaStore.Video.Media.DURATION)}")
                list.add(entity)
            }
}
`

**Comment by AlexV525** [comment]
尝试设置 https://github.com/fluttercandies/flutter_photo_manager/blob/main/lib/src/filter/filter_options.dart#L153

**Comment by azhansy** [comment]
可以取出来了！只是视频时长都为0

**Comment by AlexV525** [comment]
> 可以取出来了！只是视频时长都为0

视频保存时没有妥善的存储时长，为对应操作的问题。
