### ISSUE TITLE
[BUG] The title of the video is not allowed to be modified in iOS

### ISSUE THREAD

**Issue by RockXeng** [fluttercandies/flutter_photo_manager#789]
**Describe the bug**
Is failed to change video title when I save the video using:
```
PhotoManager.editor
          .saveVideo(File(resourceFilePath), title: "123");
```

**Expected behavior**
can save video to Photos and title is "123"

**Screenshots**
According to this bug, I find the change video title code is unused in plugin now, and I want to know why disable this?
<img width="957" alt="截屏2022-07-06 下午1 31 39" src="https://user-images.githubusercontent.com/23146173/177476979-7c41b5b1-6875-4e0f-8de0-0c523fa204da.png">

**Comment by RockXeng** [comment]
**What happened：**
When I download video with custom title "123" in iOS, the title is not change to "123" in Photos App.

```
final resourceFilePath = await file.resourceFilePath;
    AssetEntity? assetEntity;
assetEntity = await PhotoManager.editor
          .saveVideo(File(resourceFilePath), title: "123");
```
download is success, but the title is incorrect:
![IMG_9400](https://user-images.githubusercontent.com/23146173/177679256-ce8140b8-74f5-49c9-81c5-79b29161ebd3.PNG)

**What do you expect?**
The video title should to be 123.MP4

**Comment by AlexV525** [comment]
> When I download video with custom title "123" in iOS, the title is not change to "123" in Photos App.

Regarding the title definition, you should use `123.mp4` with the extension `mp4`, otherwise it might cause some resolving trouble.

Submitting fix now.
