### ISSUE TITLE
How to get an AssetEntity or asset id from a file path

### ISSUE THREAD

**Issue by jimmyff** [fluttercandies/flutter_photo_manager#795]
I am using `https://github.com/KasemJaffer/receive_sharing_intent` so a user can share a photo to my app. I get a `SharedMediaFile` object, this contains the file path -I would like to convert this to an AssetEntity so I can standardise my code for viewing photographs but I cannot find a way to do this?

Thank you

**Comment by AlexV525** [comment]
`AssetEntity` only represents existing assets in the device's gallery, which is readable and public for all apps, see https://github.com/fluttercandies/flutter_photo_manager#from-id. The only way to achieve this is to save the file from the path using `saveImageWithPath` to create a new entity.

Closing as it's not planned.

**Comment by ManmohanTalwar** [comment]
I also have a similar use case, where i tried the solution @AlexV525 you suggested and it is working perfectly fine, but it just creates an duplicate file in the device, which can be a issue, as some users can select larger files. 

If we could have a way to fetch the assetEntity  based on the asset path, that would make more sense in this particular case scenario.

It will be very useful if it can be supported by the plugin.

Thankyou!
