### ISSUE TITLE
[Custom] How to delete a file below Android 10

### ISSUE THREAD

**Issue by Flajt** [fluttercandies/flutter_photo_manager#796]
## Expect
Delete files on android 9 or everything below 10 works 

Android Version: 9 or below
`compileSdkVersion`: 33
`minSdkVersion`: 16
`targetSdkVersion`: 31
Permissions: READ_STORAGE,WRITE_STORAGE (max_sdk=18)
The device used: Android Pixel 2 with Android SDK 26

## What happens: 
Can't delete file via flutter `File.delete` (fails with: `Cannot delete file, path = '/storage/emulated/0/DCIM/Camera/IMG_20220709_175227.jpg' (OS Error: Permission denied, errno = 13)` ) or ` PhotoManager.editor.deleteWithIds` (fails with: `PlatformException(deleteWithIds failed, null, null, null)`)

The latter works with Android 10+

It seems like I'm missing something but idk what, if someone can give me an idea I would really appreciate it.

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager/blob/main/example/android/app/src/main/AndroidManifest.xml#L9
