### ISSUE TITLE
通过AssetPathEntity获取到的相册名称（name）可以是中文吗？[Feature]

### ISSUE THREAD

**Issue by Meditator-K** [fluttercandies/flutter_photo_manager#808]
目前通过AssetPathEntity获取到的相册名称有的是中文，有的是英文，可以做成可配置吗？比如相机，在手机相册中显示的是“相机”，通过AssetPathEntity获取到的是Camera，微信照片在手机相册显示的是微信，通过AssetPathEntity获取到的是WeiXin。

**Comment by AlexV525** [comment]
实现方法判断后自己处理。
