### ISSUE TITLE
[BUG] Unresolved reference: lowercase

### ISSUE THREAD

**Issue by bugrevealingbme** [fluttercandies/flutter_photo_manager#813]
Flutter 3.0.5

flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.2.0/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt: (59, 29): Unresolved reference: lowercase

**Comment by AlexV525** [comment]
Duplicate of #561
