### ISSUE TITLE
为什么没有图片的相册也返回

### ISSUE THREAD

**Issue by anchaoLu** [fluttercandies/flutter_photo_manager#822]
## Expect
调用 
```dart
PhotoManager.getAssetPathList(
          type: RequestType.image,
          filterOption: optionGroup,
        )
```
获取相册时，不要返回 assetCountAsync 为 0 的相册
或者，我该设置什么参数来避免这一情况

## ScreenShots
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/106209730/188408071-f60f9dd3-e022-4545-a945-cb787a287dcb.png)

**Comment by AlexV525** [comment]
需要自己处理，过滤掉请求完为空的相册。
