### ISSUE TITLE
[BUG] 2.3.0   need android compile version33

### ISSUE THREAD

**Issue by sara010** [fluttercandies/flutter_photo_manager#831]
cannot compile, show this
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /bigdata/buildspace/lining/workspace/release/android/app/build.gradle:
android {
  compileSdkVersion 33
  ...
}

e: xxxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.3.0/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoM
anagerPlugin.kt: (171, 58): Unresolved reference: TIRAMISU
e: xxxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.3.0/android/src/main/kotlin/com/fluttercandies/photo_manager/core/PhotoM
anagerPlugin.kt: (196, 58): Unresolved reference: TIRAMISU
e: xxxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.3.0/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/
PermissionsUtils.kt: (255, 75): Unresolved reference: READ_MEDIA_IMAGES
e: xxxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.3.0/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/
PermissionsUtils.kt: (256, 75): Unresolved reference: READ_MEDIA_VIDEO
e: xxxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/photo_manager-2.3.0/android/src/main/kotlin/com/fluttercandies/photo_manager/permission/
PermissionsUtils.kt: (257, 75): Unresolved reference: READ_MEDIA_AUDIO

**Comment by AlexV525** [comment]
Closing as intented.
