### ISSUE TITLE
List of assets entities creating a copy in tmp directory in ios which causes storage issue

### ISSUE THREAD

**Issue by subash8144** [fluttercandies/flutter_photo_manager#835]
I am reading all the files and showing the images in the ios flutter app, which creates a copy in tmp directory in ios ..how to restrict that or how to handle this. This makes the app as highest storage-consuming app after the ios photos app.

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager#cache-on-ios

**Comment by subash8144** [comment]
Thank you!
