### ISSUE TITLE
[BUG] Permission denied on Android 13

### ISSUE THREAD

**Issue by rignaneseleo** [fluttercandies/flutter_photo_manager#837]
**Describe the bug**
On android 13, the app asks for the permission to access photos and video, the pemission is agreed, but the app returns PermissionState.denied. No problems with other versions.

**To Reproduce**
1. Run  result = await PhotoManager.requestPermissionExtend()
2. Accept the permission dialog
3. Print results and you'll get PermissionState.denied

**Expected behavior**
If I accept the permission, the PermissionState should be granted. 

**Flutter version**
Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-US)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5g
 - OS: Android 13

**Code**

This is the code:
 ```
final PermissionState result = await PhotoManager.requestPermissionExtend();
    print('permission result: $result');//this returns PermissionState.denied
```

Manifest
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="32" />

    <!-- From android 13 -->
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />

    <!-- Media location permission-->
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />

    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:name=".MyApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="MyFamily"
        android:requestLegacyExternalStorage="true"
        >
        ....
```

**Comment by AlexV525** [comment]
Make sure you're using the latest stable version of the plugin (2.3.0) and retest this again.

**Comment by rignaneseleo** [comment]
I am using version 2.3.0. Sorry I forgot to mention that!

**Comment by AlexV525** [comment]
Tested with the example and the issue has not reproduced on the simulator.
![image](https://user-images.githubusercontent.com/15884415/193331555-3f19e6be-2536-485f-8483-4f1d7ace8f01.png)

**Comment by 1N50MN14** [comment]
@AlexV525 I'm facing the same issue, precisely as described in the issue. It's strange it's not reproducable at your end, could it you're not targeting sdk version 33 in your build.grade?

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager/blob/0e61f560bb6e8f624747cff3a0e8861463960314/example/android/app/build.gradle#L26

**Comment by 1N50MN14** [comment]
@AlexV525 Thanks for the quick reply. Strange, I was able to work around the issue by downgrading the target sdk version to 32 but that's not a solution either. It it possible you have a different compile version in local.properties? would it be possible to manually force the versions in build.grade just to double check if it's not too much to ask? like so:
```
  targetSdkVersion 33
  compileSdkVersion 33
```

**Comment by 1N50MN14** [comment]
@AlexV525 Thanks for the quick reply. Strange, I was able to work around the issue by downgrading the target sdk version to 32 but that's not a solution either. It it possible you have a different compile version in local.properties? would it be possible to manually force the versions in build.grade just to double check if it's not too much to ask? like so:
```
  targetSdkVersion 33
  compileSdkVersion 33
```

**Comment by AlexV525** [comment]
> Is it possible you have a different compile version in local.properties?

These fields won't generate in the `local.properties`.

**Comment by AlexV525** [comment]
I'm checking whether it's related to a version migrate.

**Comment by AlexV525** [comment]
I'm not getting any luck in reproducing this. Can you guys try with the example or provide a minimum reproducible demo?

**Comment by 1N50MN14** [comment]
@AlexV525 So I cloned the example from master, ran it and it worked as expected, i.e. permission state returning authorized. Both master and pub.dev versions. It's definitely not the package itself, you were right. I wonder if one of the firebase packages (or potentially other ones) are somehow interfering, I'm going to investigate this further. Thank you again.

**Comment by AlexV525** [comment]
Once you have progress with this, you can still update the conclusion at here so we can be aware about potential impacts.

**Comment by 1N50MN14** [comment]
Yup, that's the plan 👍

**Comment by 1N50MN14** [comment]
@AlexV525 I figured out the culprit. It was in AndroidManifest, the tag `android:maxSdkVersion="29"` was missing from the `android.permission.WRITE_EXTERNAL_STORAGE` permission which somehow caused the issue. 

The only issue that I'm facing (also happens in the example app) is that now `PhotoManager.requestPermissionExtend()` *always* immediately returns `PermissionState.authorized` without awaiting for the Future / the user allowing/disallowing access, but also if access has been disallowed. All it does is basically trigger the permission dialog.

In my cases, this causes `wechat_assets_picker` to throw a `PlatformException(Request for permission failed., User denied permission., null, null)`, and there's no way for me to know whether to display the picker or not because `PhotoManager.requestPermissionExtend()`  always returns `PermissionState.authorized`.

This also happens in the example.

Either ways, when it comes to this issue, we now know why.

**Comment by 1N50MN14** [comment]
@AlexV525 Yes ofcourse, done
