### ISSUE TITLE
[BUG] Use `requestLegacyExternalStorage` when your project is targeting above Android Q

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#844]
**Describe the bug**

Calling `PermissionState state = await PhotoManager.requestPermissionExtend();` on my android device result in error : 

```
I/flutter (27000): PlatformException(STORAGE_NOT_LEGACY, Use `requestLegacyExternalStorage` when your project is targeting above Android Q., null, null)
I/flutter (27000): 
I/flutter (27000): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter (27000): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
I/flutter (27000): <asynchronous suspension>
I/flutter (27000): #2      PhotoManagerPlugin.requestPermissionExtend (package:photo_manager/src/internal/plugin.dart:72:24)
I/flutter (27000): <asynchronous suspension>
```

This seems to be a very simple error but i have already set the `requestLegacyExternalStorage` in my android manifest.xml :  

```
  <activity
            android:name=".MainActivity"
            android:exported="true"
            android:requestLegacyExternalStorage="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"       
android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
```

And here are my permissions : 

```
 <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission android:name="android.permission.CAMERA" />
```

I have set `android:maxSdkVersion="29"` according to what i saw on another issue here and from the example project which also have this tag but i am still getting the error. 
I have checked the example project and i have the same config, my targetSDK is also 33 but my `minSdkVersion` is 26. 
Besides i saw that in the example project you don't set the `requestLegacyExternalStorage` flag in your manifest.

The weirdest thing is that i see that the permission is granted (in my phone's settings for this app) and it does this only on one of my android phone that i specify below. 
It's working fine (the very same code) with my other android phone Motorola under Android 11.
It's also working everywhere with the example project.

What am i missing here ? 

(I must use `flutter : 2.10.5` for my client for PlatformViews reasons, i am aware it's an older version of Flutter but i am using `photo_manager: 2.3.0` anyway)

**Flutter version**

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
    • Flutter version 2.10.5 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (6 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • CPH1931 (mobile) • ee9b32b5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
**Smartphone (please complete the following information):**
 - Device: OPPO A5 2020
 - OS: Android 
 - Version: 10

**Comment by AlexV525** [comment]
> This seems to be a very simple error but i have already set the `requestLegacyExternalStorage` in my android manifest.xml :
> 
> ```
>   <activity
>             android:name=".MainActivity"
>             android:exported="true"
>             android:requestLegacyExternalStorage="true"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"       
> android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize">

https://github.com/fluttercandies/flutter_photo_manager/issues/747#issuecomment-1087320326

https://github.com/fluttercandies/flutter_photo_manager/blob/91d612857a5d601597cb841ac7f7bba4abf21ddd/example/android/app/src/main/AndroidManifest.xml#L14-L18

> I have set `android:maxSdkVersion="29"` according to what i saw on another issue here and from the example project which also have this tag but i am still getting the error. I have checked the example project and i have the same config, my targetSDK is also 33 but my `minSdkVersion` is 26. Besides i saw that in the example project you don't set the `requestLegacyExternalStorage` flag in your manifest.

https://github.com/fluttercandies/flutter_photo_manager/pull/833/files

https://github.com/fluttercandies/flutter_photo_manager/blob/e66aa8fcc905709f5bede738a4a89342280e6a82/CHANGELOG.md?plain=1#L13-L17
