### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by Adrift001** [fluttercandies/flutter_photo_manager#845]
**Describe the bug**

**To Reproduce**
Select a picture with a long file name

<img width="917" alt="image" src="https://user-images.githubusercontent.com/8119320/194684635-cbc8db07-ab7d-4766-921c-d5676c4d0338.png">

**Comment by Adrift001** [comment]
Both iOS and Android have this problem.

**Comment by AlexV525** [comment]
Logs?

**Comment by tranvanphay** [comment]
> Logs?
[iOS platform]
File name is difference with file name from Photos app.

assetEntity.originFile.path = "/private/var/mobile/Containers/Data/Application/BB35B521-8965-47D3-B3B3-4B4A0D203903/tmp/.image/1665504477.520537_o_IMG_3244.HEIC"

file name from Photos app is : IMG_3244.HEIC

Attach image is example

![Screen Shot 2022-10-24 at 16 30 38](https://user-images.githubusercontent.com/42576241/197495400-4cbda95d-8d0c-4ff8-85bd-07f8e2724f0d.png)
