### ISSUE TITLE
[BUG] [Android] Stale media cache when asset is modified

### ISSUE THREAD

**Issue by ua741** [fluttercandies/flutter_photo_manager#847]
**Describe the bug**
The caching library doesn't update the cache whenever a media is modified.

**To Reproduce**
1. Request for thumbnail for a media
2. Use any photo editor app to rotate the media or apply filter
3. Request for thumbnail for the media.

**Expected behavior**
When a file is rotated or modified, the library should return updated thumbnail.

**Flutter version**

Flutter version 3.0.0

**Smartphone (please complete the following information):**
 - OS: Android
 - Photo Manager Library Version : 2.1.4

**Potential Solution**
https://bumptech.github.io/glide/doc/caching.html#cache-invalidation
We can may be use lastModifiedAt as the ObjectKey Signature?

**Comment by AlexV525** [comment]
Which device can reproduce the issue? My gallery app will generate a new image after editing.

**Comment by ua741** [comment]
> Which device can reproduce the issue? My gallery app will generate a new image after editing.
Does it generate new image even after rotating the photo?  

I used [SimpleMobile](https://github.com/SimpleMobileTools/Simple-Gallery/releases) Gallery for basic editing. During save, it will prompt for file name (it automatically adds _1 as suffix).  If you remove the suffix, it will overwrite/modify the existing file. 

And thank you so much for the quick PR!

**Comment by AlexV525** [comment]
Does the PR solves the issue?

**Comment by ua741** [comment]
> Does the PR solves the issue?

Yes.
