### ISSUE TITLE
[BUG] `title` is incorrect on iOS 

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#849]
**Describe the bug**

```assetEntity.title``` doesn't return the value you put in ```final AssetEntity? asset =
          await PhotoManager.editor.saveVideo(file, title: name);```

It works fine on Android.

**To Reproduce**
1. In the example project, set the following `FilterOption` : 

```
final FilterOptionGroup _filterOptionGroup = FilterOptionGroup(
    videoOption: const FilterOption(
      needTitle: true
    ),
    imageOption: const FilterOption(
      needTitle: true,
      sizeConstraint: SizeConstraint(ignoreSize: true),
    ),
  );
```
in `main.dart`
2. Set the following in `main.dart` : 

```
final List<AssetEntity> entities = await _path!.getAssetListPaged(
      page: 0,
      size: _sizePerPage,
    );
    for (var element in entities) {
      print("Asset title : ${element.title}");
    }
```
3. print the `videoName` var in the `saveVideo` method of the example
4. Remember the name
5. Rebuild the app once the video is downloaded locally 
6. See that at the fetch, the title has nothing to with the title passed in parameter

**Expected behavior**
Using :  

```final AssetEntity? asset = await PhotoManager.editor.saveVideo(file, title: name);```

Should mean that `asset.title` should return `name` with the above code.

**Flutter version**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max, iPhone 12 Pro, iPhone 8 plus
 - OS: iOS 16

**Comment by AlexV525** [comment]
Duplicate of #739 ?

**Comment by Tom3652** [comment]
Alright yes indeed, using `titleAsync` is working fine it returns the title of the video, and i have no performance issues because no need to use `needTitle: true`. 
I prefer this solution
