### ISSUE TITLE
On the iOS platform, the returned file!.length() is larger than the original image[BUG]

### ISSUE THREAD

**Issue by tianxiawoyougood** [fluttercandies/flutter_photo_manager#853]
**Describe the bug**
On the iOS platform, the returned file!.length() is larger than the original image

```bash
var file =entity.file;
int size = await file!.length();
```
**To Reproduce**

**Expected behavior**
same size as original

**Screenshots**

**Flutter version**
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/binsun1/Git/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/binsun1/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode_14.1_RC.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (1 available)
    • macOS (desktop)     • macos                     • darwin-x64 • macOS 12.6.1 21G217 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12 Pro]
 - OS: [e.g. iOS16.0]

**Log**

If applicable, add logs to help explain your problem.

```bash

```

**Comment by tianxiawoyougood** [comment]
Why Invalid, what else need to be provided

**Comment by AlexV525** [comment]
> the returned file!.length() is larger than the original image

Why don't you use `originFile`?

**Comment by szuwest** [comment]
the entity.file size is large than the entity.originFile size.

**Comment by szuwest** [comment]
> > the returned file!.length() is larger than the original image
> 
> Why don't you use `originFile`?

我实际测试 通过AssetEntity.originFile得到的图片只有不到2M，但是通过AssetEntity.file得到的图片却又7M多！这应该是哪里有bug。
iPhone 11， iOS 17.6.1
