### ISSUE TITLE
[BUG] `thumbnailDataWithSize` doesn't return thumbnail with a specified size with ProRAW

### ISSUE THREAD

**Issue by dev4jam** [fluttercandies/flutter_photo_manager#857]
**Describe the bug**

AssetEntity thumbnailDataWithSize returns full-size image for DNG files on iOS even size specified.

**To Reproduce**
1. Fetch any DNG (Apple ProRAW) asset 
2. Call thumbnailDataWithSize with ThumbnailSize(300, 300)

Error: Full-size image data is returned.

**Expected behavior**

Cropped (down-sized) image data is returned.

**Flutter version**
3.3.7

**Smartphone (please complete the following information):**
Any device on iOS16

**Proposed solution:**
Based on `PHImageManager` documentation `PHImageRequestOptionsResizeModeExact` needs to be specified (currently set to `PHImageRequestOptionsResizeModeFast`). Or give the option to provide resize mode in `thumbnailDataWithSize` function.

**Comment by AlexV525** [comment]
Please use `ThumbnailOption.ios` and verify if the issue still exists.

https://github.com/fluttercandies/flutter_photo_manager/blob/c14c35d02b4e416cbe5f0e54c0f2336124716379/lib/src/types/thumbnail.dart#L62-L69
