### ISSUE TITLE
[BUG] Deleted asset ids from addChangeCallback don't match with the existing asset ids 

### ISSUE THREAD

**Issue by arazosman** [fluttercandies/flutter_photo_manager#860]
**Describe the bug**
I would like to update my custom gallery in the app when a user deletes photos from the app gallery. I listen changes by `addChangeCallback` method. When the user deletes some images from the app gallery, this callback gets called with some ids that represent deleted asset ids. The problem is, these deleted ids don't match with the fetched asset ids which obtained by `getAssetListRange` method.

Here is the code example I use to fetch images:

```dart
List<AssetEntity> allPhotos = [];

getPhotos();

getPhotos() async {
  List<AssetPathEntity> _albums = await PhotoManager.getAssetPathList(
    type: RequestType.image,
    onlyAll: true,
  );
  for (AssetPathEntity _album in _albums) {
    await addPhotosOfAlbum(_album);
  }
}

Future addPhotosOfAlbum(AssetPathEntity _album) async {
  List<AssetEntity> _photos = await _album.getAssetListRange(
    start: 0,
    end: 3000,
  );
  allPhotos.addAll(_photos);
}
```

Here is the code example I listen app gallery changes:

```dart
PhotoManager.addChangeCallback(
  (MethodCall c) => handleGalleryChange(c.arguments),
);

handleGalleryChange(dynamic change) async {
  List<dynamic> _delete = (change["delete"] ?? []) as List<dynamic>;

  if (Platform.isAndroid) {
    String _type = change["type"] ?? "";
    if (change["id"] != null) {
      if (_type == "delete") {
        _delete.add({"id": change["id"]});
      }
    }
  }

  if (_delete.isNotEmpty) {
    List<String> ids = _delete.map((e) => e["id"].toString()).toList();
    await deletePhotos(ids);
  }
}

deletePhotos(List<String> ids) async {
  for (String id in ids) {
    // THE PROBLEM IS HERE. THE ID CANNOT BE FOUND IN ALL_PHOTOS. 
    final _photo = allPhotos.firstWhereOrNull((a) => a.id == id);
    // _PHOTO RETURNS NULL.
    allPhotos.remove(_photo);
  }
}
```

I am not sure if it is a bug or I am doing something wrong.

**To Reproduce**
1. Get photos via `getAssetListRange` method.
2. Listen app gallery changes via `addChangeCallback` method.

**Expected behavior**
3. I expect `addChangeCallback` returns ids that matches with ids that comes with `getAssetListRange` method.

**Flutter version**
Flutter version 3.3.6
PhotoManager version: 2.4.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.0
 - Browser: Firefox
 - Version 106

**Comment by AlexV525** [comment]
We only pass the native events, so it is likely a system issue that is out of our support. You can set breakpoints to where those callback gets called to see if we manipulated the content to an incorrect value if you'd prefer.
