### ISSUE TITLE
一些手机使用AssetEntity.origin字节的速度非常慢

### ISSUE THREAD

**Issue by qq464418017** [fluttercandies/flutter_photo_manager#866]
final List<AssetEntity>? result = await AssetPicker.pickAssets(
      context,
      pickerConfig: AssetPickerConfig(
        maxAssets: 20,
        textDelegate: t,
        requestType: RequestType.image,
      ),
    );

    if (result == null) {
      return;
    }
    _index = 0;

    //阿里云oss 不支持超过20MB 图片的缩略处理
    bool hasMax = false;
    Map<int, Uint8List> _data = <int, Uint8List>{};
    for (int i = 0; i < result.length; i++){
      var ae = result[i];
      var bytes = await ae.originBytes;
      _data[i] = bytes!;
      int size = bytes.length;
      double s = size / 1024 / 1024;
      if (s > 20){
        hasMax = true;
        break;
      }
    }

**Comment by AlexV525** [comment]
缩略处理为什么用 `originBytes`？
