### ISSUE TITLE
[BUG] Android: java.lang.IllegalArgumentException: permission cannot be null or empty after updating to 2.5.1

### ISSUE THREAD

**Issue by masewo** [fluttercandies/flutter_photo_manager#878]
**Describe the bug**
After upgrading from 2.5.0 to 2.5.1 no images can be retrieved anymore on a device with Android 13. The permission request dialog does not appear.

**To Reproduce**
1. Use the example app on Android 13 devices

**Expected behavior**
The permission dialog appears and images can be retrieved.

**Flutter version**
<details>
  <summary>Flutter version</summary>
  
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19044.2251], locale de-DE)
    • Flutter version 3.3.9 on channel stable at C:\Users\marcu\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Programme\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = D:\Programme\Android\sdk
    • ANDROID_SDK_ROOT = D:\Programme\Android\sdk
    • Java binary at: D:\Programme\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at D:\Programme\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.1
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\marcu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.122
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: 13
 - Version 2.5.1

**Log**

<details>
  <summary>Logs</summary>
  
E/MethodChannel#com.fluttercandies/photo_manager( 7212): Failed to handle method call
E/MethodChannel#com.fluttercandies/photo_manager( 7212): java.lang.IllegalArgumentException: permission cannot be null or empty
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.content.pm.PackageManager.buildRequestPermissionsIntent(PackageManager.java:6338)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.app.Activity.requestPermissions(Activity.java:5375)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at androidx.core.app.ActivityCompat$Api23Impl.requestPermissions(ActivityCompat.java:893)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:557)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at com.fluttercandies.photo_manager.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.kt:97)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at com.fluttercandies.photo_manager.permission.PermissionsUtils.getPermissions(PermissionsUtils.kt:74)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at com.fluttercandies.photo_manager.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:221)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#com.fluttercandies/photo_manager( 7212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
</details>

**Comment by AlexV525** [comment]
Thanks for the report! Confirmed that permissions are lost during checks.
