### ISSUE TITLE
It always pop "Select More Photos..." dialog when call getAssetPathList on iOS when PermissionState.limited

### ISSUE THREAD

**Issue by dodatw** [fluttercandies/flutter_photo_manager#881]
This is very useful package!

I have a question on iOS,
When the user selects "Limited" permissions. Every time we call "getAssetPathList" after restarting the app, it pops up "Select more photos...".
![IMG_9399](https://user-images.githubusercontent.com/33835425/205536343-716f708b-447b-4356-b3e7-91747fe53c0e.jpg)

Is it possible to disable this dialog?
This dialog interrupts our process.

We also tried `PhotoManager.setIgnorePermissionCheck(true);`, but it seem only work on android.

Thanks.

**Comment by dodatw** [comment]
is it possible? Our first page is a photo picker and I don't want to bother the user with limited access.

**Comment by AlexV525** [comment]
Should be considered as possible. Labeling for further investigations.

**Comment by dimiltagline** [comment]
i've tried to look into native code but it seems there is [no code to call system pop](https://imgur.com/a/gJgdKfY), perhaps it is called automatically by native apis when i request to get images if anyone have idea from where the pop-up is getting called i am happy put PR request if i able to solve issue

**Comment by dimiltagline** [comment]
@AlexV525 it seems to be depend on [this function](https://imgur.com/a/m4skXxE) more specifically highlighted light i've tried to edit code but it comes down to that highlighted line if i comment it pop-up will not show up and images will not be fetched

**Comment by CaiJingLong** [comment]
The `PhotoManager.setIgnorePermissionCheck(true);`   This means that the plug-in does not check permissions, not the system.
There are differences in the handling of the platform without permission (system call, independent of the plug-in). When the API is called without album permission, it has the following performance:
Android: Throw exception=>no catch=>crash
iOS：Show dialog

---
Now， `setIgnorePermissionCheck` works as expected.

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager/issues/974#issue-1858982952

**Comment by njzimpli** [comment]
My app scenario on iOS, it is okay to show pop up, but when user select "select more photo..." and select images,  PhotoManager.getAssetPathList is called onInit and done before user select image complete it seem images will not be fetched.
  
I solved this by using addChangeCallBack
  
```
@override
 void onInit() async {
   PhotoManager.addChangeCallback(changeNotify);
 }

 void changeNotify(MethodCall call) {
   // get change events from native.
   // update assetList.
   assetList.value = await PhotoManager.getAssetPathList(); // Getx RxList
 }
```

Hope it helps.

ps. don't forget to remove change notify.

**Comment by bankuu** [comment]
I solved this issue 

with config PHPhotoLibraryPreventAutomaticLimitedAccessAlert : true 
at Info.plist

```
<dict>
	<key>PHPhotoLibraryPreventAutomaticLimitedAccessAlert</key>
	<true/>
        .......
</dict>
```
After config, The Limited access alert is prevent.
I can create dialog and use presentLimited control manually
Hope it helps.

> This is very useful package!
> 
> I have a question on iOS, When the user selects "Limited" permissions. Every time we call "getAssetPathList" after restarting the app, it pops up "Select more photos...".

**Comment by AlexV525** [comment]
> You can workaround this issue
> 
> with config PHPhotoLibraryPreventAutomaticLimitedAccessAlert : true at Info.plist
> 
> ```
> <dict>
> 	<key>PHPhotoLibraryPreventAutomaticLimitedAccessAlert</key>
> 	<true/>
>         .......
> </dict>
> ```
> 
> After config, The Limited access alert is prevent. I can create dialog and use presentLimited control manually Hope it helps.

Thanks for the clarification. I'll add this to the doc.
