### ISSUE TITLE
[BUG] Failed to load video Error when previewing live photo on iOS

### ISSUE THREAD

**Issue by the-eric-kwok** [fluttercandies/flutter_photo_manager#882]
**Describe the bug**
This bug could be related to wechat_assets_picker, see [this issue](https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/389?notification_referrer_id=NT_kwDOAPs10LM0OTc4MDA1NzU4OjE2NDYzMzEy#issuecomment-1339205727).

When I touch an live photo image to do a preview, Flutter throws an Failed to load video Error. Although the live photo is okay to load as an image after this error thrown. 

```
PlatformException(VideoError, Failed to load video: Cannot Open, null, null)
```

**To Reproduce**
Build with this [demo](https://github.com/fluttercandies/flutter_wechat_assets_picker/files/10166324/wechat_assets_picker_demo.zip).

1. Go to 'Image picker'
2. Allow access on some live photo image
3. Click the live photo image that shows in grid to preview
4. Flutter throws error

**Expected behavior**
Should load live photo normally.

**Screenshots**
Not needed

**Flutter version**

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/eric/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode_14.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3
```

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 15.6
 - Browser: it's not running in browser
 - Version: photo_manager 2.5.1+1

**Log**

If applicable, add logs to help explain your problem.

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Cannot Open, null, null)
```

**Comment by AlexV525** [comment]
Without additional information, the issue is not actionable.
