### ISSUE TITLE
[Feature] Fetch image with DATE_TAKEN

### ISSUE THREAD

**Issue by SuhwanCha** [fluttercandies/flutter_photo_manager#886]
Currently, get path with created time, modified time but get path with photo taken date is not supported.

Filter path with taken date will be useful,
and `AssetEntity` should provide `AssetEntity.AssetTakedDate` or something to fetch date when photo/video is taken

**Comment by SuhwanCha** [comment]
https://github.com/fluttercandies/flutter_photo_manager/blob/eb3799283ea7c8184fd318ad3697ee6276ee5846/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/DBUtils.kt#L177-L218

`getDateCond` only has option that `DATE_ADD` and `DATE_MODIFIED`, but we should add option for `DAKE_TAKEN`

**Comment by SuhwanCha** [comment]
We need to change 
https://github.com/fluttercandies/flutter_photo_manager/blob/eb3799283ea7c8184fd318ad3697ee6276ee5846/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/ConvertUtils.kt#L110-L121
to order by `MediaStore.MediaColumns.DATE_TAKEN`,

add `MediaStore.Images.ImageColumns.DATE_TAKEN` on here,
https://github.com/fluttercandies/flutter_photo_manager/blob/eb3799283ea7c8184fd318ad3697ee6276ee5846/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt#L32-L48

add `MediaStore.Images.ImageColumns.DATE_TAKEN` on here too
https://github.com/fluttercandies/flutter_photo_manager/blob/eb3799283ea7c8184fd318ad3697ee6276ee5846/android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt#L604-L610

**Comment by AlexV525** [comment]
[DATE_TAKEN](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATE_TAKEN) only supports Android 29+, it might be not worth providing this into the `AssetEntity` abstraction.

**Comment by SuhwanCha** [comment]
> [DATE_TAKEN](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DATE_TAKEN) only supports Android 29+, it might be not worth providing this into the `AssetEntity` abstraction.

Umm that may not be worth because we can know through exif. But when fetching media, I think it is useful to filter with DATE_TAKEN.

iOS and android works differently. For example, I've download some image taken in 2020,
and filter image with `createDate > 2020`, iOS doesn't fetch that image because it's taken in 2020.
But, Android fetch that image because it's file created date is 2023 even if it was taken in 2020.

**Comment by AlexV525** [comment]
We can consider to support platform fields for the `FilterOptionGroup` just like the `ThumbnailOption`.

**Comment by hwasoocho** [comment]
Hi, I just wanted to chime in on this issue with a case where this becomes more apparent. When you transfer photos to an android, the native gallery expectedly sorts them by date taken. On the other hand, the create and update timestamps of photo_manager reflect the time when the photos are copied over. So it's currently not possible to replicate the native gallery behavior with copied photos.

**Comment by hwasoocho** [comment]
@AlexV525 Hi, could you provide me some guidance on how the API should look like? I would like to contribute, but I have little understanding about your earlier comment about `ThumbnailOption`. Initially, I thought a small flag like `useDateTaken` would suffice.

**Comment by hwasoocho** [comment]
I've submitted a PR for this issue!
https://github.com/fluttercandies/flutter_photo_manager/pull/914

**Comment by AlexV525** [comment]
This should already addressed by #901. cc @CaiJingLong

**Comment by hwasoocho** [comment]
Oh I wasn't aware! Thank you for the new feature. I added a small PR to fix AssetPathEntity's copyWith to reflect the new change #915
