### ISSUE TITLE
[Feature] Extract video portion from Live photo (IOS)

### ISSUE THREAD

**Issue by Tom3652** [fluttercandies/flutter_photo_manager#887]
**Is your feature request related to a problem? Please describe.**

I would like to be able to extract the little video portion from live photos on iOS because live photos have issues with what i want to do in my app. 

**Describe the solution you'd like**

I have found this link that might answer this : https://stackoverflow.com/questions/32959973/extract-video-portion-from-live-photo.
I think it would be a nice feature to have, in my app it will be very useful.

**Describe alternatives you've considered**

None

**Comment by AlexV525** [comment]
Use `fileWithSubtype` and `originFileWithSubtype` when `isLivePhoto == true` should be able to address your request.

https://github.com/fluttercandies/flutter_photo_manager/blob/eb3799283ea7c8184fd318ad3697ee6276ee5846/lib/src/types/entity.dart#L461-L470

**Comment by Tom3652** [comment]
Thanks it's exactly what i was looking for !
