### ISSUE TITLE
[Feature] How to show album name in chinese?

### ISSUE THREAD

**Issue by ahyangnb** [fluttercandies/flutter_photo_manager#888]
When i get album list use [getAssetPathList] method, then AssetPathEntity->name foreach, all is english.

**Comment by ua741** [comment]
Assuming this question is for IOS, you will need to follow the steps mentioned here

https://github.com/fluttercandies/flutter_photo_manager#localized-system-albums-name

**Comment by ahyangnb** [comment]
> Assuming this question is for IOS, you will need to follow the steps mentioned here
> 
> https://github.com/fluttercandies/flutter_photo_manager#localized-system-albums-name

it is run android.

**Comment by binhdi0111** [comment]
@AlexV525 how to fix for android?
