### ISSUE TITLE
[BUG] Some useful crash report from XCode when usage on the field.

### ISSUE THREAD

**Issue by alextran1502** [fluttercandies/flutter_photo_manager#889]
**Describe the bug**
I am reporting some crashes collected from XCode. I hope it can be helpful during the development and tracking down bugs.

# putAssetEntity
![image](https://user-images.githubusercontent.com/27055614/210626304-038f9280-ce92-4062-bc8f-7b4a1259dfdb.png)

This one causes the majority of crashes. I saw the `onAuth:result` is blocked, which I assume is that the user doesn't allow permission to the library, correct?

# injectModifyToDate
![image](https://user-images.githubusercontent.com/27055614/210626882-ebd01da3-1c3b-4e98-a96a-7d391a7c014d.png)
I also saw that perhaps not allowing permission also causes the crash.

Let me know if I can help get any other information from the crash log to help.

**Comment by AlexV525** [comment]
These logs didn't present anything until more usages code are provided. For example, whether these crashes will happen with the example app.
