### ISSUE TITLE
How to judge the picture is in heif format

### ISSUE THREAD

**Issue by tianxiawoyougood** [fluttercandies/flutter_photo_manager#892]
## Expect
How to judge the picture is in heif format？
`AssetEntity entity`

**Comment by AlexV525** [comment]
What is the main purpose in judging?

**Comment by tianxiawoyougood** [comment]
HEIF files need to be converted to jpg and uploaded to the server. Other image files are uploaded directly.

**Comment by tianxiawoyougood** [comment]
I need to distinguish whether it is a HEIF file or not.

**Comment by AlexV525** [comment]
Use `.file` to upload then, with the getter HEIF will be converted to JPG.

**Comment by tianxiawoyougood** [comment]
Yes, you're right. But other image formats do not want to use `.file`, because it will be inconsistent with the original image, such as size.
I want to be flexible and handle it myself.

**Comment by AlexV525** [comment]
Try `titleAsync` then.
