### ISSUE TITLE
[BUG]java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by liubowen-ola** [fluttercandies/flutter_photo_manager#893]
**Describe the bug**
调用wechat_assets_picker时，底层依赖photo_manager（2.5.2）读取图片时发生异常。
与ThumbnailUtil.getThumbnail中捕获异常的处理方式修改有关。
getThumbnail中出现下述堆栈是否符合预期？

**Smartphone (please complete the following information):
43%
Android 11
26%
Android 12
16%
Android 10
7%
Android 9
8%

**Log**
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Thumbnail request error, java.util.concurrent.ExecutionException: f0.q: Failed to load resource
There were 3 root causes:
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
java.lang.RuntimeException(setDataSource failed: status = 0x80000000)
 call GlideException#logRootCauses(String) for more detail, null, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at DefaultAssetPickerProvider.getThumbnailFromPath(asset_picker_provider.dart:413)

**Comment by AlexV525** [comment]
Those exceptions are only related to the underlying platform rather than the plugin itself.
