### ISSUE TITLE
[BUG] getAssetPathList return empty list

### ISSUE THREAD

**Issue by park1120** [fluttercandies/flutter_photo_manager#895]
**Describe the bug**
getAssetPathList return empty list even though permission has granted.

problem on device: samsung galaxy Android 13 version

works fine in android 12 version.

**To Reproduce**
1. requestPermissionExtend
2. then getAssetPathList
3. always return empty on the device mentioned above(galaxy and Android 13)

**Expected behavior**
must be returned with albums

**Screenshots**

**Flutter version**

Flutter version 3.3.10

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s20 
 - OS: Android 13

**Log**

No error log

**Comment by huongrealest** [comment]
https://github.com/fluttercandies/flutter_photo_manager/issues/852#issuecomment-1373675941
