### ISSUE TITLE
[BUG] In iOS Create folder time crash Occurs.

### ISSUE THREAD

**Issue by GrowAndroid** [fluttercandies/flutter_photo_manager#898]
This Same crash occurs in your example code please check and then ping me.
My Code : 
var asset = await PhotoManager.editor.darwin.createFolder(
                                  'Test',
                                parent: null
                              );

Error :
-[PHCollectionList assetCollectionSubtype]: unrecognized selector sent to instance 0x280124820
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHCollectionList assetCollectionSubtype]: unrecognized selector sent to instance 0x280124820'
*** First throw call stack:
(0x18b562db4 0x1899ed9a0 0x18b6c2c24 0x18b577f58 0x18b5db98c 0x100c8c628 0x100c96a58 0x1970fa850 0x1970fb7c8 0x1970d2b2c 0x1970dfd48 0x1970e0514 0x1d7610b14 0x1d761067c)
libc++abi: terminating with uncaught exception of type NSException
* thread #62, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
    frame #0: 0x00000001c8a542f4 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1c8a542f4 <+8>:  b.lo   0x1c8a54310               ; <+36>
    0x1c8a542f8 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1c8a542fc <+16>: mov    x29, sp
    0x1c8a54300 <+20>: bl     0x1c8a4fcd4               ; cerror_nocancel

**Comment by AlexV525** [comment]
Please provide device info, and better to make a screen record using simulators.
