### ISSUE TITLE
Filter Empty album like containsEmptyAlbum before

### ISSUE THREAD

**Issue by dodatw** [fluttercandies/flutter_photo_manager#910]
### Platforms

iOS

### Description

Is it possiable add a parameter that can filter empty album ?

### Why

After 2.x, `containsEmptyAlbum`. be removed.
It is slow that query assetCountAsync to check is count != 0.

**Comment by AlexV525** [comment]
This is intended as described in https://github.com/fluttercandies/flutter_photo_manager/issues/750#issuecomment-1163946519.
