### ISSUE TITLE
[How to use] How to get a list of only user-created albums

### ISSUE THREAD

**Issue by hukusuke1007** [fluttercandies/flutter_photo_manager#924]
### Platforms

iOS

### Description

I would like to know how to get a list of only user created albums.

In iOS,

PHAssetCollectionType:PHAssetCollectionTypeAlbum,
PHAssetCollectionSubtype: PHAssetCollectionSubtypeAlbumRegular

I think I could get it by specifying.

Since PHAssetCollectionSubtype is specified as PHAssetCollectionSubtypeAny for this library, non-albums created by the user are also retrieved.

Is it possible to retrieve a list of only user-created albums by setting the filterOption of photo_manager?

### My code

```dart
 final paths = await PhotoManager.getAssetPathList(
    type: RequestType.video,
    filterOption: FilterOptionGroup(
      videoOption: FilterOption(needTitle: true),// Filter???
    ),
  );
```

**Comment by AlexV525** [comment]
Is AlbumRegular not included in Any?
