### ISSUE TITLE
Unable to rename a folder

### ISSUE THREAD

**Issue by Helocominc** [fluttercandies/flutter_photo_manager#965]
### Platforms

Android

### Description

I am trying to rename  **Recent** folder in Android to **All Media**. Unfortunately I couldn't find a method to use in the photo_manager package for renaming folders. 

How can I be be able to rename folder using photo_manager?

**Comment by AlexV525** [comment]
No. However, you can map the name to what you desire.

**Comment by Helocominc** [comment]
@AlexV525 I am not trying to rename the folder in the device but on my app. Something like changing the folder name .

**Comment by AlexV525** [comment]
```dart
if (path.isAll) return 'All Media';
return path.name;
```
