### ISSUE TITLE
android配置文件缺少package标签，导致编译失败

### ISSUE THREAD

**Issue by zdc939023** [fluttercandies/flutter_photo_manager#968]
### Version

2.7.1

### Platforms

Android

### Device Model

所有设备

### flutter info

```sh
在2.7.1版本的AndroidManifest.xml文件里面缺少package标签
应该是这样的
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
package="com.fluttercandies.photo_manager">

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

</manifest>
```

### How to reproduce?

<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
package="com.fluttercandies.photo_manager">

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

</manifest>

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/flutter_photo_manager#android-config-preparation
