### ISSUE TITLE
[Bug report] 部份视频获取宽高的时候，宽高都是0，或者是反的

### ISSUE THREAD

**Issue by imtagtalk** [fluttercandies/flutter_photo_manager#973]
### Version

2.7.0

### Platforms

dart

### Device Model

huawei  p20

### flutter info

```sh
部份视频获取宽高的时候，宽高都是0，或者是反的
```

### How to reproduce?

部份视频获取宽高的时候，宽高都是0，或者是反的

**Comment by CaiJingLong** [comment]
Try to load `orientation`?
