### ISSUE TITLE
[Feature request] 在选择可访问照片为选择的照片时减少弹窗要求访问权限 | Not show dialog when allow access "Selected Photos"

### ISSUE THREAD

**Issue by andychucs** [fluttercandies/flutter_photo_manager#974]
### Platforms

iOS

### Description

在调用PhotoManager.getAssetPathList时会自动请求权限，如果访问范围是选择的照片就会在调用时出现访问请求的弹窗。
这个情况我只在真机测试时发现，模拟器不会。
希望能添加一个限制权限请求的功能。

### Why

我的应用在第一屏调用了PhotoManager.getAssetPathList， 应用启动时功能正常没有弹窗请求访问权限，但是当这个组件被销毁重建时就会弹窗，此后再次重复销毁重建这个组件则不会再触发弹窗，每次打开操作一下就会重新请求权限感觉很奇怪。

我注意到有key可以限制弹窗请求，是否能实现手动控制该弹窗的出现
https://developer.apple.com/documentation/photokit/phphotolibrary/3616113-presentlimitedlibrarypickerfromv

**Comment by AlexV525** [comment]
Duplicated of #974
