### ISSUE TITLE
[Bug report][iOS] For assets with adjustments/filters, return original name instead of FullSizeRender.*

### ISSUE THREAD

**Issue by ua741** [fluttercandies/flutter_photo_manager#976]
### Version

2.7.1

### Platforms

iOS, macOS

### Device Model

Any

### flutter info

```sh
flutter 3.10.6
```

### How to reproduce?

* Using native photos app, turn off the video of a live photo.
* Get the title for that asset. It shows FullSizeRender.jpg as asset name.

Related Threads:

https://discussions.apple.com/thread/6849595

Sample reference:
How owncloud iOS app had fixed similar issue in the past:
https://github.com/owncloud/ios-app/pull/522/files#diff-8f5e53a932df183d0057b50091c72ea54c1524c4917b548a973448a95234e5ee
<img width="751" alt="image" src="https://github.com/fluttercandies/flutter_photo_manager/assets/254676/74fd4801-2a5d-4b73-9338-d7fc1be3058e">

### Logs

```sh
NA
```

### Contact

ua741

**Comment by xick** [comment]
Can confirm. Also is worth to mention that currently there is no options provided (correct me if I’m wrong)  to get the original file instead of the altered one. 
We’d need a method to get original file name if a given pic has modifications

**Comment by AlexV525** [comment]
@ua741 Would you be able to submit a PR for this? We're currently occupied by another refactoring of permissions.

**Comment by xick** [comment]
I'm currently trying work on this too, If you want have a look here (I'm still have to run tests) @ua741 https://github.com/fluttercandies/flutter_photo_manager/commit/122b1db2f95439de687d781ddfce0fbd1ca8bcbf

**Comment by AlexV525** [comment]
The #990 seems not covering full cases, unfortunately.

**Comment by AlexV525** [comment]
Recent changes might affect the behavior again, please let me know if you see any related unexpected filenames.
