### ISSUE TITLE
[Bug] iOS : need add permission

### ISSUE THREAD

**Issue by lionnner** [fluttercandies/flutter_photo_manager#979]
Version

2.7.1

Platforms

iOS

Device Model

iPhone 12 (iOS 16.6)
flutter info

flutter 3.10.7
How to reproduce?
when "requestPermissionExtend" method callbak 'PHAuthorizationStatusLimited' to Flutter, then use 'saveImageWithPath' method while callback "need add permission"

**Comment by AlexV525** [comment]
- We don't have a package version called `3.7.1`.
- Add-only permission is invalid when the permission is limited for the camera picker since it cannot obtain the `AssetEntity` after being captured.

Closing as won't fix. You can still leave comments if you disagree or can provide more context.

**Comment by lionnner** [comment]
> * We don't have a package version called `3.7.1`.
> * Add-only permission is invalid when the permission is limited for the camera picker since it cannot obtain the `AssetEntity` after being captured.
> 
> Closing as won't fix. You can still leave comments if you disagree or can provide more context.


Version: 2.7.1
when photo permission is PHAuthorizationStatusLimited , 'saveImageWithPath' method actually can save image success. but callback 'need add permission' because auth = PHAuthorizationStatusAuthorized == status

**Comment by AlexV525** [comment]
As I said above, obtaining the `AssetEntity` after being captured requires full access permission.

**Comment by lionnner** [comment]
> As I said above, obtaining the `AssetEntity` after being captured requires full access permission.

for 'saveImageWithPath' PHAuthorizationStatusLimited is sufficient，save success and 'assetId' has value, 
The requested image list also includes this previously saved image.

**Comment by lionnner** [comment]
So when using the 'wechat_camera_picker' plugin and the photo library permission is 'PHAuthorizationStatusLimited,' an exception will always be thrown, and the camera functionality will be disabled."

**Comment by CaiJingLong** [comment]
Maybe about:

https://github.com/fluttercandies/flutter_photo_manager/blob/5cbb6c6e3fd576a3c007820563b5acd20e860549/ios/Classes/core/PMManager.m#L394-L396

**Comment by AlexV525** [comment]
> Maybe about:
> 
> https://github.com/fluttercandies/flutter_photo_manager/blob/5cbb6c6e3fd576a3c007820563b5acd20e860549/ios/Classes/core/PMManager.m#L394-L396

@lionnner If you're able to debug, remove the above line and check whether it fixes your case.

**Comment by lionnner** [comment]
> Maybe about:
> 
> https://github.com/fluttercandies/flutter_photo_manager/blob/5cbb6c6e3fd576a3c007820563b5acd20e860549/ios/Classes/core/PMManager.m#L394-L396

Sure, this is just a part

**Comment by lionnner** [comment]
I attempted to modify the following code, and it resolves my issue.
PMPlugin.m
`- (void)replyPermssionResult:(ResultHandler *)handler status:(PHAuthorizationStatus)status isOnlyAdd:(BOOL)isOnlyAdd {
    BOOL auth;
    if (@available(iOS 14, *)) {
        auth = PHAuthorizationStatusAuthorized == status ||  PHAuthorizationStatusLimited == status;
    } else {
        auth = PHAuthorizationStatusAuthorized == status;
    }
    if (isOnlyAdd) {
        [self.manager setOnlyAddAuth:auth];
    } else {
        [self.manager setAuth:auth];
    }
    [handler reply:@(status)];
}
`

**Comment by CaiJingLong** [comment]
I pushed a commit(5f7fe257af6909433838e86812c10f3a1d5c1c5a) to test the problem.

When I saved asset, as long as I need to obtain asset information, the read permission dialog will be triggered, even if I have the onlyAdd permission.

---

[example/lib/page/developer/issues_page/issue_979.dart][issue]

[issue]: https://github.com/fluttercandies/flutter_photo_manager/blob/main/example/lib/page/developer/issues_page/issue_979.dart
