### ISSUE TITLE
[Feature request] I want create new folder in photomanager library but the new folder not created in photomanager and I want to move image from one folder to another folder the image also not moved.not work on android.

### ISSUE THREAD

**Issue by Vishvas2416** [fluttercandies/flutter_photo_manager#980]
### Platforms

dart, Android, iOS

### Description

thunbData

### Why

i want to get thumbnail of the asset to display in the list

**Comment by AlexV525** [comment]
Your title is nothing related to your comment. Closing and please provide more accurate info if you can later.

**Comment by Vishvas2416** [comment]
Sir in photomanager library we are fetching gallery folder (directory) but I am trying to create new the folder the  is created but not added  to the photomanager library folder list.

**Comment by Vishvas2416** [comment]
Sir In Photomanager library we are fetching Gallery Folder the folders are display perfectly but I am creating new folder the folder also created but the created folder not added to the Photomanager folder list.

**Comment by Vishvas2416** [comment]
Sir By Using Photomanager library I fetched all the Gallery Folders from the mobile and all folders are show and I see the images inside the each  folders but I want to create new folder. I create new custom folder but the created folder is not added to the all folder list (photomanager).
