### ISSUE TITLE
[How to use] Is the `id` field of the AssetEntity class unique

### ISSUE THREAD

**Issue by joshpetit** [fluttercandies/flutter_photo_manager#981]
### Platforms

Android, iOS

### Description

I'm wondering if the AssetEntity `id` field will always be the same for an image and if it will always be unique.

**Comment by AlexV525** [comment]
It's locally unique.

**Comment by zhahouming** [comment]
If the content of the photo changes, will the ID change? What is the generation mechanism of the ID?
